/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteUsersId401,
  DeleteUsersId403,
  DeleteUsersId404,
  DeleteUsersId500,
  DeleteUsersIdRole200,
  DeleteUsersIdRole401,
  DeleteUsersIdRole403,
  DeleteUsersIdRole404,
  DeleteUsersIdRole500,
  GetUsers200,
  GetUsers401,
  GetUsers403,
  GetUsers500,
  GetUsersCounts200,
  GetUsersCounts401,
  GetUsersCounts403,
  GetUsersCounts500,
  GetUsersId200,
  GetUsersId401,
  GetUsersId403,
  GetUsersId404,
  GetUsersId500,
  GetUsersMe200,
  GetUsersMe401,
  GetUsersMe500,
  GetUsersParams,
  GithubCom4H1RZooraInternalDomainAssignRoleDTO,
  GithubCom4H1RZooraInternalDomainChangePasswordDTO,
  GithubCom4H1RZooraInternalDomainCreateUserDTO,
  GithubCom4H1RZooraInternalDomainDisableUserDTO,
  GithubCom4H1RZooraInternalDomainResponse,
  GithubCom4H1RZooraInternalDomainUpdateProfileDTO,
  GithubCom4H1RZooraInternalDomainUpdateUserDTO,
  PostUsers201,
  PostUsers400,
  PostUsers401,
  PostUsers403,
  PostUsers500,
  PostUsersIdDisable200,
  PostUsersIdDisable400,
  PostUsersIdDisable401,
  PostUsersIdDisable403,
  PostUsersIdDisable404,
  PostUsersIdDisable500,
  PostUsersIdEnable200,
  PostUsersIdEnable401,
  PostUsersIdEnable403,
  PostUsersIdEnable404,
  PostUsersIdEnable500,
  PostUsersMePassword400,
  PostUsersMePassword401,
  PostUsersMePassword500,
  PutUsersId200,
  PutUsersId400,
  PutUsersId401,
  PutUsersId403,
  PutUsersId404,
  PutUsersId500,
  PutUsersIdRole200,
  PutUsersIdRole400,
  PutUsersIdRole401,
  PutUsersIdRole403,
  PutUsersIdRole404,
  PutUsersIdRole500,
  PutUsersMe200,
  PutUsersMe400,
  PutUsersMe401,
  PutUsersMe500
} from '../model';

import { customInstance } from '.././mutator/custom-instance';
import type { ErrorType } from '.././mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getUsersResponse200 = {
  data: GetUsers200
  status: 200
}

export type getUsersResponse401 = {
  data: GetUsers401
  status: 401
}

export type getUsersResponse403 = {
  data: GetUsers403
  status: 403
}

export type getUsersResponse500 = {
  data: GetUsers500
  status: 500
}

export type getUsersResponseSuccess = (getUsersResponse200) & {
  headers: Headers;
};
export type getUsersResponseError = (getUsersResponse401 | getUsersResponse403 | getUsersResponse500) & {
  headers: Headers;
};

export type getUsersResponse = (getUsersResponseSuccess | getUsersResponseError)

export const getGetUsersUrl = (params?: GetUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users?${stringifiedParams}` : `/users`
}

/**
 * Returns users scoped by caller role. Search matches substrings of: username, name. Orderable fields: created_at, updated_at, username, name.
 * @summary List users
 */
export const getUsers = async (params?: GetUsersParams, options?: RequestInit): Promise<getUsersResponse> => {

  return customInstance<getUsersResponse>(getGetUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersQueryKey = (params?: GetUsersParams,) => {
    return [
    `/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetUsersQueryOptions = <TData = Awaited<ReturnType<typeof getUsers>>, TError = ErrorType<GetUsers401 | GetUsers403 | GetUsers500>>(params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsers>>> = ({ signal }) => getUsers(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>
export type GetUsersQueryError = ErrorType<GetUsers401 | GetUsers403 | GetUsers500>


export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = ErrorType<GetUsers401 | GetUsers403 | GetUsers500>>(
 params: undefined |  GetUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = ErrorType<GetUsers401 | GetUsers403 | GetUsers500>>(
 params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsers>>,
          TError,
          Awaited<ReturnType<typeof getUsers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = ErrorType<GetUsers401 | GetUsers403 | GetUsers500>>(
 params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List users
 */

export function useGetUsers<TData = Awaited<ReturnType<typeof getUsers>>, TError = ErrorType<GetUsers401 | GetUsers403 | GetUsers500>>(
 params?: GetUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postUsersResponse201 = {
  data: PostUsers201
  status: 201
}

export type postUsersResponse400 = {
  data: PostUsers400
  status: 400
}

export type postUsersResponse401 = {
  data: PostUsers401
  status: 401
}

export type postUsersResponse403 = {
  data: PostUsers403
  status: 403
}

export type postUsersResponse500 = {
  data: PostUsers500
  status: 500
}

export type postUsersResponseSuccess = (postUsersResponse201) & {
  headers: Headers;
};
export type postUsersResponseError = (postUsersResponse400 | postUsersResponse401 | postUsersResponse403 | postUsersResponse500) & {
  headers: Headers;
};

export type postUsersResponse = (postUsersResponseSuccess | postUsersResponseError)

export const getPostUsersUrl = () => {




  return `/users`
}

/**
 * @summary Create user
 */
export const postUsers = async (githubCom4H1RZooraInternalDomainCreateUserDTO: GithubCom4H1RZooraInternalDomainCreateUserDTO, options?: RequestInit): Promise<postUsersResponse> => {

  return customInstance<postUsersResponse>(getPostUsersUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainCreateUserDTO)
  }
);}




export const getPostUsersMutationOptions = <TError = ErrorType<PostUsers400 | PostUsers401 | PostUsers403 | PostUsers500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsers>>, TError,{data: GithubCom4H1RZooraInternalDomainCreateUserDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postUsers>>, TError,{data: GithubCom4H1RZooraInternalDomainCreateUserDTO}, TContext> => {

const mutationKey = ['postUsers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUsers>>, {data: GithubCom4H1RZooraInternalDomainCreateUserDTO}> = (props) => {
          const {data} = props ?? {};

          return  postUsers(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUsersMutationResult = NonNullable<Awaited<ReturnType<typeof postUsers>>>
    export type PostUsersMutationBody = GithubCom4H1RZooraInternalDomainCreateUserDTO
    export type PostUsersMutationError = ErrorType<PostUsers400 | PostUsers401 | PostUsers403 | PostUsers500>

    /**
 * @summary Create user
 */
export const usePostUsers = <TError = ErrorType<PostUsers400 | PostUsers401 | PostUsers403 | PostUsers500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsers>>, TError,{data: GithubCom4H1RZooraInternalDomainCreateUserDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUsers>>,
        TError,
        {data: GithubCom4H1RZooraInternalDomainCreateUserDTO},
        TContext
      > => {
      return useMutation(getPostUsersMutationOptions(options), queryClient);
    }
    export type getUsersCountsResponse200 = {
  data: GetUsersCounts200
  status: 200
}

export type getUsersCountsResponse401 = {
  data: GetUsersCounts401
  status: 401
}

export type getUsersCountsResponse403 = {
  data: GetUsersCounts403
  status: 403
}

export type getUsersCountsResponse500 = {
  data: GetUsersCounts500
  status: 500
}

export type getUsersCountsResponseSuccess = (getUsersCountsResponse200) & {
  headers: Headers;
};
export type getUsersCountsResponseError = (getUsersCountsResponse401 | getUsersCountsResponse403 | getUsersCountsResponse500) & {
  headers: Headers;
};

export type getUsersCountsResponse = (getUsersCountsResponseSuccess | getUsersCountsResponseError)

export const getGetUsersCountsUrl = () => {




  return `/users/counts`
}

/**
 * Returns all/active/disabled user counts scoped by caller role. Backs the status tabs on the users list.
 * @summary User status counts
 */
export const getUsersCounts = async ( options?: RequestInit): Promise<getUsersCountsResponse> => {

  return customInstance<getUsersCountsResponse>(getGetUsersCountsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersCountsQueryKey = () => {
    return [
    `/users/counts`
    ] as const;
    }


export const getGetUsersCountsQueryOptions = <TData = Awaited<ReturnType<typeof getUsersCounts>>, TError = ErrorType<GetUsersCounts401 | GetUsersCounts403 | GetUsersCounts500>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersCounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersCountsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersCounts>>> = ({ signal }) => getUsersCounts({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersCounts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersCountsQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersCounts>>>
export type GetUsersCountsQueryError = ErrorType<GetUsersCounts401 | GetUsersCounts403 | GetUsersCounts500>


export function useGetUsersCounts<TData = Awaited<ReturnType<typeof getUsersCounts>>, TError = ErrorType<GetUsersCounts401 | GetUsersCounts403 | GetUsersCounts500>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersCounts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersCounts>>,
          TError,
          Awaited<ReturnType<typeof getUsersCounts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersCounts<TData = Awaited<ReturnType<typeof getUsersCounts>>, TError = ErrorType<GetUsersCounts401 | GetUsersCounts403 | GetUsersCounts500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersCounts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersCounts>>,
          TError,
          Awaited<ReturnType<typeof getUsersCounts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersCounts<TData = Awaited<ReturnType<typeof getUsersCounts>>, TError = ErrorType<GetUsersCounts401 | GetUsersCounts403 | GetUsersCounts500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersCounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary User status counts
 */

export function useGetUsersCounts<TData = Awaited<ReturnType<typeof getUsersCounts>>, TError = ErrorType<GetUsersCounts401 | GetUsersCounts403 | GetUsersCounts500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersCounts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersCountsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getUsersMeResponse200 = {
  data: GetUsersMe200
  status: 200
}

export type getUsersMeResponse401 = {
  data: GetUsersMe401
  status: 401
}

export type getUsersMeResponse500 = {
  data: GetUsersMe500
  status: 500
}

export type getUsersMeResponseSuccess = (getUsersMeResponse200) & {
  headers: Headers;
};
export type getUsersMeResponseError = (getUsersMeResponse401 | getUsersMeResponse500) & {
  headers: Headers;
};

export type getUsersMeResponse = (getUsersMeResponseSuccess | getUsersMeResponseError)

export const getGetUsersMeUrl = () => {




  return `/users/me`
}

/**
 * @summary Get my profile
 */
export const getUsersMe = async ( options?: RequestInit): Promise<getUsersMeResponse> => {

  return customInstance<getUsersMeResponse>(getGetUsersMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersMeQueryKey = () => {
    return [
    `/users/me`
    ] as const;
    }


export const getGetUsersMeQueryOptions = <TData = Awaited<ReturnType<typeof getUsersMe>>, TError = ErrorType<GetUsersMe401 | GetUsersMe500>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersMe>>> = ({ signal }) => getUsersMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersMeQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersMe>>>
export type GetUsersMeQueryError = ErrorType<GetUsersMe401 | GetUsersMe500>


export function useGetUsersMe<TData = Awaited<ReturnType<typeof getUsersMe>>, TError = ErrorType<GetUsersMe401 | GetUsersMe500>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersMe>>,
          TError,
          Awaited<ReturnType<typeof getUsersMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersMe<TData = Awaited<ReturnType<typeof getUsersMe>>, TError = ErrorType<GetUsersMe401 | GetUsersMe500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersMe>>,
          TError,
          Awaited<ReturnType<typeof getUsersMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersMe<TData = Awaited<ReturnType<typeof getUsersMe>>, TError = ErrorType<GetUsersMe401 | GetUsersMe500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get my profile
 */

export function useGetUsersMe<TData = Awaited<ReturnType<typeof getUsersMe>>, TError = ErrorType<GetUsersMe401 | GetUsersMe500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type putUsersMeResponse200 = {
  data: PutUsersMe200
  status: 200
}

export type putUsersMeResponse400 = {
  data: PutUsersMe400
  status: 400
}

export type putUsersMeResponse401 = {
  data: PutUsersMe401
  status: 401
}

export type putUsersMeResponse500 = {
  data: PutUsersMe500
  status: 500
}

export type putUsersMeResponseSuccess = (putUsersMeResponse200) & {
  headers: Headers;
};
export type putUsersMeResponseError = (putUsersMeResponse400 | putUsersMeResponse401 | putUsersMeResponse500) & {
  headers: Headers;
};

export type putUsersMeResponse = (putUsersMeResponseSuccess | putUsersMeResponseError)

export const getPutUsersMeUrl = () => {




  return `/users/me`
}

/**
 * @summary Update my profile
 */
export const putUsersMe = async (githubCom4H1RZooraInternalDomainUpdateProfileDTO: GithubCom4H1RZooraInternalDomainUpdateProfileDTO, options?: RequestInit): Promise<putUsersMeResponse> => {

  return customInstance<putUsersMeResponse>(getPutUsersMeUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainUpdateProfileDTO)
  }
);}




export const getPutUsersMeMutationOptions = <TError = ErrorType<PutUsersMe400 | PutUsersMe401 | PutUsersMe500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUsersMe>>, TError,{data: GithubCom4H1RZooraInternalDomainUpdateProfileDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putUsersMe>>, TError,{data: GithubCom4H1RZooraInternalDomainUpdateProfileDTO}, TContext> => {

const mutationKey = ['putUsersMe'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putUsersMe>>, {data: GithubCom4H1RZooraInternalDomainUpdateProfileDTO}> = (props) => {
          const {data} = props ?? {};

          return  putUsersMe(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutUsersMeMutationResult = NonNullable<Awaited<ReturnType<typeof putUsersMe>>>
    export type PutUsersMeMutationBody = GithubCom4H1RZooraInternalDomainUpdateProfileDTO
    export type PutUsersMeMutationError = ErrorType<PutUsersMe400 | PutUsersMe401 | PutUsersMe500>

    /**
 * @summary Update my profile
 */
export const usePutUsersMe = <TError = ErrorType<PutUsersMe400 | PutUsersMe401 | PutUsersMe500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUsersMe>>, TError,{data: GithubCom4H1RZooraInternalDomainUpdateProfileDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putUsersMe>>,
        TError,
        {data: GithubCom4H1RZooraInternalDomainUpdateProfileDTO},
        TContext
      > => {
      return useMutation(getPutUsersMeMutationOptions(options), queryClient);
    }
    export type postUsersMePasswordResponse200 = {
  data: GithubCom4H1RZooraInternalDomainResponse
  status: 200
}

export type postUsersMePasswordResponse400 = {
  data: PostUsersMePassword400
  status: 400
}

export type postUsersMePasswordResponse401 = {
  data: PostUsersMePassword401
  status: 401
}

export type postUsersMePasswordResponse500 = {
  data: PostUsersMePassword500
  status: 500
}

export type postUsersMePasswordResponseSuccess = (postUsersMePasswordResponse200) & {
  headers: Headers;
};
export type postUsersMePasswordResponseError = (postUsersMePasswordResponse400 | postUsersMePasswordResponse401 | postUsersMePasswordResponse500) & {
  headers: Headers;
};

export type postUsersMePasswordResponse = (postUsersMePasswordResponseSuccess | postUsersMePasswordResponseError)

export const getPostUsersMePasswordUrl = () => {




  return `/users/me/password`
}

/**
 * @summary Change my password
 */
export const postUsersMePassword = async (githubCom4H1RZooraInternalDomainChangePasswordDTO: GithubCom4H1RZooraInternalDomainChangePasswordDTO, options?: RequestInit): Promise<postUsersMePasswordResponse> => {

  return customInstance<postUsersMePasswordResponse>(getPostUsersMePasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainChangePasswordDTO)
  }
);}




export const getPostUsersMePasswordMutationOptions = <TError = ErrorType<PostUsersMePassword400 | PostUsersMePassword401 | PostUsersMePassword500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsersMePassword>>, TError,{data: GithubCom4H1RZooraInternalDomainChangePasswordDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postUsersMePassword>>, TError,{data: GithubCom4H1RZooraInternalDomainChangePasswordDTO}, TContext> => {

const mutationKey = ['postUsersMePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUsersMePassword>>, {data: GithubCom4H1RZooraInternalDomainChangePasswordDTO}> = (props) => {
          const {data} = props ?? {};

          return  postUsersMePassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUsersMePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postUsersMePassword>>>
    export type PostUsersMePasswordMutationBody = GithubCom4H1RZooraInternalDomainChangePasswordDTO
    export type PostUsersMePasswordMutationError = ErrorType<PostUsersMePassword400 | PostUsersMePassword401 | PostUsersMePassword500>

    /**
 * @summary Change my password
 */
export const usePostUsersMePassword = <TError = ErrorType<PostUsersMePassword400 | PostUsersMePassword401 | PostUsersMePassword500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsersMePassword>>, TError,{data: GithubCom4H1RZooraInternalDomainChangePasswordDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUsersMePassword>>,
        TError,
        {data: GithubCom4H1RZooraInternalDomainChangePasswordDTO},
        TContext
      > => {
      return useMutation(getPostUsersMePasswordMutationOptions(options), queryClient);
    }
    export type getUsersIdResponse200 = {
  data: GetUsersId200
  status: 200
}

export type getUsersIdResponse401 = {
  data: GetUsersId401
  status: 401
}

export type getUsersIdResponse403 = {
  data: GetUsersId403
  status: 403
}

export type getUsersIdResponse404 = {
  data: GetUsersId404
  status: 404
}

export type getUsersIdResponse500 = {
  data: GetUsersId500
  status: 500
}

export type getUsersIdResponseSuccess = (getUsersIdResponse200) & {
  headers: Headers;
};
export type getUsersIdResponseError = (getUsersIdResponse401 | getUsersIdResponse403 | getUsersIdResponse404 | getUsersIdResponse500) & {
  headers: Headers;
};

export type getUsersIdResponse = (getUsersIdResponseSuccess | getUsersIdResponseError)

export const getGetUsersIdUrl = (id: string,) => {




  return `/users/${id}`
}

/**
 * @summary Get user by ID
 */
export const getUsersId = async (id: string, options?: RequestInit): Promise<getUsersIdResponse> => {

  return customInstance<getUsersIdResponse>(getGetUsersIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersIdQueryKey = (id: string,) => {
    return [
    `/users/${id}`
    ] as const;
    }


export const getGetUsersIdQueryOptions = <TData = Awaited<ReturnType<typeof getUsersId>>, TError = ErrorType<GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersId>>> = ({ signal }) => getUsersId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersIdQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersId>>>
export type GetUsersIdQueryError = ErrorType<GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500>


export function useGetUsersId<TData = Awaited<ReturnType<typeof getUsersId>>, TError = ErrorType<GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersId>>,
          TError,
          Awaited<ReturnType<typeof getUsersId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersId<TData = Awaited<ReturnType<typeof getUsersId>>, TError = ErrorType<GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersId>>,
          TError,
          Awaited<ReturnType<typeof getUsersId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersId<TData = Awaited<ReturnType<typeof getUsersId>>, TError = ErrorType<GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user by ID
 */

export function useGetUsersId<TData = Awaited<ReturnType<typeof getUsersId>>, TError = ErrorType<GetUsersId401 | GetUsersId403 | GetUsersId404 | GetUsersId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type putUsersIdResponse200 = {
  data: PutUsersId200
  status: 200
}

export type putUsersIdResponse400 = {
  data: PutUsersId400
  status: 400
}

export type putUsersIdResponse401 = {
  data: PutUsersId401
  status: 401
}

export type putUsersIdResponse403 = {
  data: PutUsersId403
  status: 403
}

export type putUsersIdResponse404 = {
  data: PutUsersId404
  status: 404
}

export type putUsersIdResponse500 = {
  data: PutUsersId500
  status: 500
}

export type putUsersIdResponseSuccess = (putUsersIdResponse200) & {
  headers: Headers;
};
export type putUsersIdResponseError = (putUsersIdResponse400 | putUsersIdResponse401 | putUsersIdResponse403 | putUsersIdResponse404 | putUsersIdResponse500) & {
  headers: Headers;
};

export type putUsersIdResponse = (putUsersIdResponseSuccess | putUsersIdResponseError)

export const getPutUsersIdUrl = (id: string,) => {




  return `/users/${id}`
}

/**
 * @summary Update user
 */
export const putUsersId = async (id: string,
    githubCom4H1RZooraInternalDomainUpdateUserDTO: GithubCom4H1RZooraInternalDomainUpdateUserDTO, options?: RequestInit): Promise<putUsersIdResponse> => {

  return customInstance<putUsersIdResponse>(getPutUsersIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainUpdateUserDTO)
  }
);}




export const getPutUsersIdMutationOptions = <TError = ErrorType<PutUsersId400 | PutUsersId401 | PutUsersId403 | PutUsersId404 | PutUsersId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUsersId>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainUpdateUserDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putUsersId>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainUpdateUserDTO}, TContext> => {

const mutationKey = ['putUsersId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putUsersId>>, {id: string;data: GithubCom4H1RZooraInternalDomainUpdateUserDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  putUsersId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutUsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof putUsersId>>>
    export type PutUsersIdMutationBody = GithubCom4H1RZooraInternalDomainUpdateUserDTO
    export type PutUsersIdMutationError = ErrorType<PutUsersId400 | PutUsersId401 | PutUsersId403 | PutUsersId404 | PutUsersId500>

    /**
 * @summary Update user
 */
export const usePutUsersId = <TError = ErrorType<PutUsersId400 | PutUsersId401 | PutUsersId403 | PutUsersId404 | PutUsersId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUsersId>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainUpdateUserDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putUsersId>>,
        TError,
        {id: string;data: GithubCom4H1RZooraInternalDomainUpdateUserDTO},
        TContext
      > => {
      return useMutation(getPutUsersIdMutationOptions(options), queryClient);
    }
    export type deleteUsersIdResponse200 = {
  data: GithubCom4H1RZooraInternalDomainResponse
  status: 200
}

export type deleteUsersIdResponse401 = {
  data: DeleteUsersId401
  status: 401
}

export type deleteUsersIdResponse403 = {
  data: DeleteUsersId403
  status: 403
}

export type deleteUsersIdResponse404 = {
  data: DeleteUsersId404
  status: 404
}

export type deleteUsersIdResponse500 = {
  data: DeleteUsersId500
  status: 500
}

export type deleteUsersIdResponseSuccess = (deleteUsersIdResponse200) & {
  headers: Headers;
};
export type deleteUsersIdResponseError = (deleteUsersIdResponse401 | deleteUsersIdResponse403 | deleteUsersIdResponse404 | deleteUsersIdResponse500) & {
  headers: Headers;
};

export type deleteUsersIdResponse = (deleteUsersIdResponseSuccess | deleteUsersIdResponseError)

export const getDeleteUsersIdUrl = (id: string,) => {




  return `/users/${id}`
}

/**
 * @summary Delete user
 */
export const deleteUsersId = async (id: string, options?: RequestInit): Promise<deleteUsersIdResponse> => {

  return customInstance<deleteUsersIdResponse>(getDeleteUsersIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteUsersIdMutationOptions = <TError = ErrorType<DeleteUsersId401 | DeleteUsersId403 | DeleteUsersId404 | DeleteUsersId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsersId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUsersId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteUsersId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUsersId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteUsersId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUsersId>>>

    export type DeleteUsersIdMutationError = ErrorType<DeleteUsersId401 | DeleteUsersId403 | DeleteUsersId404 | DeleteUsersId500>

    /**
 * @summary Delete user
 */
export const useDeleteUsersId = <TError = ErrorType<DeleteUsersId401 | DeleteUsersId403 | DeleteUsersId404 | DeleteUsersId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsersId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUsersId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteUsersIdMutationOptions(options), queryClient);
    }
    export type postUsersIdDisableResponse200 = {
  data: PostUsersIdDisable200
  status: 200
}

export type postUsersIdDisableResponse400 = {
  data: PostUsersIdDisable400
  status: 400
}

export type postUsersIdDisableResponse401 = {
  data: PostUsersIdDisable401
  status: 401
}

export type postUsersIdDisableResponse403 = {
  data: PostUsersIdDisable403
  status: 403
}

export type postUsersIdDisableResponse404 = {
  data: PostUsersIdDisable404
  status: 404
}

export type postUsersIdDisableResponse500 = {
  data: PostUsersIdDisable500
  status: 500
}

export type postUsersIdDisableResponseSuccess = (postUsersIdDisableResponse200) & {
  headers: Headers;
};
export type postUsersIdDisableResponseError = (postUsersIdDisableResponse400 | postUsersIdDisableResponse401 | postUsersIdDisableResponse403 | postUsersIdDisableResponse404 | postUsersIdDisableResponse500) & {
  headers: Headers;
};

export type postUsersIdDisableResponse = (postUsersIdDisableResponseSuccess | postUsersIdDisableResponseError)

export const getPostUsersIdDisableUrl = (id: string,) => {




  return `/users/${id}/disable`
}

/**
 * @summary Disable user
 */
export const postUsersIdDisable = async (id: string,
    githubCom4H1RZooraInternalDomainDisableUserDTO: GithubCom4H1RZooraInternalDomainDisableUserDTO, options?: RequestInit): Promise<postUsersIdDisableResponse> => {

  return customInstance<postUsersIdDisableResponse>(getPostUsersIdDisableUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainDisableUserDTO)
  }
);}




export const getPostUsersIdDisableMutationOptions = <TError = ErrorType<PostUsersIdDisable400 | PostUsersIdDisable401 | PostUsersIdDisable403 | PostUsersIdDisable404 | PostUsersIdDisable500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsersIdDisable>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainDisableUserDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postUsersIdDisable>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainDisableUserDTO}, TContext> => {

const mutationKey = ['postUsersIdDisable'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUsersIdDisable>>, {id: string;data: GithubCom4H1RZooraInternalDomainDisableUserDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  postUsersIdDisable(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUsersIdDisableMutationResult = NonNullable<Awaited<ReturnType<typeof postUsersIdDisable>>>
    export type PostUsersIdDisableMutationBody = GithubCom4H1RZooraInternalDomainDisableUserDTO
    export type PostUsersIdDisableMutationError = ErrorType<PostUsersIdDisable400 | PostUsersIdDisable401 | PostUsersIdDisable403 | PostUsersIdDisable404 | PostUsersIdDisable500>

    /**
 * @summary Disable user
 */
export const usePostUsersIdDisable = <TError = ErrorType<PostUsersIdDisable400 | PostUsersIdDisable401 | PostUsersIdDisable403 | PostUsersIdDisable404 | PostUsersIdDisable500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsersIdDisable>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainDisableUserDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUsersIdDisable>>,
        TError,
        {id: string;data: GithubCom4H1RZooraInternalDomainDisableUserDTO},
        TContext
      > => {
      return useMutation(getPostUsersIdDisableMutationOptions(options), queryClient);
    }
    export type postUsersIdEnableResponse200 = {
  data: PostUsersIdEnable200
  status: 200
}

export type postUsersIdEnableResponse401 = {
  data: PostUsersIdEnable401
  status: 401
}

export type postUsersIdEnableResponse403 = {
  data: PostUsersIdEnable403
  status: 403
}

export type postUsersIdEnableResponse404 = {
  data: PostUsersIdEnable404
  status: 404
}

export type postUsersIdEnableResponse500 = {
  data: PostUsersIdEnable500
  status: 500
}

export type postUsersIdEnableResponseSuccess = (postUsersIdEnableResponse200) & {
  headers: Headers;
};
export type postUsersIdEnableResponseError = (postUsersIdEnableResponse401 | postUsersIdEnableResponse403 | postUsersIdEnableResponse404 | postUsersIdEnableResponse500) & {
  headers: Headers;
};

export type postUsersIdEnableResponse = (postUsersIdEnableResponseSuccess | postUsersIdEnableResponseError)

export const getPostUsersIdEnableUrl = (id: string,) => {




  return `/users/${id}/enable`
}

/**
 * @summary Enable user
 */
export const postUsersIdEnable = async (id: string, options?: RequestInit): Promise<postUsersIdEnableResponse> => {

  return customInstance<postUsersIdEnableResponse>(getPostUsersIdEnableUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostUsersIdEnableMutationOptions = <TError = ErrorType<PostUsersIdEnable401 | PostUsersIdEnable403 | PostUsersIdEnable404 | PostUsersIdEnable500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsersIdEnable>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postUsersIdEnable>>, TError,{id: string}, TContext> => {

const mutationKey = ['postUsersIdEnable'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUsersIdEnable>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postUsersIdEnable(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostUsersIdEnableMutationResult = NonNullable<Awaited<ReturnType<typeof postUsersIdEnable>>>

    export type PostUsersIdEnableMutationError = ErrorType<PostUsersIdEnable401 | PostUsersIdEnable403 | PostUsersIdEnable404 | PostUsersIdEnable500>

    /**
 * @summary Enable user
 */
export const usePostUsersIdEnable = <TError = ErrorType<PostUsersIdEnable401 | PostUsersIdEnable403 | PostUsersIdEnable404 | PostUsersIdEnable500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUsersIdEnable>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUsersIdEnable>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPostUsersIdEnableMutationOptions(options), queryClient);
    }
    export type putUsersIdRoleResponse200 = {
  data: PutUsersIdRole200
  status: 200
}

export type putUsersIdRoleResponse400 = {
  data: PutUsersIdRole400
  status: 400
}

export type putUsersIdRoleResponse401 = {
  data: PutUsersIdRole401
  status: 401
}

export type putUsersIdRoleResponse403 = {
  data: PutUsersIdRole403
  status: 403
}

export type putUsersIdRoleResponse404 = {
  data: PutUsersIdRole404
  status: 404
}

export type putUsersIdRoleResponse500 = {
  data: PutUsersIdRole500
  status: 500
}

export type putUsersIdRoleResponseSuccess = (putUsersIdRoleResponse200) & {
  headers: Headers;
};
export type putUsersIdRoleResponseError = (putUsersIdRoleResponse400 | putUsersIdRoleResponse401 | putUsersIdRoleResponse403 | putUsersIdRoleResponse404 | putUsersIdRoleResponse500) & {
  headers: Headers;
};

export type putUsersIdRoleResponse = (putUsersIdRoleResponseSuccess | putUsersIdRoleResponseError)

export const getPutUsersIdRoleUrl = (id: string,) => {




  return `/users/${id}/role`
}

/**
 * @summary Assign role to user
 */
export const putUsersIdRole = async (id: string,
    githubCom4H1RZooraInternalDomainAssignRoleDTO: GithubCom4H1RZooraInternalDomainAssignRoleDTO, options?: RequestInit): Promise<putUsersIdRoleResponse> => {

  return customInstance<putUsersIdRoleResponse>(getPutUsersIdRoleUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainAssignRoleDTO)
  }
);}




export const getPutUsersIdRoleMutationOptions = <TError = ErrorType<PutUsersIdRole400 | PutUsersIdRole401 | PutUsersIdRole403 | PutUsersIdRole404 | PutUsersIdRole500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUsersIdRole>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainAssignRoleDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putUsersIdRole>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainAssignRoleDTO}, TContext> => {

const mutationKey = ['putUsersIdRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putUsersIdRole>>, {id: string;data: GithubCom4H1RZooraInternalDomainAssignRoleDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  putUsersIdRole(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutUsersIdRoleMutationResult = NonNullable<Awaited<ReturnType<typeof putUsersIdRole>>>
    export type PutUsersIdRoleMutationBody = GithubCom4H1RZooraInternalDomainAssignRoleDTO
    export type PutUsersIdRoleMutationError = ErrorType<PutUsersIdRole400 | PutUsersIdRole401 | PutUsersIdRole403 | PutUsersIdRole404 | PutUsersIdRole500>

    /**
 * @summary Assign role to user
 */
export const usePutUsersIdRole = <TError = ErrorType<PutUsersIdRole400 | PutUsersIdRole401 | PutUsersIdRole403 | PutUsersIdRole404 | PutUsersIdRole500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUsersIdRole>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainAssignRoleDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putUsersIdRole>>,
        TError,
        {id: string;data: GithubCom4H1RZooraInternalDomainAssignRoleDTO},
        TContext
      > => {
      return useMutation(getPutUsersIdRoleMutationOptions(options), queryClient);
    }
    export type deleteUsersIdRoleResponse200 = {
  data: DeleteUsersIdRole200
  status: 200
}

export type deleteUsersIdRoleResponse401 = {
  data: DeleteUsersIdRole401
  status: 401
}

export type deleteUsersIdRoleResponse403 = {
  data: DeleteUsersIdRole403
  status: 403
}

export type deleteUsersIdRoleResponse404 = {
  data: DeleteUsersIdRole404
  status: 404
}

export type deleteUsersIdRoleResponse500 = {
  data: DeleteUsersIdRole500
  status: 500
}

export type deleteUsersIdRoleResponseSuccess = (deleteUsersIdRoleResponse200) & {
  headers: Headers;
};
export type deleteUsersIdRoleResponseError = (deleteUsersIdRoleResponse401 | deleteUsersIdRoleResponse403 | deleteUsersIdRoleResponse404 | deleteUsersIdRoleResponse500) & {
  headers: Headers;
};

export type deleteUsersIdRoleResponse = (deleteUsersIdRoleResponseSuccess | deleteUsersIdRoleResponseError)

export const getDeleteUsersIdRoleUrl = (id: string,) => {




  return `/users/${id}/role`
}

/**
 * @summary Remove role from user
 */
export const deleteUsersIdRole = async (id: string, options?: RequestInit): Promise<deleteUsersIdRoleResponse> => {

  return customInstance<deleteUsersIdRoleResponse>(getDeleteUsersIdRoleUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteUsersIdRoleMutationOptions = <TError = ErrorType<DeleteUsersIdRole401 | DeleteUsersIdRole403 | DeleteUsersIdRole404 | DeleteUsersIdRole500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsersIdRole>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUsersIdRole>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteUsersIdRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUsersIdRole>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteUsersIdRole(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteUsersIdRoleMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUsersIdRole>>>

    export type DeleteUsersIdRoleMutationError = ErrorType<DeleteUsersIdRole401 | DeleteUsersIdRole403 | DeleteUsersIdRole404 | DeleteUsersIdRole500>

    /**
 * @summary Remove role from user
 */
export const useDeleteUsersIdRole = <TError = ErrorType<DeleteUsersIdRole401 | DeleteUsersIdRole403 | DeleteUsersIdRole404 | DeleteUsersIdRole500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUsersIdRole>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUsersIdRole>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteUsersIdRoleMutationOptions(options), queryClient);
    }
