/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GetAdminUsersParams = {
/**
 * Filter by organization UUID
 */
organization_id?: string;
/**
 * Filter by role UUID
 */
role_id?: string;
/**
 * Filter by admin flag
 */
is_admin?: boolean;
/**
 * Include soft-deleted users
 */
include_deleted?: boolean;
/**
 * Substring match on username/name
 */
search?: string;
/**
 * One of: created_at, updated_at, username, name
 */
order_by?: string;
/**
 * asc or desc
 */
order_dir?: string;
/**
 * 1-based page number
 */
page?: number;
/**
 * Items per page (default 20)
 */
page_size?: number;
};
