/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GetAdminPractices200Data } from './getAdminPractices200Data';
import type { GithubCom4H1RZooraInternalDomainResponse } from './githubCom4H1RZooraInternalDomainResponse';

export type GetAdminPractices200 = GithubCom4H1RZooraInternalDomainResponse & {
  data?: GetAdminPractices200Data;
};
