/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GetAttendanceMeStatus = typeof GetAttendanceMeStatus[keyof typeof GetAttendanceMeStatus];


export const GetAttendanceMeStatus = {
  present: 'present',
  absent: 'absent',
  late: 'late',
  excused: 'excused',
} as const;
