/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GetAdminLeadsParams = {
/**
 * Filter by status (new, contacted, converted, rejected)
 */
status?: string;
/**
 * Substring match on name/org_name/phone
 */
search?: string;
/**
 * One of: created_at, updated_at
 */
order_by?: string;
/**
 * asc or desc
 */
order_dir?: string;
/**
 * 1-based page number
 */
page?: number;
/**
 * Items per page (default 20)
 */
page_size?: number;
};
