/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GetAdminSessionsParams = {
/**
 * Filter by class UUID
 */
class_id?: string;
/**
 * Include soft-deleted sessions
 */
include_deleted?: boolean;
/**
 * Substring match on name/description
 */
search?: string;
/**
 * One of: created_at, updated_at, name, start_time
 */
order_by?: string;
/**
 * asc or desc
 */
order_dir?: string;
/**
 * 1-based page number
 */
page?: number;
};
