/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GetClassesIdSessionsSessionIdAttendanceStatus = typeof GetClassesIdSessionsSessionIdAttendanceStatus[keyof typeof GetClassesIdSessionsSessionIdAttendanceStatus];


export const GetClassesIdSessionsSessionIdAttendanceStatus = {
  present: 'present',
  absent: 'absent',
  late: 'late',
  excused: 'excused',
} as const;
