/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GetClassesIdGradebookColumnsType } from './getClassesIdGradebookColumnsType';

export type GetClassesIdGradebookColumnsParams = {
/**
 * Filter by column type
 */
type?: GetClassesIdGradebookColumnsType;
/**
 * Substring match on title
 */
search?: string;
/**
 * One of: created_at, updated_at, title, order_index
 */
order_by?: string;
/**
 * asc or desc
 */
order_dir?: string;
/**
 * 1-based page number
 */
page?: number;
};
