/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GetCalendarEventsParams = {
/**
 * Range start, RFC3339 (e.g. 2026-06-01T00:00:00Z)
 */
from: string;
/**
 * Range end, RFC3339 (e.g. 2026-06-30T23:59:59Z)
 */
to: string;
};
