/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GetConversationsSearchParams = {
/**
 * Search query (min 3 characters)
 */
q: string;
/**
 * Max results (service default applies if omitted)
 */
limit?: number;
};
