/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GetConversationsParams = {
/**
 * Filter by type: direct, group, channel
 */
type?: string;
/**
 * Substring match on name
 */
search?: string;
/**
 * One of: updated_at, created_at, name
 */
order_by?: string;
/**
 * asc or desc
 */
order_dir?: string;
/**
 * 1-based page number
 */
page?: number;
/**
 * Items per page
 */
page_size?: number;
};
