/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GetFilesOwnersKindFilesOrderBy } from './getFilesOwnersKindFilesOrderBy';
import type { GetFilesOwnersKindFilesOrderDir } from './getFilesOwnersKindFilesOrderDir';

export type GetFilesOwnersKindFilesParams = {
/**
 * Owner UUID (omit for shared/other)
 */
owner_id?: string;
/**
 * Page (1-based)
 */
page?: number;
/**
 * Page size
 */
page_size?: number;
/**
 * Search in file name
 */
search?: string;
/**
 * Order field
 */
order_by?: GetFilesOwnersKindFilesOrderBy;
/**
 * Order direction
 */
order_dir?: GetFilesOwnersKindFilesOrderDir;
};
