/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GetImportsLatestType = typeof GetImportsLatestType[keyof typeof GetImportsLatestType];


export const GetImportsLatestType = {
  users: 'users',
  classes: 'classes',
} as const;
