/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GetOfflines200Data } from './getOfflines200Data';
import type { GithubCom4H1RZooraInternalDomainResponse } from './githubCom4H1RZooraInternalDomainResponse';

export type GetOfflines200 = GithubCom4H1RZooraInternalDomainResponse & {
  data?: GetOfflines200Data;
};
