/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GetPracticesIdSubmissions200Data } from './getPracticesIdSubmissions200Data';
import type { GithubCom4H1RZooraInternalDomainResponse } from './githubCom4H1RZooraInternalDomainResponse';

export type GetPracticesIdSubmissions200 = GithubCom4H1RZooraInternalDomainResponse & {
  data?: GetPracticesIdSubmissions200Data;
};
