/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainQuizTakePreview } from './githubCom4H1RZooraInternalDomainQuizTakePreview';
import type { GithubCom4H1RZooraInternalDomainResponse } from './githubCom4H1RZooraInternalDomainResponse';

export type GetQuizzesIdPreview200 = GithubCom4H1RZooraInternalDomainResponse & {
  data?: GithubCom4H1RZooraInternalDomainQuizTakePreview;
};
