/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainErrorBody } from './githubCom4H1RZooraInternalDomainErrorBody';
import type { GithubCom4H1RZooraInternalDomainResponse } from './githubCom4H1RZooraInternalDomainResponse';

export type GetQa400 = GithubCom4H1RZooraInternalDomainResponse & {
  error?: GithubCom4H1RZooraInternalDomainErrorBody;
};
