/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GetQuizzesIdSubmissionsParams = {
/**
 * Filter by user UUID
 */
user_id?: string;
/**
 * Filter by status (in_progress, submitted, graded)
 */
status?: string;
/**
 * One of: created_at, started_at, submitted_at, total_score
 */
order_by?: string;
/**
 * asc or desc
 */
order_dir?: string;
/**
 * 1-based page number
 */
page?: number;
};
