/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GetTicketsParams = {
/**
 * Filter by class UUID
 */
class_id?: string;
/**
 * Filter by status: open, answered, closed
 */
status?: string;
/**
 * Filter by type: question, grade_objection, other
 */
type?: string;
/**
 * Substring match on title
 */
search?: string;
/**
 * One of: updated_at, created_at, title
 */
order_by?: string;
/**
 * asc or desc
 */
order_dir?: string;
/**
 * 1-based page number
 */
page?: number;
/**
 * Items per page
 */
page_size?: number;
};
