/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainAttendance } from './githubCom4H1RZooraInternalDomainAttendance';
import type { GithubCom4H1RZooraInternalDomainMyAttendanceSummary } from './githubCom4H1RZooraInternalDomainMyAttendanceSummary';

export interface GithubCom4H1RZooraInternalDomainMyAttendance {
  items?: GithubCom4H1RZooraInternalDomainAttendance[];
  summary?: GithubCom4H1RZooraInternalDomainMyAttendanceSummary;
}
