/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainPlan } from './githubCom4H1RZooraInternalDomainPlan';
import type { GithubCom4H1RZooraInternalDomainPlanInfoFeatures } from './githubCom4H1RZooraInternalDomainPlanInfoFeatures';
import type { GithubCom4H1RZooraInternalDomainPlanInfoLimits } from './githubCom4H1RZooraInternalDomainPlanInfoLimits';

export interface GithubCom4H1RZooraInternalDomainPlanInfo {
  features?: GithubCom4H1RZooraInternalDomainPlanInfoFeatures;
  limits?: GithubCom4H1RZooraInternalDomainPlanInfoLimits;
  plan?: GithubCom4H1RZooraInternalDomainPlan;
}
