/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainNotificationChannelReport } from './githubCom4H1RZooraInternalDomainNotificationChannelReport';

export interface GithubCom4H1RZooraInternalDomainNotificationDeliveryReport {
  channels?: GithubCom4H1RZooraInternalDomainNotificationChannelReport[];
  recipients?: number;
}
