/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainClass } from './githubCom4H1RZooraInternalDomainClass';
import type { GithubCom4H1RZooraInternalDomainLiveRoom } from './githubCom4H1RZooraInternalDomainLiveRoom';
import type { GithubCom4H1RZooraInternalDomainOfflineRoom } from './githubCom4H1RZooraInternalDomainOfflineRoom';
import type { GithubCom4H1RZooraInternalDomainPracticeRoom } from './githubCom4H1RZooraInternalDomainPracticeRoom';
import type { GithubCom4H1RZooraInternalDomainQuizRoom } from './githubCom4H1RZooraInternalDomainQuizRoom';

export interface GithubCom4H1RZooraInternalDomainClassSession {
  class?: GithubCom4H1RZooraInternalDomainClass;
  class_id?: string;
  created_at?: string;
  description?: string;
  id?: string;
  live_rooms?: GithubCom4H1RZooraInternalDomainLiveRoom[];
  name?: string;
  offline_rooms?: GithubCom4H1RZooraInternalDomainOfflineRoom[];
  practice_rooms?: GithubCom4H1RZooraInternalDomainPracticeRoom[];
  quiz_rooms?: GithubCom4H1RZooraInternalDomainQuizRoom[];
  start_time?: string;
  updated_at?: string;
}
