/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export interface GithubCom4H1RZooraInternalDomainCreateRoleDTO {
  is_preset?: boolean
  /** @minLength 2 */
  name: string
  organization_id?: string
  /** @minItems 1 */
  permission_ids: string[]
}
