/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export interface GithubCom4H1RZooraInternalDomainSubmissionAnswer {
  earned_score?: number;
  question_id?: string;
  selected_option_ids?: string[];
  spent_seconds?: number;
  value?: string;
}
