/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainGradebookMatrixRowCells } from './githubCom4H1RZooraInternalDomainGradebookMatrixRowCells';
import type { GithubCom4H1RZooraInternalDomainUser } from './githubCom4H1RZooraInternalDomainUser';

export interface GithubCom4H1RZooraInternalDomainGradebookMatrixRow {
  /** column_id -> value */
  cells?: GithubCom4H1RZooraInternalDomainGradebookMatrixRowCells;
  student?: GithubCom4H1RZooraInternalDomainUser;
  student_id?: string;
}
