/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainClass } from './githubCom4H1RZooraInternalDomainClass';
import type { GithubCom4H1RZooraInternalDomainNegativeMarkMode } from './githubCom4H1RZooraInternalDomainNegativeMarkMode';
import type { GithubCom4H1RZooraInternalDomainUser } from './githubCom4H1RZooraInternalDomainUser';

export interface GithubCom4H1RZooraInternalDomainQuiz {
  class?: GithubCom4H1RZooraInternalDomainClass;
  class_id?: string;
  created_at?: string;
  description?: string;
  disable_copy_paste?: boolean;
  disable_right_click_shortcuts?: boolean;
  duration_minutes?: number;
  id?: string;
  /**
     * Quiz-wide negative-marking override (Layer 2b). Fills gaps for questions
     * (manual and random) lacking their own setting.
     */
  negative_mark_mode?: GithubCom4H1RZooraInternalDomainNegativeMarkMode;
  negative_value?: number;
  no_back_navigation?: boolean;
  organization_id?: string;
  require_gps?: boolean;
  /**
     * Anti-cheat config toggles. Class A (enforced): ShuffleOptions. Class B
     * (advisory signals): TrackTabSwitches, RequireGPS. Class C (frontend-only
     * deterrents): DisableCopyPaste, DisableRightClickShortcuts.
     */
  shuffle_options?: boolean;
  shuffle_questions?: boolean;
  title?: string;
  total_score?: number;
  track_tab_switches?: boolean;
  updated_at?: string;
  user?: GithubCom4H1RZooraInternalDomainUser;
  user_id?: string;
  wrongs_per_point?: number;
}
