/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export interface GithubCom4H1RZooraInternalDomainCreateLeadDTO {
  /**
     * @minLength 2
     * @maxLength 255
     */
  name: string;
  /** @maxLength 2000 */
  note?: string;
  /**
     * @minLength 2
     * @maxLength 255
     */
  org_name: string;
  /**
     * @minLength 3
     * @maxLength 32
     */
  phone: string;
  /** @maxLength 32 */
  plan?: string;
  /**
     * Website is a honeypot: hidden from real users via CSS, only bots fill it.
     * A non-empty value means the submission is silently dropped as spam.
     */
  website?: string;
}
