/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GithubCom4H1RZooraInternalDomainUpdateQuizRuleDTOType =
  (typeof GithubCom4H1RZooraInternalDomainUpdateQuizRuleDTOType)[keyof typeof GithubCom4H1RZooraInternalDomainUpdateQuizRuleDTOType]

export const GithubCom4H1RZooraInternalDomainUpdateQuizRuleDTOType = {
  manual: "manual",
  random: "random",
} as const
