/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GithubCom4H1RZooraInternalDomainQuestionBankStatus = typeof GithubCom4H1RZooraInternalDomainQuestionBankStatus[keyof typeof GithubCom4H1RZooraInternalDomainQuestionBankStatus];


export const GithubCom4H1RZooraInternalDomainQuestionBankStatus = {
  QuestionBankStatusReady: 'ready',
  QuestionBankStatusCopying: 'copying',
  QuestionBankStatusFailed: 'failed',
} as const;
