/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainLiveWhiteboardSnapshot } from './githubCom4H1RZooraInternalDomainLiveWhiteboardSnapshot';

export interface GithubCom4H1RZooraInternalDomainLiveWhiteboard {
  created_at?: string;
  id?: string;
  live_room_id?: string;
  snapshot?: GithubCom4H1RZooraInternalDomainLiveWhiteboardSnapshot;
  updated_at?: string;
}
