/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export interface GithubCom4H1RZooraInternalDomainUpdateRoleDTO {
  is_preset?: boolean;
  /** @minLength 2 */
  name?: string;
  permission_ids?: string[];
}
