/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainCustomFieldType } from './githubCom4H1RZooraInternalDomainCustomFieldType';

export interface GithubCom4H1RZooraInternalDomainCreateCustomFieldDefinitionDTO {
  /** @maxLength 1000 */
  description?: string;
  field_type: GithubCom4H1RZooraInternalDomainCustomFieldType;
  is_required?: boolean;
  is_unique?: boolean;
  /**
     * @minLength 1
     * @maxLength 255
     */
  label: string;
  options?: string[];
  visible_to_user?: boolean;
}
