/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainQuiz } from "./githubCom4H1RZooraInternalDomainQuiz"
import type { GithubCom4H1RZooraInternalDomainSubmissionAnswer } from "./githubCom4H1RZooraInternalDomainSubmissionAnswer"
import type { GithubCom4H1RZooraInternalDomainSubmissionStatus } from "./githubCom4H1RZooraInternalDomainSubmissionStatus"
import type { GithubCom4H1RZooraInternalDomainUser } from "./githubCom4H1RZooraInternalDomainUser"

export interface GithubCom4H1RZooraInternalDomainQuizSubmission {
  answers?: GithubCom4H1RZooraInternalDomainSubmissionAnswer[]
  created_at?: string
  id?: string
  quiz?: GithubCom4H1RZooraInternalDomainQuiz
  quiz_id?: string
  started_at?: string
  status?: GithubCom4H1RZooraInternalDomainSubmissionStatus
  submitted_at?: string
  total_score?: number
  updated_at?: string
  user?: GithubCom4H1RZooraInternalDomainUser
  user_id?: string
}
