/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GithubCom4H1RZooraInternalDomainUpdateLeadStatusDTOStatus = typeof GithubCom4H1RZooraInternalDomainUpdateLeadStatusDTOStatus[keyof typeof GithubCom4H1RZooraInternalDomainUpdateLeadStatusDTOStatus];


export const GithubCom4H1RZooraInternalDomainUpdateLeadStatusDTOStatus = {
  new: 'new',
  contacted: 'contacted',
  converted: 'converted',
  rejected: 'rejected',
} as const;
