/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainChangelogEntry } from './githubCom4H1RZooraInternalDomainChangelogEntry';

export interface GithubCom4H1RZooraInternalDomainChangelogStatus {
  current_version?: string;
  has_major_unseen?: boolean;
  latest_major?: GithubCom4H1RZooraInternalDomainChangelogEntry;
  unseen_count?: number;
}
