/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export interface GithubCom4H1RZooraInternalDomainSendConversationMessageDTO {
  /**
     * @minLength 1
     * @maxLength 10000
     */
  content: string;
  /** client-supplied uuidv7 (idempotency) */
  id?: string;
  /** @maxItems 20 */
  media_ids?: string[];
  /** @maxItems 100 */
  mentions?: string[];
  reply_to_message_id?: string;
}
