/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GithubCom4H1RZooraInternalDomainAIGradingMode = typeof GithubCom4H1RZooraInternalDomainAIGradingMode[keyof typeof GithubCom4H1RZooraInternalDomainAIGradingMode];


export const GithubCom4H1RZooraInternalDomainAIGradingMode = {
  /** write earned_score (never over a manual grade) */
  AIGradingModeApply: 'apply',
  /** only write suggested_score + rationale */
  AIGradingModeSuggest: 'suggest',
} as const;
