/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainCreateQuestionDTOType } from './githubCom4H1RZooraInternalDomainCreateQuestionDTOType';
import type { GithubCom4H1RZooraInternalDomainNegativeMarkMode } from './githubCom4H1RZooraInternalDomainNegativeMarkMode';
import type { GithubCom4H1RZooraInternalDomainQuestionMetadata } from './githubCom4H1RZooraInternalDomainQuestionMetadata';
import type { GithubCom4H1RZooraInternalDomainQuestionOption } from './githubCom4H1RZooraInternalDomainQuestionOption';

export interface GithubCom4H1RZooraInternalDomainCreateQuestionDTO {
  metadata?: GithubCom4H1RZooraInternalDomainQuestionMetadata[];
  /** @minimum 0 */
  min_seconds?: number;
  model_answer?: string;
  negative_mark_mode?: GithubCom4H1RZooraInternalDomainNegativeMarkMode;
  negative_value?: number;
  options?: GithubCom4H1RZooraInternalDomainQuestionOption[];
  render_as_image?: boolean;
  /** @minLength 1 */
  text: string;
  type: GithubCom4H1RZooraInternalDomainCreateQuestionDTOType;
  wrongs_per_point?: number;
}
