/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainBillingInterval } from './githubCom4H1RZooraInternalDomainBillingInterval';
import type { GithubCom4H1RZooraInternalDomainInvoiceItemKind } from './githubCom4H1RZooraInternalDomainInvoiceItemKind';
import type { GithubCom4H1RZooraInternalDomainPlan } from './githubCom4H1RZooraInternalDomainPlan';

export interface GithubCom4H1RZooraInternalDomainInvoiceItem {
  amount?: number;
  created_at?: string;
  currency?: string;
  description?: string;
  id?: string;
  interval?: GithubCom4H1RZooraInternalDomainBillingInterval;
  invoice_id?: string;
  kind?: GithubCom4H1RZooraInternalDomainInvoiceItemKind;
  period_end?: string;
  period_start?: string;
  plan?: GithubCom4H1RZooraInternalDomainPlan;
  quantity?: number;
  unit_amount?: number;
}
