/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainAdminUpdateOrganizationDTOStatus } from './githubCom4H1RZooraInternalDomainAdminUpdateOrganizationDTOStatus';

export interface GithubCom4H1RZooraInternalDomainAdminUpdateOrganizationDTO {
  description?: string;
  /** @minLength 2 */
  name?: string;
  /**
     * @minLength 2
     * @maxLength 63
     */
  slug?: string;
  status?: GithubCom4H1RZooraInternalDomainAdminUpdateOrganizationDTOStatus;
}
