/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

/**
 * column_id -> value
 */
export type GithubCom4H1RZooraInternalDomainGradebookMatrixRowCells = {[key: string]: string};
