/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export interface GithubCom4H1RZooraInternalDomainOrganizationStats {
  active_count?: number;
  archived_count?: number;
  deleted_organizations?: number;
  suspended_count?: number;
  total_organizations?: number;
  total_users?: number;
  trial_count?: number;
}
