/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainCustomFieldType } from './githubCom4H1RZooraInternalDomainCustomFieldType';

export interface GithubCom4H1RZooraInternalDomainVisibleCustomField {
  field_id?: string;
  field_type?: GithubCom4H1RZooraInternalDomainCustomFieldType;
  label?: string;
  value?: unknown;
}
