/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainProvisionClassConversationDTOType } from './githubCom4H1RZooraInternalDomainProvisionClassConversationDTOType';

export interface GithubCom4H1RZooraInternalDomainProvisionClassConversationDTO {
  /**
     * @minimum 0
     * @maximum 6
     */
  color_index?: number;
  /** @maxLength 255 */
  name?: string;
  type: GithubCom4H1RZooraInternalDomainProvisionClassConversationDTOType;
}
