/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export interface GithubCom4H1RZooraInternalDomainAddTicketMessageDTO {
  /**
     * @minLength 1
     * @maxLength 10000
     */
  body: string;
  /** @maxItems 10 */
  media_ids?: string[];
}
