/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainMessageType } from './githubCom4H1RZooraInternalDomainMessageType';

export interface GithubCom4H1RZooraInternalDomainSendMessageDTO {
  attachments?: number[];
  /**
     * @minLength 1
     * @maxLength 10000
     */
  content: string;
  message_type: GithubCom4H1RZooraInternalDomainMessageType;
  parent_message_id?: string;
}
