/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GithubCom4H1RZooraInternalDomainAdminCreateOrganizationDTOStatus = typeof GithubCom4H1RZooraInternalDomainAdminCreateOrganizationDTOStatus[keyof typeof GithubCom4H1RZooraInternalDomainAdminCreateOrganizationDTOStatus];


export const GithubCom4H1RZooraInternalDomainAdminCreateOrganizationDTOStatus = {
  active: 'active',
  trial: 'trial',
  suspended: 'suspended',
  archived: 'archived',
} as const;
