/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainImageRenderStatus } from './githubCom4H1RZooraInternalDomainImageRenderStatus';
import type { GithubCom4H1RZooraInternalDomainNegativeMarkConfig } from './githubCom4H1RZooraInternalDomainNegativeMarkConfig';
import type { GithubCom4H1RZooraInternalDomainNegativeMarkMode } from './githubCom4H1RZooraInternalDomainNegativeMarkMode';
import type { GithubCom4H1RZooraInternalDomainQuestionBank } from './githubCom4H1RZooraInternalDomainQuestionBank';
import type { GithubCom4H1RZooraInternalDomainQuestionMetadata } from './githubCom4H1RZooraInternalDomainQuestionMetadata';
import type { GithubCom4H1RZooraInternalDomainQuestionOption } from './githubCom4H1RZooraInternalDomainQuestionOption';
import type { GithubCom4H1RZooraInternalDomainQuestionType } from './githubCom4H1RZooraInternalDomainQuestionType';

export interface GithubCom4H1RZooraInternalDomainQuestion {
  bank?: GithubCom4H1RZooraInternalDomainQuestionBank;
  bank_id?: string;
  created_at?: string;
  id?: string;
  /**
     * ImageRenderStatus tracks whether this question's anti-cheat images have
     * been rendered. The render decision lives on the QUIZ (Quiz.RenderAsImage);
     * the rendered images are cached here and reused across every quiz that uses
     * the question. A status other than 'none' also marks the question as
     * participating in rendering, so an edit to its text re-renders the images.
     * A quiz cannot start while any of its questions is not yet 'ready'.
     */
  image_render_status?: GithubCom4H1RZooraInternalDomainImageRenderStatus;
  /**
     * IsMultiSelectFlag is populated only by the "take" endpoint after answer
     * keys are stripped, so the client can still render multi-select choice
     * questions without seeing per-option scores.
     */
  is_multi_select?: boolean;
  metadata?: GithubCom4H1RZooraInternalDomainQuestionMetadata[];
  /**
     * MinSeconds is the teacher-declared minimum expected time to answer this
     * question. 0 = no expectation. Advisory only: answers faster than this are
     * flagged for review, never rejected.
     */
  min_seconds?: number;
  /**
     * ModelAnswer is the teacher's reference answer for descriptive questions.
     * Used only to compute the advisory similarity signal shown during manual
     * grading — never affects the score, never sent to students.
     */
  model_answer?: string;
  /**
     * NegativeConfig is the transient, score-free effective negative-marking
     * config attached by the "take" endpoint so the client can show penalties
     * without leaking the answer key. Never persisted.
     */
  negative_config?: GithubCom4H1RZooraInternalDomainNegativeMarkConfig;
  /** Negative-marking default for this question (Layer 1). choice-only. */
  negative_mark_mode?: GithubCom4H1RZooraInternalDomainNegativeMarkMode;
  negative_value?: number;
  options?: GithubCom4H1RZooraInternalDomainQuestionOption[];
  organization_id?: string;
  /**
     * SystemImageMediaID references the rendered body image. Server-owned; nil
     * until the render task completes.
     */
  system_image_media_id?: string;
  text?: string;
  type?: GithubCom4H1RZooraInternalDomainQuestionType;
  updated_at?: string;
  wrongs_per_point?: number;
}
