/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainFastAnswerFlag } from './githubCom4H1RZooraInternalDomainFastAnswerFlag';

export interface GithubCom4H1RZooraInternalDomainSubmissionAntiCheatReport {
  fast_answers?: GithubCom4H1RZooraInternalDomainFastAnswerFlag[];
  gps_denied?: boolean;
  /**
     * SameLocationUserIDs lists other students in this quiz whose recorded GPS is
     * within SameLocationMeters (both accuracy < SameLocationMaxAccuracy).
     */
  same_location_user_ids?: string[];
  submission_id?: string;
  tab_flagged?: boolean;
  tab_hidden_count?: number;
  tab_hidden_seconds?: number;
  user_id?: string;
}
