/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */

export type GithubCom4H1RZooraInternalDomainParticipantRole = typeof GithubCom4H1RZooraInternalDomainParticipantRole[keyof typeof GithubCom4H1RZooraInternalDomainParticipantRole];


export const GithubCom4H1RZooraInternalDomainParticipantRole = {
  ParticipantRoleHost: 'host',
  ParticipantRolePresenter: 'presenter',
  ParticipantRoleViewer: 'viewer',
} as const;
