/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainCreateTicketDTOType } from './githubCom4H1RZooraInternalDomainCreateTicketDTOType';

export interface GithubCom4H1RZooraInternalDomainCreateTicketDTO {
  /**
     * @minLength 1
     * @maxLength 10000
     */
  body: string;
  class_id: string;
  gradebook_column_id?: string;
  /** @maxItems 10 */
  media_ids?: string[];
  quiz_room_id?: string;
  /**
     * @minLength 2
     * @maxLength 255
     */
  title: string;
  type: GithubCom4H1RZooraInternalDomainCreateTicketDTOType;
}
