/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import type { GithubCom4H1RZooraInternalDomainResponse } from './githubCom4H1RZooraInternalDomainResponse';
import type { PostAuthLogin200Data } from './postAuthLogin200Data';

export type PostAuthLogin200 = GithubCom4H1RZooraInternalDomainResponse & {
  data?: PostAuthLogin200Data;
};
