/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestGetStartedRouteImport } from './routes/_guest/get-started'
import { Route as AuthOrgRouteImport } from './routes/_auth/org'
import { Route as AuthOrgIndexRouteImport } from './routes/_auth/org/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AuthQuizQuizIdRouteImport } from './routes/_auth/quiz/$quizId'
import { Route as AuthOrgWhatsNewRouteImport } from './routes/_auth/org/whats-new'
import { Route as AuthOrgTutorialsRouteImport } from './routes/_auth/org/tutorials'
import { Route as AuthOrgDashboardRouteImport } from './routes/_auth/org/dashboard'
import { Route as AuthOrgCalendarRouteImport } from './routes/_auth/org/calendar'
import { Route as AuthOrgAccountRouteImport } from './routes/_auth/org/account'
import { Route as AuthLiveLiveIdRouteImport } from './routes/_auth/live/$liveId'
import { Route as AdminAdminNotificationsRouteImport } from './routes/_admin/admin/notifications'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin/dashboard'
import { Route as AdminAdminAccountRouteImport } from './routes/_admin/admin/account'
import { Route as AuthOrgConversationsRouteRouteImport } from './routes/_auth/org/conversations/route'
import { Route as AuthOrgUsersIndexRouteImport } from './routes/_auth/org/users/index'
import { Route as AuthOrgTicketsIndexRouteImport } from './routes/_auth/org/tickets/index'
import { Route as AuthOrgSettingsIndexRouteImport } from './routes/_auth/org/settings/index'
import { Route as AuthOrgRolesIndexRouteImport } from './routes/_auth/org/roles/index'
import { Route as AuthOrgPracticesIndexRouteImport } from './routes/_auth/org/practices/index'
import { Route as AuthOrgOnlineClassesIndexRouteImport } from './routes/_auth/org/online-classes/index'
import { Route as AuthOrgNotificationsIndexRouteImport } from './routes/_auth/org/notifications/index'
import { Route as AuthOrgMediasIndexRouteImport } from './routes/_auth/org/medias/index'
import { Route as AuthOrgGradesIndexRouteImport } from './routes/_auth/org/grades/index'
import { Route as AuthOrgFilesIndexRouteImport } from './routes/_auth/org/files/index'
import { Route as AuthOrgExamsIndexRouteImport } from './routes/_auth/org/exams/index'
import { Route as AuthOrgConversationsIndexRouteImport } from './routes/_auth/org/conversations/index'
import { Route as AuthOrgClassesIndexRouteImport } from './routes/_auth/org/classes/index'
import { Route as AuthOrgBillingIndexRouteImport } from './routes/_auth/org/billing/index'
import { Route as AuthOrgAttendanceIndexRouteImport } from './routes/_auth/org/attendance/index'
import { Route as AdminAdminUsersIndexRouteImport } from './routes/_admin/admin/users/index'
import { Route as AdminAdminTutorialsIndexRouteImport } from './routes/_admin/admin/tutorials/index'
import { Route as AdminAdminSessionsIndexRouteImport } from './routes/_admin/admin/sessions/index'
import { Route as AdminAdminRolesIndexRouteImport } from './routes/_admin/admin/roles/index'
import { Route as AdminAdminQuizzesIndexRouteImport } from './routes/_admin/admin/quizzes/index'
import { Route as AdminAdminQuestionsIndexRouteImport } from './routes/_admin/admin/questions/index'
import { Route as AdminAdminPracticesIndexRouteImport } from './routes/_admin/admin/practices/index'
import { Route as AdminAdminPermissionsIndexRouteImport } from './routes/_admin/admin/permissions/index'
import { Route as AdminAdminOrganizationsIndexRouteImport } from './routes/_admin/admin/organizations/index'
import { Route as AdminAdminOfflinesIndexRouteImport } from './routes/_admin/admin/offlines/index'
import { Route as AdminAdminLiveRoomsIndexRouteImport } from './routes/_admin/admin/live-rooms/index'
import { Route as AdminAdminLeadsIndexRouteImport } from './routes/_admin/admin/leads/index'
import { Route as AdminAdminGradebookIndexRouteImport } from './routes/_admin/admin/gradebook/index'
import { Route as AdminAdminCorrectionsIndexRouteImport } from './routes/_admin/admin/corrections/index'
import { Route as AdminAdminClassesIndexRouteImport } from './routes/_admin/admin/classes/index'
import { Route as AdminAdminChangelogIndexRouteImport } from './routes/_admin/admin/changelog/index'
import { Route as AdminAdminAttendanceIndexRouteImport } from './routes/_admin/admin/attendance/index'
import { Route as AuthOrgOfflinesOfflineIdRouteImport } from './routes/_auth/org/offlines/$offlineId'
import { Route as AuthOrgNotificationsSettingsRouteImport } from './routes/_auth/org/notifications/settings'
import { Route as AuthOrgNotificationsSendRouteImport } from './routes/_auth/org/notifications/send'
import { Route as AuthOrgFilesFolderRouteImport } from './routes/_auth/org/files/$folder'
import { Route as AuthOrgConversationsConversationIdRouteImport } from './routes/_auth/org/conversations/$conversationId'
import { Route as AuthOrgClassesClassIdRouteImport } from './routes/_auth/org/classes/$classId'
import { Route as AuthOrgBillingResultRouteImport } from './routes/_auth/org/billing/result'
import { Route as AuthOrgBillingInvoicesRouteImport } from './routes/_auth/org/billing/invoices'
import { Route as AdminAdminTutorialsIdRouteImport } from './routes/_admin/admin/tutorials/$id'
import { Route as AdminAdminChangelogIdRouteImport } from './routes/_admin/admin/changelog/$id'
import { Route as AdminAdminBillingPricesRouteImport } from './routes/_admin/admin/billing/prices'
import { Route as AdminAdminBillingInvoicesIndexRouteImport } from './routes/_admin/admin/billing/invoices/index'
import { Route as AuthOrgClassesClassSessionsClassSessionIdRouteImport } from './routes/_auth/org/classes/class-sessions/$classSessionId'
import { Route as AuthOrgClassesClassIdGradebookRouteImport } from './routes/_auth/org/classes/$classId_.gradebook'
import { Route as AdminAdminClassesClassIdSessionsRouteImport } from './routes/_admin/admin/classes/$classId/sessions'
import { Route as AdminAdminClassesClassIdQuizzesRouteImport } from './routes/_admin/admin/classes/$classId/quizzes'
import { Route as AdminAdminClassesClassIdQuestionsRouteImport } from './routes/_admin/admin/classes/$classId/questions'
import { Route as AdminAdminClassesClassIdPracticesRouteImport } from './routes/_admin/admin/classes/$classId/practices'
import { Route as AdminAdminClassesClassIdOfflinesRouteImport } from './routes/_admin/admin/classes/$classId/offlines'
import { Route as AdminAdminClassesClassIdMembersRouteImport } from './routes/_admin/admin/classes/$classId/members'
import { Route as AdminAdminClassesClassIdLiveRoomsRouteImport } from './routes/_admin/admin/classes/$classId/live-rooms'
import { Route as AdminAdminClassesClassIdGradebookRouteImport } from './routes/_admin/admin/classes/$classId/gradebook'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestGetStartedRoute = GuestGetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => GuestRoute,
} as any)
const AuthOrgRoute = AuthOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrgIndexRoute = AuthOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthQuizQuizIdRoute = AuthQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOrgWhatsNewRoute = AuthOrgWhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgTutorialsRoute = AuthOrgTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgDashboardRoute = AuthOrgDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgCalendarRoute = AuthOrgCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgAccountRoute = AuthOrgAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthLiveLiveIdRoute = AuthLiveLiveIdRouteImport.update({
  id: '/live/$liveId',
  path: '/live/$liveId',
  getParentRoute: () => AuthRoute,
} as any)
const AdminAdminNotificationsRoute = AdminAdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminAccountRoute = AdminAdminAccountRouteImport.update({
  id: '/admin/account',
  path: '/admin/account',
  getParentRoute: () => AdminRoute,
} as any)
const AuthOrgConversationsRouteRoute =
  AuthOrgConversationsRouteRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgUsersIndexRoute = AuthOrgUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgTicketsIndexRoute = AuthOrgTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgSettingsIndexRoute = AuthOrgSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgRolesIndexRoute = AuthOrgRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgPracticesIndexRoute = AuthOrgPracticesIndexRouteImport.update({
  id: '/practices/',
  path: '/practices/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgOnlineClassesIndexRoute =
  AuthOrgOnlineClassesIndexRouteImport.update({
    id: '/online-classes/',
    path: '/online-classes/',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgNotificationsIndexRoute =
  AuthOrgNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgMediasIndexRoute = AuthOrgMediasIndexRouteImport.update({
  id: '/medias/',
  path: '/medias/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgGradesIndexRoute = AuthOrgGradesIndexRouteImport.update({
  id: '/grades/',
  path: '/grades/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgFilesIndexRoute = AuthOrgFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgExamsIndexRoute = AuthOrgExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgConversationsIndexRoute =
  AuthOrgConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthOrgConversationsRouteRoute,
  } as any)
const AuthOrgClassesIndexRoute = AuthOrgClassesIndexRouteImport.update({
  id: '/classes/',
  path: '/classes/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgBillingIndexRoute = AuthOrgBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgAttendanceIndexRoute = AuthOrgAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AdminAdminUsersIndexRoute = AdminAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminTutorialsIndexRoute =
  AdminAdminTutorialsIndexRouteImport.update({
    id: '/admin/tutorials/',
    path: '/admin/tutorials/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminSessionsIndexRoute = AdminAdminSessionsIndexRouteImport.update({
  id: '/admin/sessions/',
  path: '/admin/sessions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRolesIndexRoute = AdminAdminRolesIndexRouteImport.update({
  id: '/admin/roles/',
  path: '/admin/roles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminQuizzesIndexRoute = AdminAdminQuizzesIndexRouteImport.update({
  id: '/admin/quizzes/',
  path: '/admin/quizzes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminQuestionsIndexRoute =
  AdminAdminQuestionsIndexRouteImport.update({
    id: '/admin/questions/',
    path: '/admin/questions/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminPracticesIndexRoute =
  AdminAdminPracticesIndexRouteImport.update({
    id: '/admin/practices/',
    path: '/admin/practices/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminPermissionsIndexRoute =
  AdminAdminPermissionsIndexRouteImport.update({
    id: '/admin/permissions/',
    path: '/admin/permissions/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminOrganizationsIndexRoute =
  AdminAdminOrganizationsIndexRouteImport.update({
    id: '/admin/organizations/',
    path: '/admin/organizations/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminOfflinesIndexRoute = AdminAdminOfflinesIndexRouteImport.update({
  id: '/admin/offlines/',
  path: '/admin/offlines/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLiveRoomsIndexRoute =
  AdminAdminLiveRoomsIndexRouteImport.update({
    id: '/admin/live-rooms/',
    path: '/admin/live-rooms/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminLeadsIndexRoute = AdminAdminLeadsIndexRouteImport.update({
  id: '/admin/leads/',
  path: '/admin/leads/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminGradebookIndexRoute =
  AdminAdminGradebookIndexRouteImport.update({
    id: '/admin/gradebook/',
    path: '/admin/gradebook/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminCorrectionsIndexRoute =
  AdminAdminCorrectionsIndexRouteImport.update({
    id: '/admin/corrections/',
    path: '/admin/corrections/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminClassesIndexRoute = AdminAdminClassesIndexRouteImport.update({
  id: '/admin/classes/',
  path: '/admin/classes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminChangelogIndexRoute =
  AdminAdminChangelogIndexRouteImport.update({
    id: '/admin/changelog/',
    path: '/admin/changelog/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminAttendanceIndexRoute =
  AdminAdminAttendanceIndexRouteImport.update({
    id: '/admin/attendance/',
    path: '/admin/attendance/',
    getParentRoute: () => AdminRoute,
  } as any)
const AuthOrgOfflinesOfflineIdRoute =
  AuthOrgOfflinesOfflineIdRouteImport.update({
    id: '/offlines/$offlineId',
    path: '/offlines/$offlineId',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgNotificationsSettingsRoute =
  AuthOrgNotificationsSettingsRouteImport.update({
    id: '/notifications/settings',
    path: '/notifications/settings',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgNotificationsSendRoute =
  AuthOrgNotificationsSendRouteImport.update({
    id: '/notifications/send',
    path: '/notifications/send',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgFilesFolderRoute = AuthOrgFilesFolderRouteImport.update({
  id: '/files/$folder',
  path: '/files/$folder',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgConversationsConversationIdRoute =
  AuthOrgConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthOrgConversationsRouteRoute,
  } as any)
const AuthOrgClassesClassIdRoute = AuthOrgClassesClassIdRouteImport.update({
  id: '/classes/$classId',
  path: '/classes/$classId',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgBillingResultRoute = AuthOrgBillingResultRouteImport.update({
  id: '/billing/result',
  path: '/billing/result',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AuthOrgBillingInvoicesRoute = AuthOrgBillingInvoicesRouteImport.update({
  id: '/billing/invoices',
  path: '/billing/invoices',
  getParentRoute: () => AuthOrgRoute,
} as any)
const AdminAdminTutorialsIdRoute = AdminAdminTutorialsIdRouteImport.update({
  id: '/admin/tutorials/$id',
  path: '/admin/tutorials/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminChangelogIdRoute = AdminAdminChangelogIdRouteImport.update({
  id: '/admin/changelog/$id',
  path: '/admin/changelog/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBillingPricesRoute = AdminAdminBillingPricesRouteImport.update({
  id: '/admin/billing/prices',
  path: '/admin/billing/prices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminBillingInvoicesIndexRoute =
  AdminAdminBillingInvoicesIndexRouteImport.update({
    id: '/admin/billing/invoices/',
    path: '/admin/billing/invoices/',
    getParentRoute: () => AdminRoute,
  } as any)
const AuthOrgClassesClassSessionsClassSessionIdRoute =
  AuthOrgClassesClassSessionsClassSessionIdRouteImport.update({
    id: '/classes/class-sessions/$classSessionId',
    path: '/classes/class-sessions/$classSessionId',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AuthOrgClassesClassIdGradebookRoute =
  AuthOrgClassesClassIdGradebookRouteImport.update({
    id: '/classes/$classId_/gradebook',
    path: '/classes/$classId/gradebook',
    getParentRoute: () => AuthOrgRoute,
  } as any)
const AdminAdminClassesClassIdSessionsRoute =
  AdminAdminClassesClassIdSessionsRouteImport.update({
    id: '/admin/classes/$classId/sessions',
    path: '/admin/classes/$classId/sessions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminClassesClassIdQuizzesRoute =
  AdminAdminClassesClassIdQuizzesRouteImport.update({
    id: '/admin/classes/$classId/quizzes',
    path: '/admin/classes/$classId/quizzes',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminClassesClassIdQuestionsRoute =
  AdminAdminClassesClassIdQuestionsRouteImport.update({
    id: '/admin/classes/$classId/questions',
    path: '/admin/classes/$classId/questions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminClassesClassIdPracticesRoute =
  AdminAdminClassesClassIdPracticesRouteImport.update({
    id: '/admin/classes/$classId/practices',
    path: '/admin/classes/$classId/practices',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminClassesClassIdOfflinesRoute =
  AdminAdminClassesClassIdOfflinesRouteImport.update({
    id: '/admin/classes/$classId/offlines',
    path: '/admin/classes/$classId/offlines',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminClassesClassIdMembersRoute =
  AdminAdminClassesClassIdMembersRouteImport.update({
    id: '/admin/classes/$classId/members',
    path: '/admin/classes/$classId/members',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminClassesClassIdLiveRoomsRoute =
  AdminAdminClassesClassIdLiveRoomsRouteImport.update({
    id: '/admin/classes/$classId/live-rooms',
    path: '/admin/classes/$classId/live-rooms',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAdminClassesClassIdGradebookRoute =
  AdminAdminClassesClassIdGradebookRouteImport.update({
    id: '/admin/classes/$classId/gradebook',
    path: '/admin/classes/$classId/gradebook',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/org': typeof AuthOrgRouteWithChildren
  '/get-started': typeof GuestGetStartedRoute
  '/login': typeof GuestLoginRoute
  '/org/conversations': typeof AuthOrgConversationsRouteRouteWithChildren
  '/admin/account': typeof AdminAdminAccountRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/live/$liveId': typeof AuthLiveLiveIdRoute
  '/org/account': typeof AuthOrgAccountRoute
  '/org/calendar': typeof AuthOrgCalendarRoute
  '/org/dashboard': typeof AuthOrgDashboardRoute
  '/org/tutorials': typeof AuthOrgTutorialsRoute
  '/org/whats-new': typeof AuthOrgWhatsNewRoute
  '/quiz/$quizId': typeof AuthQuizQuizIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/org/': typeof AuthOrgIndexRoute
  '/admin/billing/prices': typeof AdminAdminBillingPricesRoute
  '/admin/changelog/$id': typeof AdminAdminChangelogIdRoute
  '/admin/tutorials/$id': typeof AdminAdminTutorialsIdRoute
  '/org/billing/invoices': typeof AuthOrgBillingInvoicesRoute
  '/org/billing/result': typeof AuthOrgBillingResultRoute
  '/org/classes/$classId': typeof AuthOrgClassesClassIdRoute
  '/org/conversations/$conversationId': typeof AuthOrgConversationsConversationIdRoute
  '/org/files/$folder': typeof AuthOrgFilesFolderRoute
  '/org/notifications/send': typeof AuthOrgNotificationsSendRoute
  '/org/notifications/settings': typeof AuthOrgNotificationsSettingsRoute
  '/org/offlines/$offlineId': typeof AuthOrgOfflinesOfflineIdRoute
  '/admin/attendance/': typeof AdminAdminAttendanceIndexRoute
  '/admin/changelog/': typeof AdminAdminChangelogIndexRoute
  '/admin/classes/': typeof AdminAdminClassesIndexRoute
  '/admin/corrections/': typeof AdminAdminCorrectionsIndexRoute
  '/admin/gradebook/': typeof AdminAdminGradebookIndexRoute
  '/admin/leads/': typeof AdminAdminLeadsIndexRoute
  '/admin/live-rooms/': typeof AdminAdminLiveRoomsIndexRoute
  '/admin/offlines/': typeof AdminAdminOfflinesIndexRoute
  '/admin/organizations/': typeof AdminAdminOrganizationsIndexRoute
  '/admin/permissions/': typeof AdminAdminPermissionsIndexRoute
  '/admin/practices/': typeof AdminAdminPracticesIndexRoute
  '/admin/questions/': typeof AdminAdminQuestionsIndexRoute
  '/admin/quizzes/': typeof AdminAdminQuizzesIndexRoute
  '/admin/roles/': typeof AdminAdminRolesIndexRoute
  '/admin/sessions/': typeof AdminAdminSessionsIndexRoute
  '/admin/tutorials/': typeof AdminAdminTutorialsIndexRoute
  '/admin/users/': typeof AdminAdminUsersIndexRoute
  '/org/attendance/': typeof AuthOrgAttendanceIndexRoute
  '/org/billing/': typeof AuthOrgBillingIndexRoute
  '/org/classes/': typeof AuthOrgClassesIndexRoute
  '/org/conversations/': typeof AuthOrgConversationsIndexRoute
  '/org/exams/': typeof AuthOrgExamsIndexRoute
  '/org/files/': typeof AuthOrgFilesIndexRoute
  '/org/grades/': typeof AuthOrgGradesIndexRoute
  '/org/medias/': typeof AuthOrgMediasIndexRoute
  '/org/notifications/': typeof AuthOrgNotificationsIndexRoute
  '/org/online-classes/': typeof AuthOrgOnlineClassesIndexRoute
  '/org/practices/': typeof AuthOrgPracticesIndexRoute
  '/org/roles/': typeof AuthOrgRolesIndexRoute
  '/org/settings/': typeof AuthOrgSettingsIndexRoute
  '/org/tickets/': typeof AuthOrgTicketsIndexRoute
  '/org/users/': typeof AuthOrgUsersIndexRoute
  '/admin/classes/$classId/gradebook': typeof AdminAdminClassesClassIdGradebookRoute
  '/admin/classes/$classId/live-rooms': typeof AdminAdminClassesClassIdLiveRoomsRoute
  '/admin/classes/$classId/members': typeof AdminAdminClassesClassIdMembersRoute
  '/admin/classes/$classId/offlines': typeof AdminAdminClassesClassIdOfflinesRoute
  '/admin/classes/$classId/practices': typeof AdminAdminClassesClassIdPracticesRoute
  '/admin/classes/$classId/questions': typeof AdminAdminClassesClassIdQuestionsRoute
  '/admin/classes/$classId/quizzes': typeof AdminAdminClassesClassIdQuizzesRoute
  '/admin/classes/$classId/sessions': typeof AdminAdminClassesClassIdSessionsRoute
  '/org/classes/$classId/gradebook': typeof AuthOrgClassesClassIdGradebookRoute
  '/org/classes/class-sessions/$classSessionId': typeof AuthOrgClassesClassSessionsClassSessionIdRoute
  '/admin/billing/invoices/': typeof AdminAdminBillingInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-started': typeof GuestGetStartedRoute
  '/login': typeof GuestLoginRoute
  '/admin/account': typeof AdminAdminAccountRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/live/$liveId': typeof AuthLiveLiveIdRoute
  '/org/account': typeof AuthOrgAccountRoute
  '/org/calendar': typeof AuthOrgCalendarRoute
  '/org/dashboard': typeof AuthOrgDashboardRoute
  '/org/tutorials': typeof AuthOrgTutorialsRoute
  '/org/whats-new': typeof AuthOrgWhatsNewRoute
  '/quiz/$quizId': typeof AuthQuizQuizIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/org': typeof AuthOrgIndexRoute
  '/admin/billing/prices': typeof AdminAdminBillingPricesRoute
  '/admin/changelog/$id': typeof AdminAdminChangelogIdRoute
  '/admin/tutorials/$id': typeof AdminAdminTutorialsIdRoute
  '/org/billing/invoices': typeof AuthOrgBillingInvoicesRoute
  '/org/billing/result': typeof AuthOrgBillingResultRoute
  '/org/classes/$classId': typeof AuthOrgClassesClassIdRoute
  '/org/conversations/$conversationId': typeof AuthOrgConversationsConversationIdRoute
  '/org/files/$folder': typeof AuthOrgFilesFolderRoute
  '/org/notifications/send': typeof AuthOrgNotificationsSendRoute
  '/org/notifications/settings': typeof AuthOrgNotificationsSettingsRoute
  '/org/offlines/$offlineId': typeof AuthOrgOfflinesOfflineIdRoute
  '/admin/attendance': typeof AdminAdminAttendanceIndexRoute
  '/admin/changelog': typeof AdminAdminChangelogIndexRoute
  '/admin/classes': typeof AdminAdminClassesIndexRoute
  '/admin/corrections': typeof AdminAdminCorrectionsIndexRoute
  '/admin/gradebook': typeof AdminAdminGradebookIndexRoute
  '/admin/leads': typeof AdminAdminLeadsIndexRoute
  '/admin/live-rooms': typeof AdminAdminLiveRoomsIndexRoute
  '/admin/offlines': typeof AdminAdminOfflinesIndexRoute
  '/admin/organizations': typeof AdminAdminOrganizationsIndexRoute
  '/admin/permissions': typeof AdminAdminPermissionsIndexRoute
  '/admin/practices': typeof AdminAdminPracticesIndexRoute
  '/admin/questions': typeof AdminAdminQuestionsIndexRoute
  '/admin/quizzes': typeof AdminAdminQuizzesIndexRoute
  '/admin/roles': typeof AdminAdminRolesIndexRoute
  '/admin/sessions': typeof AdminAdminSessionsIndexRoute
  '/admin/tutorials': typeof AdminAdminTutorialsIndexRoute
  '/admin/users': typeof AdminAdminUsersIndexRoute
  '/org/attendance': typeof AuthOrgAttendanceIndexRoute
  '/org/billing': typeof AuthOrgBillingIndexRoute
  '/org/classes': typeof AuthOrgClassesIndexRoute
  '/org/conversations': typeof AuthOrgConversationsIndexRoute
  '/org/exams': typeof AuthOrgExamsIndexRoute
  '/org/files': typeof AuthOrgFilesIndexRoute
  '/org/grades': typeof AuthOrgGradesIndexRoute
  '/org/medias': typeof AuthOrgMediasIndexRoute
  '/org/notifications': typeof AuthOrgNotificationsIndexRoute
  '/org/online-classes': typeof AuthOrgOnlineClassesIndexRoute
  '/org/practices': typeof AuthOrgPracticesIndexRoute
  '/org/roles': typeof AuthOrgRolesIndexRoute
  '/org/settings': typeof AuthOrgSettingsIndexRoute
  '/org/tickets': typeof AuthOrgTicketsIndexRoute
  '/org/users': typeof AuthOrgUsersIndexRoute
  '/admin/classes/$classId/gradebook': typeof AdminAdminClassesClassIdGradebookRoute
  '/admin/classes/$classId/live-rooms': typeof AdminAdminClassesClassIdLiveRoomsRoute
  '/admin/classes/$classId/members': typeof AdminAdminClassesClassIdMembersRoute
  '/admin/classes/$classId/offlines': typeof AdminAdminClassesClassIdOfflinesRoute
  '/admin/classes/$classId/practices': typeof AdminAdminClassesClassIdPracticesRoute
  '/admin/classes/$classId/questions': typeof AdminAdminClassesClassIdQuestionsRoute
  '/admin/classes/$classId/quizzes': typeof AdminAdminClassesClassIdQuizzesRoute
  '/admin/classes/$classId/sessions': typeof AdminAdminClassesClassIdSessionsRoute
  '/org/classes/$classId/gradebook': typeof AuthOrgClassesClassIdGradebookRoute
  '/org/classes/class-sessions/$classSessionId': typeof AuthOrgClassesClassSessionsClassSessionIdRoute
  '/admin/billing/invoices': typeof AdminAdminBillingInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_auth/org': typeof AuthOrgRouteWithChildren
  '/_guest/get-started': typeof GuestGetStartedRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_auth/org/conversations': typeof AuthOrgConversationsRouteRouteWithChildren
  '/_admin/admin/account': typeof AdminAdminAccountRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/notifications': typeof AdminAdminNotificationsRoute
  '/_auth/live/$liveId': typeof AuthLiveLiveIdRoute
  '/_auth/org/account': typeof AuthOrgAccountRoute
  '/_auth/org/calendar': typeof AuthOrgCalendarRoute
  '/_auth/org/dashboard': typeof AuthOrgDashboardRoute
  '/_auth/org/tutorials': typeof AuthOrgTutorialsRoute
  '/_auth/org/whats-new': typeof AuthOrgWhatsNewRoute
  '/_auth/quiz/$quizId': typeof AuthQuizQuizIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_auth/org/': typeof AuthOrgIndexRoute
  '/_admin/admin/billing/prices': typeof AdminAdminBillingPricesRoute
  '/_admin/admin/changelog/$id': typeof AdminAdminChangelogIdRoute
  '/_admin/admin/tutorials/$id': typeof AdminAdminTutorialsIdRoute
  '/_auth/org/billing/invoices': typeof AuthOrgBillingInvoicesRoute
  '/_auth/org/billing/result': typeof AuthOrgBillingResultRoute
  '/_auth/org/classes/$classId': typeof AuthOrgClassesClassIdRoute
  '/_auth/org/conversations/$conversationId': typeof AuthOrgConversationsConversationIdRoute
  '/_auth/org/files/$folder': typeof AuthOrgFilesFolderRoute
  '/_auth/org/notifications/send': typeof AuthOrgNotificationsSendRoute
  '/_auth/org/notifications/settings': typeof AuthOrgNotificationsSettingsRoute
  '/_auth/org/offlines/$offlineId': typeof AuthOrgOfflinesOfflineIdRoute
  '/_admin/admin/attendance/': typeof AdminAdminAttendanceIndexRoute
  '/_admin/admin/changelog/': typeof AdminAdminChangelogIndexRoute
  '/_admin/admin/classes/': typeof AdminAdminClassesIndexRoute
  '/_admin/admin/corrections/': typeof AdminAdminCorrectionsIndexRoute
  '/_admin/admin/gradebook/': typeof AdminAdminGradebookIndexRoute
  '/_admin/admin/leads/': typeof AdminAdminLeadsIndexRoute
  '/_admin/admin/live-rooms/': typeof AdminAdminLiveRoomsIndexRoute
  '/_admin/admin/offlines/': typeof AdminAdminOfflinesIndexRoute
  '/_admin/admin/organizations/': typeof AdminAdminOrganizationsIndexRoute
  '/_admin/admin/permissions/': typeof AdminAdminPermissionsIndexRoute
  '/_admin/admin/practices/': typeof AdminAdminPracticesIndexRoute
  '/_admin/admin/questions/': typeof AdminAdminQuestionsIndexRoute
  '/_admin/admin/quizzes/': typeof AdminAdminQuizzesIndexRoute
  '/_admin/admin/roles/': typeof AdminAdminRolesIndexRoute
  '/_admin/admin/sessions/': typeof AdminAdminSessionsIndexRoute
  '/_admin/admin/tutorials/': typeof AdminAdminTutorialsIndexRoute
  '/_admin/admin/users/': typeof AdminAdminUsersIndexRoute
  '/_auth/org/attendance/': typeof AuthOrgAttendanceIndexRoute
  '/_auth/org/billing/': typeof AuthOrgBillingIndexRoute
  '/_auth/org/classes/': typeof AuthOrgClassesIndexRoute
  '/_auth/org/conversations/': typeof AuthOrgConversationsIndexRoute
  '/_auth/org/exams/': typeof AuthOrgExamsIndexRoute
  '/_auth/org/files/': typeof AuthOrgFilesIndexRoute
  '/_auth/org/grades/': typeof AuthOrgGradesIndexRoute
  '/_auth/org/medias/': typeof AuthOrgMediasIndexRoute
  '/_auth/org/notifications/': typeof AuthOrgNotificationsIndexRoute
  '/_auth/org/online-classes/': typeof AuthOrgOnlineClassesIndexRoute
  '/_auth/org/practices/': typeof AuthOrgPracticesIndexRoute
  '/_auth/org/roles/': typeof AuthOrgRolesIndexRoute
  '/_auth/org/settings/': typeof AuthOrgSettingsIndexRoute
  '/_auth/org/tickets/': typeof AuthOrgTicketsIndexRoute
  '/_auth/org/users/': typeof AuthOrgUsersIndexRoute
  '/_admin/admin/classes/$classId/gradebook': typeof AdminAdminClassesClassIdGradebookRoute
  '/_admin/admin/classes/$classId/live-rooms': typeof AdminAdminClassesClassIdLiveRoomsRoute
  '/_admin/admin/classes/$classId/members': typeof AdminAdminClassesClassIdMembersRoute
  '/_admin/admin/classes/$classId/offlines': typeof AdminAdminClassesClassIdOfflinesRoute
  '/_admin/admin/classes/$classId/practices': typeof AdminAdminClassesClassIdPracticesRoute
  '/_admin/admin/classes/$classId/questions': typeof AdminAdminClassesClassIdQuestionsRoute
  '/_admin/admin/classes/$classId/quizzes': typeof AdminAdminClassesClassIdQuizzesRoute
  '/_admin/admin/classes/$classId/sessions': typeof AdminAdminClassesClassIdSessionsRoute
  '/_auth/org/classes/$classId_/gradebook': typeof AuthOrgClassesClassIdGradebookRoute
  '/_auth/org/classes/class-sessions/$classSessionId': typeof AuthOrgClassesClassSessionsClassSessionIdRoute
  '/_admin/admin/billing/invoices/': typeof AdminAdminBillingInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/org'
    | '/get-started'
    | '/login'
    | '/org/conversations'
    | '/admin/account'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/live/$liveId'
    | '/org/account'
    | '/org/calendar'
    | '/org/dashboard'
    | '/org/tutorials'
    | '/org/whats-new'
    | '/quiz/$quizId'
    | '/admin/'
    | '/org/'
    | '/admin/billing/prices'
    | '/admin/changelog/$id'
    | '/admin/tutorials/$id'
    | '/org/billing/invoices'
    | '/org/billing/result'
    | '/org/classes/$classId'
    | '/org/conversations/$conversationId'
    | '/org/files/$folder'
    | '/org/notifications/send'
    | '/org/notifications/settings'
    | '/org/offlines/$offlineId'
    | '/admin/attendance/'
    | '/admin/changelog/'
    | '/admin/classes/'
    | '/admin/corrections/'
    | '/admin/gradebook/'
    | '/admin/leads/'
    | '/admin/live-rooms/'
    | '/admin/offlines/'
    | '/admin/organizations/'
    | '/admin/permissions/'
    | '/admin/practices/'
    | '/admin/questions/'
    | '/admin/quizzes/'
    | '/admin/roles/'
    | '/admin/sessions/'
    | '/admin/tutorials/'
    | '/admin/users/'
    | '/org/attendance/'
    | '/org/billing/'
    | '/org/classes/'
    | '/org/conversations/'
    | '/org/exams/'
    | '/org/files/'
    | '/org/grades/'
    | '/org/medias/'
    | '/org/notifications/'
    | '/org/online-classes/'
    | '/org/practices/'
    | '/org/roles/'
    | '/org/settings/'
    | '/org/tickets/'
    | '/org/users/'
    | '/admin/classes/$classId/gradebook'
    | '/admin/classes/$classId/live-rooms'
    | '/admin/classes/$classId/members'
    | '/admin/classes/$classId/offlines'
    | '/admin/classes/$classId/practices'
    | '/admin/classes/$classId/questions'
    | '/admin/classes/$classId/quizzes'
    | '/admin/classes/$classId/sessions'
    | '/org/classes/$classId/gradebook'
    | '/org/classes/class-sessions/$classSessionId'
    | '/admin/billing/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-started'
    | '/login'
    | '/admin/account'
    | '/admin/dashboard'
    | '/admin/notifications'
    | '/live/$liveId'
    | '/org/account'
    | '/org/calendar'
    | '/org/dashboard'
    | '/org/tutorials'
    | '/org/whats-new'
    | '/quiz/$quizId'
    | '/admin'
    | '/org'
    | '/admin/billing/prices'
    | '/admin/changelog/$id'
    | '/admin/tutorials/$id'
    | '/org/billing/invoices'
    | '/org/billing/result'
    | '/org/classes/$classId'
    | '/org/conversations/$conversationId'
    | '/org/files/$folder'
    | '/org/notifications/send'
    | '/org/notifications/settings'
    | '/org/offlines/$offlineId'
    | '/admin/attendance'
    | '/admin/changelog'
    | '/admin/classes'
    | '/admin/corrections'
    | '/admin/gradebook'
    | '/admin/leads'
    | '/admin/live-rooms'
    | '/admin/offlines'
    | '/admin/organizations'
    | '/admin/permissions'
    | '/admin/practices'
    | '/admin/questions'
    | '/admin/quizzes'
    | '/admin/roles'
    | '/admin/sessions'
    | '/admin/tutorials'
    | '/admin/users'
    | '/org/attendance'
    | '/org/billing'
    | '/org/classes'
    | '/org/conversations'
    | '/org/exams'
    | '/org/files'
    | '/org/grades'
    | '/org/medias'
    | '/org/notifications'
    | '/org/online-classes'
    | '/org/practices'
    | '/org/roles'
    | '/org/settings'
    | '/org/tickets'
    | '/org/users'
    | '/admin/classes/$classId/gradebook'
    | '/admin/classes/$classId/live-rooms'
    | '/admin/classes/$classId/members'
    | '/admin/classes/$classId/offlines'
    | '/admin/classes/$classId/practices'
    | '/admin/classes/$classId/questions'
    | '/admin/classes/$classId/quizzes'
    | '/admin/classes/$classId/sessions'
    | '/org/classes/$classId/gradebook'
    | '/org/classes/class-sessions/$classSessionId'
    | '/admin/billing/invoices'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_guest'
    | '/_auth/org'
    | '/_guest/get-started'
    | '/_guest/login'
    | '/_auth/org/conversations'
    | '/_admin/admin/account'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/notifications'
    | '/_auth/live/$liveId'
    | '/_auth/org/account'
    | '/_auth/org/calendar'
    | '/_auth/org/dashboard'
    | '/_auth/org/tutorials'
    | '/_auth/org/whats-new'
    | '/_auth/quiz/$quizId'
    | '/_admin/admin/'
    | '/_auth/org/'
    | '/_admin/admin/billing/prices'
    | '/_admin/admin/changelog/$id'
    | '/_admin/admin/tutorials/$id'
    | '/_auth/org/billing/invoices'
    | '/_auth/org/billing/result'
    | '/_auth/org/classes/$classId'
    | '/_auth/org/conversations/$conversationId'
    | '/_auth/org/files/$folder'
    | '/_auth/org/notifications/send'
    | '/_auth/org/notifications/settings'
    | '/_auth/org/offlines/$offlineId'
    | '/_admin/admin/attendance/'
    | '/_admin/admin/changelog/'
    | '/_admin/admin/classes/'
    | '/_admin/admin/corrections/'
    | '/_admin/admin/gradebook/'
    | '/_admin/admin/leads/'
    | '/_admin/admin/live-rooms/'
    | '/_admin/admin/offlines/'
    | '/_admin/admin/organizations/'
    | '/_admin/admin/permissions/'
    | '/_admin/admin/practices/'
    | '/_admin/admin/questions/'
    | '/_admin/admin/quizzes/'
    | '/_admin/admin/roles/'
    | '/_admin/admin/sessions/'
    | '/_admin/admin/tutorials/'
    | '/_admin/admin/users/'
    | '/_auth/org/attendance/'
    | '/_auth/org/billing/'
    | '/_auth/org/classes/'
    | '/_auth/org/conversations/'
    | '/_auth/org/exams/'
    | '/_auth/org/files/'
    | '/_auth/org/grades/'
    | '/_auth/org/medias/'
    | '/_auth/org/notifications/'
    | '/_auth/org/online-classes/'
    | '/_auth/org/practices/'
    | '/_auth/org/roles/'
    | '/_auth/org/settings/'
    | '/_auth/org/tickets/'
    | '/_auth/org/users/'
    | '/_admin/admin/classes/$classId/gradebook'
    | '/_admin/admin/classes/$classId/live-rooms'
    | '/_admin/admin/classes/$classId/members'
    | '/_admin/admin/classes/$classId/offlines'
    | '/_admin/admin/classes/$classId/practices'
    | '/_admin/admin/classes/$classId/questions'
    | '/_admin/admin/classes/$classId/quizzes'
    | '/_admin/admin/classes/$classId/sessions'
    | '/_auth/org/classes/$classId_/gradebook'
    | '/_auth/org/classes/class-sessions/$classSessionId'
    | '/_admin/admin/billing/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/get-started': {
      id: '/_guest/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GuestGetStartedRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_auth/org': {
      id: '/_auth/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AuthOrgRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/org/': {
      id: '/_auth/org/'
      path: '/'
      fullPath: '/org/'
      preLoaderRoute: typeof AuthOrgIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/quiz/$quizId': {
      id: '/_auth/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof AuthQuizQuizIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/org/whats-new': {
      id: '/_auth/org/whats-new'
      path: '/whats-new'
      fullPath: '/org/whats-new'
      preLoaderRoute: typeof AuthOrgWhatsNewRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/tutorials': {
      id: '/_auth/org/tutorials'
      path: '/tutorials'
      fullPath: '/org/tutorials'
      preLoaderRoute: typeof AuthOrgTutorialsRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/dashboard': {
      id: '/_auth/org/dashboard'
      path: '/dashboard'
      fullPath: '/org/dashboard'
      preLoaderRoute: typeof AuthOrgDashboardRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/calendar': {
      id: '/_auth/org/calendar'
      path: '/calendar'
      fullPath: '/org/calendar'
      preLoaderRoute: typeof AuthOrgCalendarRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/account': {
      id: '/_auth/org/account'
      path: '/account'
      fullPath: '/org/account'
      preLoaderRoute: typeof AuthOrgAccountRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/live/$liveId': {
      id: '/_auth/live/$liveId'
      path: '/live/$liveId'
      fullPath: '/live/$liveId'
      preLoaderRoute: typeof AuthLiveLiveIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/admin/notifications': {
      id: '/_admin/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminAdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/account': {
      id: '/_admin/admin/account'
      path: '/admin/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/org/conversations': {
      id: '/_auth/org/conversations'
      path: '/conversations'
      fullPath: '/org/conversations'
      preLoaderRoute: typeof AuthOrgConversationsRouteRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/users/': {
      id: '/_auth/org/users/'
      path: '/users'
      fullPath: '/org/users/'
      preLoaderRoute: typeof AuthOrgUsersIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/tickets/': {
      id: '/_auth/org/tickets/'
      path: '/tickets'
      fullPath: '/org/tickets/'
      preLoaderRoute: typeof AuthOrgTicketsIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/settings/': {
      id: '/_auth/org/settings/'
      path: '/settings'
      fullPath: '/org/settings/'
      preLoaderRoute: typeof AuthOrgSettingsIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/roles/': {
      id: '/_auth/org/roles/'
      path: '/roles'
      fullPath: '/org/roles/'
      preLoaderRoute: typeof AuthOrgRolesIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/practices/': {
      id: '/_auth/org/practices/'
      path: '/practices'
      fullPath: '/org/practices/'
      preLoaderRoute: typeof AuthOrgPracticesIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/online-classes/': {
      id: '/_auth/org/online-classes/'
      path: '/online-classes'
      fullPath: '/org/online-classes/'
      preLoaderRoute: typeof AuthOrgOnlineClassesIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/notifications/': {
      id: '/_auth/org/notifications/'
      path: '/notifications'
      fullPath: '/org/notifications/'
      preLoaderRoute: typeof AuthOrgNotificationsIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/medias/': {
      id: '/_auth/org/medias/'
      path: '/medias'
      fullPath: '/org/medias/'
      preLoaderRoute: typeof AuthOrgMediasIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/grades/': {
      id: '/_auth/org/grades/'
      path: '/grades'
      fullPath: '/org/grades/'
      preLoaderRoute: typeof AuthOrgGradesIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/files/': {
      id: '/_auth/org/files/'
      path: '/files'
      fullPath: '/org/files/'
      preLoaderRoute: typeof AuthOrgFilesIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/exams/': {
      id: '/_auth/org/exams/'
      path: '/exams'
      fullPath: '/org/exams/'
      preLoaderRoute: typeof AuthOrgExamsIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/conversations/': {
      id: '/_auth/org/conversations/'
      path: '/'
      fullPath: '/org/conversations/'
      preLoaderRoute: typeof AuthOrgConversationsIndexRouteImport
      parentRoute: typeof AuthOrgConversationsRouteRoute
    }
    '/_auth/org/classes/': {
      id: '/_auth/org/classes/'
      path: '/classes'
      fullPath: '/org/classes/'
      preLoaderRoute: typeof AuthOrgClassesIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/billing/': {
      id: '/_auth/org/billing/'
      path: '/billing'
      fullPath: '/org/billing/'
      preLoaderRoute: typeof AuthOrgBillingIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/attendance/': {
      id: '/_auth/org/attendance/'
      path: '/attendance'
      fullPath: '/org/attendance/'
      preLoaderRoute: typeof AuthOrgAttendanceIndexRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_admin/admin/users/': {
      id: '/_admin/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminAdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/tutorials/': {
      id: '/_admin/admin/tutorials/'
      path: '/admin/tutorials'
      fullPath: '/admin/tutorials/'
      preLoaderRoute: typeof AdminAdminTutorialsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/sessions/': {
      id: '/_admin/admin/sessions/'
      path: '/admin/sessions'
      fullPath: '/admin/sessions/'
      preLoaderRoute: typeof AdminAdminSessionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/roles/': {
      id: '/_admin/admin/roles/'
      path: '/admin/roles'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AdminAdminRolesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/quizzes/': {
      id: '/_admin/admin/quizzes/'
      path: '/admin/quizzes'
      fullPath: '/admin/quizzes/'
      preLoaderRoute: typeof AdminAdminQuizzesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/questions/': {
      id: '/_admin/admin/questions/'
      path: '/admin/questions'
      fullPath: '/admin/questions/'
      preLoaderRoute: typeof AdminAdminQuestionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/practices/': {
      id: '/_admin/admin/practices/'
      path: '/admin/practices'
      fullPath: '/admin/practices/'
      preLoaderRoute: typeof AdminAdminPracticesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/permissions/': {
      id: '/_admin/admin/permissions/'
      path: '/admin/permissions'
      fullPath: '/admin/permissions/'
      preLoaderRoute: typeof AdminAdminPermissionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/organizations/': {
      id: '/_admin/admin/organizations/'
      path: '/admin/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminAdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/offlines/': {
      id: '/_admin/admin/offlines/'
      path: '/admin/offlines'
      fullPath: '/admin/offlines/'
      preLoaderRoute: typeof AdminAdminOfflinesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/live-rooms/': {
      id: '/_admin/admin/live-rooms/'
      path: '/admin/live-rooms'
      fullPath: '/admin/live-rooms/'
      preLoaderRoute: typeof AdminAdminLiveRoomsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/leads/': {
      id: '/_admin/admin/leads/'
      path: '/admin/leads'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AdminAdminLeadsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/gradebook/': {
      id: '/_admin/admin/gradebook/'
      path: '/admin/gradebook'
      fullPath: '/admin/gradebook/'
      preLoaderRoute: typeof AdminAdminGradebookIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/corrections/': {
      id: '/_admin/admin/corrections/'
      path: '/admin/corrections'
      fullPath: '/admin/corrections/'
      preLoaderRoute: typeof AdminAdminCorrectionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/classes/': {
      id: '/_admin/admin/classes/'
      path: '/admin/classes'
      fullPath: '/admin/classes/'
      preLoaderRoute: typeof AdminAdminClassesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/changelog/': {
      id: '/_admin/admin/changelog/'
      path: '/admin/changelog'
      fullPath: '/admin/changelog/'
      preLoaderRoute: typeof AdminAdminChangelogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/attendance/': {
      id: '/_admin/admin/attendance/'
      path: '/admin/attendance'
      fullPath: '/admin/attendance/'
      preLoaderRoute: typeof AdminAdminAttendanceIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/org/offlines/$offlineId': {
      id: '/_auth/org/offlines/$offlineId'
      path: '/offlines/$offlineId'
      fullPath: '/org/offlines/$offlineId'
      preLoaderRoute: typeof AuthOrgOfflinesOfflineIdRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/notifications/settings': {
      id: '/_auth/org/notifications/settings'
      path: '/notifications/settings'
      fullPath: '/org/notifications/settings'
      preLoaderRoute: typeof AuthOrgNotificationsSettingsRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/notifications/send': {
      id: '/_auth/org/notifications/send'
      path: '/notifications/send'
      fullPath: '/org/notifications/send'
      preLoaderRoute: typeof AuthOrgNotificationsSendRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/files/$folder': {
      id: '/_auth/org/files/$folder'
      path: '/files/$folder'
      fullPath: '/org/files/$folder'
      preLoaderRoute: typeof AuthOrgFilesFolderRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/conversations/$conversationId': {
      id: '/_auth/org/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/org/conversations/$conversationId'
      preLoaderRoute: typeof AuthOrgConversationsConversationIdRouteImport
      parentRoute: typeof AuthOrgConversationsRouteRoute
    }
    '/_auth/org/classes/$classId': {
      id: '/_auth/org/classes/$classId'
      path: '/classes/$classId'
      fullPath: '/org/classes/$classId'
      preLoaderRoute: typeof AuthOrgClassesClassIdRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/billing/result': {
      id: '/_auth/org/billing/result'
      path: '/billing/result'
      fullPath: '/org/billing/result'
      preLoaderRoute: typeof AuthOrgBillingResultRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/billing/invoices': {
      id: '/_auth/org/billing/invoices'
      path: '/billing/invoices'
      fullPath: '/org/billing/invoices'
      preLoaderRoute: typeof AuthOrgBillingInvoicesRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_admin/admin/tutorials/$id': {
      id: '/_admin/admin/tutorials/$id'
      path: '/admin/tutorials/$id'
      fullPath: '/admin/tutorials/$id'
      preLoaderRoute: typeof AdminAdminTutorialsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/changelog/$id': {
      id: '/_admin/admin/changelog/$id'
      path: '/admin/changelog/$id'
      fullPath: '/admin/changelog/$id'
      preLoaderRoute: typeof AdminAdminChangelogIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/billing/prices': {
      id: '/_admin/admin/billing/prices'
      path: '/admin/billing/prices'
      fullPath: '/admin/billing/prices'
      preLoaderRoute: typeof AdminAdminBillingPricesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/billing/invoices/': {
      id: '/_admin/admin/billing/invoices/'
      path: '/admin/billing/invoices'
      fullPath: '/admin/billing/invoices/'
      preLoaderRoute: typeof AdminAdminBillingInvoicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/org/classes/class-sessions/$classSessionId': {
      id: '/_auth/org/classes/class-sessions/$classSessionId'
      path: '/classes/class-sessions/$classSessionId'
      fullPath: '/org/classes/class-sessions/$classSessionId'
      preLoaderRoute: typeof AuthOrgClassesClassSessionsClassSessionIdRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_auth/org/classes/$classId_/gradebook': {
      id: '/_auth/org/classes/$classId_/gradebook'
      path: '/classes/$classId/gradebook'
      fullPath: '/org/classes/$classId/gradebook'
      preLoaderRoute: typeof AuthOrgClassesClassIdGradebookRouteImport
      parentRoute: typeof AuthOrgRoute
    }
    '/_admin/admin/classes/$classId/sessions': {
      id: '/_admin/admin/classes/$classId/sessions'
      path: '/admin/classes/$classId/sessions'
      fullPath: '/admin/classes/$classId/sessions'
      preLoaderRoute: typeof AdminAdminClassesClassIdSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/classes/$classId/quizzes': {
      id: '/_admin/admin/classes/$classId/quizzes'
      path: '/admin/classes/$classId/quizzes'
      fullPath: '/admin/classes/$classId/quizzes'
      preLoaderRoute: typeof AdminAdminClassesClassIdQuizzesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/classes/$classId/questions': {
      id: '/_admin/admin/classes/$classId/questions'
      path: '/admin/classes/$classId/questions'
      fullPath: '/admin/classes/$classId/questions'
      preLoaderRoute: typeof AdminAdminClassesClassIdQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/classes/$classId/practices': {
      id: '/_admin/admin/classes/$classId/practices'
      path: '/admin/classes/$classId/practices'
      fullPath: '/admin/classes/$classId/practices'
      preLoaderRoute: typeof AdminAdminClassesClassIdPracticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/classes/$classId/offlines': {
      id: '/_admin/admin/classes/$classId/offlines'
      path: '/admin/classes/$classId/offlines'
      fullPath: '/admin/classes/$classId/offlines'
      preLoaderRoute: typeof AdminAdminClassesClassIdOfflinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/classes/$classId/members': {
      id: '/_admin/admin/classes/$classId/members'
      path: '/admin/classes/$classId/members'
      fullPath: '/admin/classes/$classId/members'
      preLoaderRoute: typeof AdminAdminClassesClassIdMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/classes/$classId/live-rooms': {
      id: '/_admin/admin/classes/$classId/live-rooms'
      path: '/admin/classes/$classId/live-rooms'
      fullPath: '/admin/classes/$classId/live-rooms'
      preLoaderRoute: typeof AdminAdminClassesClassIdLiveRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/classes/$classId/gradebook': {
      id: '/_admin/admin/classes/$classId/gradebook'
      path: '/admin/classes/$classId/gradebook'
      fullPath: '/admin/classes/$classId/gradebook'
      preLoaderRoute: typeof AdminAdminClassesClassIdGradebookRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAccountRoute: typeof AdminAdminAccountRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminNotificationsRoute: typeof AdminAdminNotificationsRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminBillingPricesRoute: typeof AdminAdminBillingPricesRoute
  AdminAdminChangelogIdRoute: typeof AdminAdminChangelogIdRoute
  AdminAdminTutorialsIdRoute: typeof AdminAdminTutorialsIdRoute
  AdminAdminAttendanceIndexRoute: typeof AdminAdminAttendanceIndexRoute
  AdminAdminChangelogIndexRoute: typeof AdminAdminChangelogIndexRoute
  AdminAdminClassesIndexRoute: typeof AdminAdminClassesIndexRoute
  AdminAdminCorrectionsIndexRoute: typeof AdminAdminCorrectionsIndexRoute
  AdminAdminGradebookIndexRoute: typeof AdminAdminGradebookIndexRoute
  AdminAdminLeadsIndexRoute: typeof AdminAdminLeadsIndexRoute
  AdminAdminLiveRoomsIndexRoute: typeof AdminAdminLiveRoomsIndexRoute
  AdminAdminOfflinesIndexRoute: typeof AdminAdminOfflinesIndexRoute
  AdminAdminOrganizationsIndexRoute: typeof AdminAdminOrganizationsIndexRoute
  AdminAdminPermissionsIndexRoute: typeof AdminAdminPermissionsIndexRoute
  AdminAdminPracticesIndexRoute: typeof AdminAdminPracticesIndexRoute
  AdminAdminQuestionsIndexRoute: typeof AdminAdminQuestionsIndexRoute
  AdminAdminQuizzesIndexRoute: typeof AdminAdminQuizzesIndexRoute
  AdminAdminRolesIndexRoute: typeof AdminAdminRolesIndexRoute
  AdminAdminSessionsIndexRoute: typeof AdminAdminSessionsIndexRoute
  AdminAdminTutorialsIndexRoute: typeof AdminAdminTutorialsIndexRoute
  AdminAdminUsersIndexRoute: typeof AdminAdminUsersIndexRoute
  AdminAdminClassesClassIdGradebookRoute: typeof AdminAdminClassesClassIdGradebookRoute
  AdminAdminClassesClassIdLiveRoomsRoute: typeof AdminAdminClassesClassIdLiveRoomsRoute
  AdminAdminClassesClassIdMembersRoute: typeof AdminAdminClassesClassIdMembersRoute
  AdminAdminClassesClassIdOfflinesRoute: typeof AdminAdminClassesClassIdOfflinesRoute
  AdminAdminClassesClassIdPracticesRoute: typeof AdminAdminClassesClassIdPracticesRoute
  AdminAdminClassesClassIdQuestionsRoute: typeof AdminAdminClassesClassIdQuestionsRoute
  AdminAdminClassesClassIdQuizzesRoute: typeof AdminAdminClassesClassIdQuizzesRoute
  AdminAdminClassesClassIdSessionsRoute: typeof AdminAdminClassesClassIdSessionsRoute
  AdminAdminBillingInvoicesIndexRoute: typeof AdminAdminBillingInvoicesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAccountRoute: AdminAdminAccountRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminNotificationsRoute: AdminAdminNotificationsRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminBillingPricesRoute: AdminAdminBillingPricesRoute,
  AdminAdminChangelogIdRoute: AdminAdminChangelogIdRoute,
  AdminAdminTutorialsIdRoute: AdminAdminTutorialsIdRoute,
  AdminAdminAttendanceIndexRoute: AdminAdminAttendanceIndexRoute,
  AdminAdminChangelogIndexRoute: AdminAdminChangelogIndexRoute,
  AdminAdminClassesIndexRoute: AdminAdminClassesIndexRoute,
  AdminAdminCorrectionsIndexRoute: AdminAdminCorrectionsIndexRoute,
  AdminAdminGradebookIndexRoute: AdminAdminGradebookIndexRoute,
  AdminAdminLeadsIndexRoute: AdminAdminLeadsIndexRoute,
  AdminAdminLiveRoomsIndexRoute: AdminAdminLiveRoomsIndexRoute,
  AdminAdminOfflinesIndexRoute: AdminAdminOfflinesIndexRoute,
  AdminAdminOrganizationsIndexRoute: AdminAdminOrganizationsIndexRoute,
  AdminAdminPermissionsIndexRoute: AdminAdminPermissionsIndexRoute,
  AdminAdminPracticesIndexRoute: AdminAdminPracticesIndexRoute,
  AdminAdminQuestionsIndexRoute: AdminAdminQuestionsIndexRoute,
  AdminAdminQuizzesIndexRoute: AdminAdminQuizzesIndexRoute,
  AdminAdminRolesIndexRoute: AdminAdminRolesIndexRoute,
  AdminAdminSessionsIndexRoute: AdminAdminSessionsIndexRoute,
  AdminAdminTutorialsIndexRoute: AdminAdminTutorialsIndexRoute,
  AdminAdminUsersIndexRoute: AdminAdminUsersIndexRoute,
  AdminAdminClassesClassIdGradebookRoute:
    AdminAdminClassesClassIdGradebookRoute,
  AdminAdminClassesClassIdLiveRoomsRoute:
    AdminAdminClassesClassIdLiveRoomsRoute,
  AdminAdminClassesClassIdMembersRoute: AdminAdminClassesClassIdMembersRoute,
  AdminAdminClassesClassIdOfflinesRoute: AdminAdminClassesClassIdOfflinesRoute,
  AdminAdminClassesClassIdPracticesRoute:
    AdminAdminClassesClassIdPracticesRoute,
  AdminAdminClassesClassIdQuestionsRoute:
    AdminAdminClassesClassIdQuestionsRoute,
  AdminAdminClassesClassIdQuizzesRoute: AdminAdminClassesClassIdQuizzesRoute,
  AdminAdminClassesClassIdSessionsRoute: AdminAdminClassesClassIdSessionsRoute,
  AdminAdminBillingInvoicesIndexRoute: AdminAdminBillingInvoicesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthOrgConversationsRouteRouteChildren {
  AuthOrgConversationsConversationIdRoute: typeof AuthOrgConversationsConversationIdRoute
  AuthOrgConversationsIndexRoute: typeof AuthOrgConversationsIndexRoute
}

const AuthOrgConversationsRouteRouteChildren: AuthOrgConversationsRouteRouteChildren =
  {
    AuthOrgConversationsConversationIdRoute:
      AuthOrgConversationsConversationIdRoute,
    AuthOrgConversationsIndexRoute: AuthOrgConversationsIndexRoute,
  }

const AuthOrgConversationsRouteRouteWithChildren =
  AuthOrgConversationsRouteRoute._addFileChildren(
    AuthOrgConversationsRouteRouteChildren,
  )

interface AuthOrgRouteChildren {
  AuthOrgConversationsRouteRoute: typeof AuthOrgConversationsRouteRouteWithChildren
  AuthOrgAccountRoute: typeof AuthOrgAccountRoute
  AuthOrgCalendarRoute: typeof AuthOrgCalendarRoute
  AuthOrgDashboardRoute: typeof AuthOrgDashboardRoute
  AuthOrgTutorialsRoute: typeof AuthOrgTutorialsRoute
  AuthOrgWhatsNewRoute: typeof AuthOrgWhatsNewRoute
  AuthOrgIndexRoute: typeof AuthOrgIndexRoute
  AuthOrgBillingInvoicesRoute: typeof AuthOrgBillingInvoicesRoute
  AuthOrgBillingResultRoute: typeof AuthOrgBillingResultRoute
  AuthOrgClassesClassIdRoute: typeof AuthOrgClassesClassIdRoute
  AuthOrgFilesFolderRoute: typeof AuthOrgFilesFolderRoute
  AuthOrgNotificationsSendRoute: typeof AuthOrgNotificationsSendRoute
  AuthOrgNotificationsSettingsRoute: typeof AuthOrgNotificationsSettingsRoute
  AuthOrgOfflinesOfflineIdRoute: typeof AuthOrgOfflinesOfflineIdRoute
  AuthOrgAttendanceIndexRoute: typeof AuthOrgAttendanceIndexRoute
  AuthOrgBillingIndexRoute: typeof AuthOrgBillingIndexRoute
  AuthOrgClassesIndexRoute: typeof AuthOrgClassesIndexRoute
  AuthOrgExamsIndexRoute: typeof AuthOrgExamsIndexRoute
  AuthOrgFilesIndexRoute: typeof AuthOrgFilesIndexRoute
  AuthOrgGradesIndexRoute: typeof AuthOrgGradesIndexRoute
  AuthOrgMediasIndexRoute: typeof AuthOrgMediasIndexRoute
  AuthOrgNotificationsIndexRoute: typeof AuthOrgNotificationsIndexRoute
  AuthOrgOnlineClassesIndexRoute: typeof AuthOrgOnlineClassesIndexRoute
  AuthOrgPracticesIndexRoute: typeof AuthOrgPracticesIndexRoute
  AuthOrgRolesIndexRoute: typeof AuthOrgRolesIndexRoute
  AuthOrgSettingsIndexRoute: typeof AuthOrgSettingsIndexRoute
  AuthOrgTicketsIndexRoute: typeof AuthOrgTicketsIndexRoute
  AuthOrgUsersIndexRoute: typeof AuthOrgUsersIndexRoute
  AuthOrgClassesClassIdGradebookRoute: typeof AuthOrgClassesClassIdGradebookRoute
  AuthOrgClassesClassSessionsClassSessionIdRoute: typeof AuthOrgClassesClassSessionsClassSessionIdRoute
}

const AuthOrgRouteChildren: AuthOrgRouteChildren = {
  AuthOrgConversationsRouteRoute: AuthOrgConversationsRouteRouteWithChildren,
  AuthOrgAccountRoute: AuthOrgAccountRoute,
  AuthOrgCalendarRoute: AuthOrgCalendarRoute,
  AuthOrgDashboardRoute: AuthOrgDashboardRoute,
  AuthOrgTutorialsRoute: AuthOrgTutorialsRoute,
  AuthOrgWhatsNewRoute: AuthOrgWhatsNewRoute,
  AuthOrgIndexRoute: AuthOrgIndexRoute,
  AuthOrgBillingInvoicesRoute: AuthOrgBillingInvoicesRoute,
  AuthOrgBillingResultRoute: AuthOrgBillingResultRoute,
  AuthOrgClassesClassIdRoute: AuthOrgClassesClassIdRoute,
  AuthOrgFilesFolderRoute: AuthOrgFilesFolderRoute,
  AuthOrgNotificationsSendRoute: AuthOrgNotificationsSendRoute,
  AuthOrgNotificationsSettingsRoute: AuthOrgNotificationsSettingsRoute,
  AuthOrgOfflinesOfflineIdRoute: AuthOrgOfflinesOfflineIdRoute,
  AuthOrgAttendanceIndexRoute: AuthOrgAttendanceIndexRoute,
  AuthOrgBillingIndexRoute: AuthOrgBillingIndexRoute,
  AuthOrgClassesIndexRoute: AuthOrgClassesIndexRoute,
  AuthOrgExamsIndexRoute: AuthOrgExamsIndexRoute,
  AuthOrgFilesIndexRoute: AuthOrgFilesIndexRoute,
  AuthOrgGradesIndexRoute: AuthOrgGradesIndexRoute,
  AuthOrgMediasIndexRoute: AuthOrgMediasIndexRoute,
  AuthOrgNotificationsIndexRoute: AuthOrgNotificationsIndexRoute,
  AuthOrgOnlineClassesIndexRoute: AuthOrgOnlineClassesIndexRoute,
  AuthOrgPracticesIndexRoute: AuthOrgPracticesIndexRoute,
  AuthOrgRolesIndexRoute: AuthOrgRolesIndexRoute,
  AuthOrgSettingsIndexRoute: AuthOrgSettingsIndexRoute,
  AuthOrgTicketsIndexRoute: AuthOrgTicketsIndexRoute,
  AuthOrgUsersIndexRoute: AuthOrgUsersIndexRoute,
  AuthOrgClassesClassIdGradebookRoute: AuthOrgClassesClassIdGradebookRoute,
  AuthOrgClassesClassSessionsClassSessionIdRoute:
    AuthOrgClassesClassSessionsClassSessionIdRoute,
}

const AuthOrgRouteWithChildren =
  AuthOrgRoute._addFileChildren(AuthOrgRouteChildren)

interface AuthRouteChildren {
  AuthOrgRoute: typeof AuthOrgRouteWithChildren
  AuthLiveLiveIdRoute: typeof AuthLiveLiveIdRoute
  AuthQuizQuizIdRoute: typeof AuthQuizQuizIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOrgRoute: AuthOrgRouteWithChildren,
  AuthLiveLiveIdRoute: AuthLiveLiveIdRoute,
  AuthQuizQuizIdRoute: AuthQuizQuizIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface GuestRouteChildren {
  GuestGetStartedRoute: typeof GuestGetStartedRoute
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestGetStartedRoute: GuestGetStartedRoute,
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
