/**
 * Generated by orval v8.8.1 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteClassesIdGradebookColumnsColumnId401,
  DeleteClassesIdGradebookColumnsColumnId403,
  DeleteClassesIdGradebookColumnsColumnId404,
  GetClassesIdGradebook200,
  GetClassesIdGradebook401,
  GetClassesIdGradebook403,
  GetClassesIdGradebook404,
  GetClassesIdGradebookColumns200,
  GetClassesIdGradebookColumns401,
  GetClassesIdGradebookColumns403,
  GetClassesIdGradebookColumns404,
  GetClassesIdGradebookColumnsParams,
  GetGradebookMe200,
  GetGradebookMe401,
  GithubCom4H1RZooraInternalDomainCreateGradebookColumnDTO,
  GithubCom4H1RZooraInternalDomainResponse,
  GithubCom4H1RZooraInternalDomainUpdateGradebookColumnDTO,
  GithubCom4H1RZooraInternalDomainUpsertGradebookCellDTO,
  PostClassesIdGradebookColumns201,
  PostClassesIdGradebookColumns400,
  PostClassesIdGradebookColumns401,
  PostClassesIdGradebookColumns403,
  PostClassesIdGradebookColumnsColumnIdCells200,
  PostClassesIdGradebookColumnsColumnIdCells400,
  PostClassesIdGradebookColumnsColumnIdCells401,
  PostClassesIdGradebookColumnsColumnIdCells403,
  PostClassesIdGradebookColumnsColumnIdCells404,
  PutClassesIdGradebookColumnsColumnId200,
  PutClassesIdGradebookColumnsColumnId400,
  PutClassesIdGradebookColumnsColumnId401,
  PutClassesIdGradebookColumnsColumnId403,
  PutClassesIdGradebookColumnsColumnId404
} from '../model';

import { customInstance } from '.././mutator/custom-instance';
import type { ErrorType } from '.././mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get gradebook matrix
 */
export type getClassesIdGradebookResponse200 = {
  data: GetClassesIdGradebook200
  status: 200
}

export type getClassesIdGradebookResponse401 = {
  data: GetClassesIdGradebook401
  status: 401
}

export type getClassesIdGradebookResponse403 = {
  data: GetClassesIdGradebook403
  status: 403
}

export type getClassesIdGradebookResponse404 = {
  data: GetClassesIdGradebook404
  status: 404
}

export type getClassesIdGradebookResponseSuccess = (getClassesIdGradebookResponse200) & {
  headers: Headers;
};
export type getClassesIdGradebookResponseError = (getClassesIdGradebookResponse401 | getClassesIdGradebookResponse403 | getClassesIdGradebookResponse404) & {
  headers: Headers;
};

export type getClassesIdGradebookResponse = (getClassesIdGradebookResponseSuccess | getClassesIdGradebookResponseError)

export const getGetClassesIdGradebookUrl = (id: string,) => {




  return `/classes/${id}/gradebook`
}

export const getClassesIdGradebook = async (id: string, options?: RequestInit): Promise<getClassesIdGradebookResponse> => {

  return customInstance<getClassesIdGradebookResponse>(getGetClassesIdGradebookUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetClassesIdGradebookQueryKey = (id: string,) => {
    return [
    `/classes/${id}/gradebook`
    ] as const;
    }


export const getGetClassesIdGradebookQueryOptions = <TData = Awaited<ReturnType<typeof getClassesIdGradebook>>, TError = ErrorType<GetClassesIdGradebook401 | GetClassesIdGradebook403 | GetClassesIdGradebook404>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClassesIdGradebook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClassesIdGradebookQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClassesIdGradebook>>> = ({ signal }) => getClassesIdGradebook(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClassesIdGradebook>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClassesIdGradebookQueryResult = NonNullable<Awaited<ReturnType<typeof getClassesIdGradebook>>>
export type GetClassesIdGradebookQueryError = ErrorType<GetClassesIdGradebook401 | GetClassesIdGradebook403 | GetClassesIdGradebook404>


export function useGetClassesIdGradebook<TData = Awaited<ReturnType<typeof getClassesIdGradebook>>, TError = ErrorType<GetClassesIdGradebook401 | GetClassesIdGradebook403 | GetClassesIdGradebook404>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClassesIdGradebook>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClassesIdGradebook>>,
          TError,
          Awaited<ReturnType<typeof getClassesIdGradebook>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClassesIdGradebook<TData = Awaited<ReturnType<typeof getClassesIdGradebook>>, TError = ErrorType<GetClassesIdGradebook401 | GetClassesIdGradebook403 | GetClassesIdGradebook404>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClassesIdGradebook>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClassesIdGradebook>>,
          TError,
          Awaited<ReturnType<typeof getClassesIdGradebook>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClassesIdGradebook<TData = Awaited<ReturnType<typeof getClassesIdGradebook>>, TError = ErrorType<GetClassesIdGradebook401 | GetClassesIdGradebook403 | GetClassesIdGradebook404>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClassesIdGradebook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get gradebook matrix
 */

export function useGetClassesIdGradebook<TData = Awaited<ReturnType<typeof getClassesIdGradebook>>, TError = ErrorType<GetClassesIdGradebook401 | GetClassesIdGradebook403 | GetClassesIdGradebook404>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClassesIdGradebook>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClassesIdGradebookQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Search matches substrings of: title. Orderable fields: created_at, updated_at, title, order_index. Filters: type.
 * @summary List gradebook columns
 */
export type getClassesIdGradebookColumnsResponse200 = {
  data: GetClassesIdGradebookColumns200
  status: 200
}

export type getClassesIdGradebookColumnsResponse401 = {
  data: GetClassesIdGradebookColumns401
  status: 401
}

export type getClassesIdGradebookColumnsResponse403 = {
  data: GetClassesIdGradebookColumns403
  status: 403
}

export type getClassesIdGradebookColumnsResponse404 = {
  data: GetClassesIdGradebookColumns404
  status: 404
}

export type getClassesIdGradebookColumnsResponseSuccess = (getClassesIdGradebookColumnsResponse200) & {
  headers: Headers;
};
export type getClassesIdGradebookColumnsResponseError = (getClassesIdGradebookColumnsResponse401 | getClassesIdGradebookColumnsResponse403 | getClassesIdGradebookColumnsResponse404) & {
  headers: Headers;
};

export type getClassesIdGradebookColumnsResponse = (getClassesIdGradebookColumnsResponseSuccess | getClassesIdGradebookColumnsResponseError)

export const getGetClassesIdGradebookColumnsUrl = (id: string,
    params?: GetClassesIdGradebookColumnsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/classes/${id}/gradebook/columns?${stringifiedParams}` : `/classes/${id}/gradebook/columns`
}

export const getClassesIdGradebookColumns = async (id: string,
    params?: GetClassesIdGradebookColumnsParams, options?: RequestInit): Promise<getClassesIdGradebookColumnsResponse> => {

  return customInstance<getClassesIdGradebookColumnsResponse>(getGetClassesIdGradebookColumnsUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetClassesIdGradebookColumnsQueryKey = (id: string,
    params?: GetClassesIdGradebookColumnsParams,) => {
    return [
    `/classes/${id}/gradebook/columns`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetClassesIdGradebookColumnsQueryOptions = <TData = Awaited<ReturnType<typeof getClassesIdGradebookColumns>>, TError = ErrorType<GetClassesIdGradebookColumns401 | GetClassesIdGradebookColumns403 | GetClassesIdGradebookColumns404>>(id: string,
    params?: GetClassesIdGradebookColumnsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClassesIdGradebookColumns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClassesIdGradebookColumnsQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClassesIdGradebookColumns>>> = ({ signal }) => getClassesIdGradebookColumns(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClassesIdGradebookColumns>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClassesIdGradebookColumnsQueryResult = NonNullable<Awaited<ReturnType<typeof getClassesIdGradebookColumns>>>
export type GetClassesIdGradebookColumnsQueryError = ErrorType<GetClassesIdGradebookColumns401 | GetClassesIdGradebookColumns403 | GetClassesIdGradebookColumns404>


export function useGetClassesIdGradebookColumns<TData = Awaited<ReturnType<typeof getClassesIdGradebookColumns>>, TError = ErrorType<GetClassesIdGradebookColumns401 | GetClassesIdGradebookColumns403 | GetClassesIdGradebookColumns404>>(
 id: string,
    params: undefined |  GetClassesIdGradebookColumnsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClassesIdGradebookColumns>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClassesIdGradebookColumns>>,
          TError,
          Awaited<ReturnType<typeof getClassesIdGradebookColumns>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClassesIdGradebookColumns<TData = Awaited<ReturnType<typeof getClassesIdGradebookColumns>>, TError = ErrorType<GetClassesIdGradebookColumns401 | GetClassesIdGradebookColumns403 | GetClassesIdGradebookColumns404>>(
 id: string,
    params?: GetClassesIdGradebookColumnsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClassesIdGradebookColumns>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClassesIdGradebookColumns>>,
          TError,
          Awaited<ReturnType<typeof getClassesIdGradebookColumns>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClassesIdGradebookColumns<TData = Awaited<ReturnType<typeof getClassesIdGradebookColumns>>, TError = ErrorType<GetClassesIdGradebookColumns401 | GetClassesIdGradebookColumns403 | GetClassesIdGradebookColumns404>>(
 id: string,
    params?: GetClassesIdGradebookColumnsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClassesIdGradebookColumns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List gradebook columns
 */

export function useGetClassesIdGradebookColumns<TData = Awaited<ReturnType<typeof getClassesIdGradebookColumns>>, TError = ErrorType<GetClassesIdGradebookColumns401 | GetClassesIdGradebookColumns403 | GetClassesIdGradebookColumns404>>(
 id: string,
    params?: GetClassesIdGradebookColumnsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClassesIdGradebookColumns>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClassesIdGradebookColumnsQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary Create gradebook column
 */
export type postClassesIdGradebookColumnsResponse201 = {
  data: PostClassesIdGradebookColumns201
  status: 201
}

export type postClassesIdGradebookColumnsResponse400 = {
  data: PostClassesIdGradebookColumns400
  status: 400
}

export type postClassesIdGradebookColumnsResponse401 = {
  data: PostClassesIdGradebookColumns401
  status: 401
}

export type postClassesIdGradebookColumnsResponse403 = {
  data: PostClassesIdGradebookColumns403
  status: 403
}

export type postClassesIdGradebookColumnsResponseSuccess = (postClassesIdGradebookColumnsResponse201) & {
  headers: Headers;
};
export type postClassesIdGradebookColumnsResponseError = (postClassesIdGradebookColumnsResponse400 | postClassesIdGradebookColumnsResponse401 | postClassesIdGradebookColumnsResponse403) & {
  headers: Headers;
};

export type postClassesIdGradebookColumnsResponse = (postClassesIdGradebookColumnsResponseSuccess | postClassesIdGradebookColumnsResponseError)

export const getPostClassesIdGradebookColumnsUrl = (id: string,) => {




  return `/classes/${id}/gradebook/columns`
}

export const postClassesIdGradebookColumns = async (id: string,
    githubCom4H1RZooraInternalDomainCreateGradebookColumnDTO: GithubCom4H1RZooraInternalDomainCreateGradebookColumnDTO, options?: RequestInit): Promise<postClassesIdGradebookColumnsResponse> => {

  return customInstance<postClassesIdGradebookColumnsResponse>(getPostClassesIdGradebookColumnsUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      githubCom4H1RZooraInternalDomainCreateGradebookColumnDTO,)
  }
);}




export const getPostClassesIdGradebookColumnsMutationOptions = <TError = ErrorType<PostClassesIdGradebookColumns400 | PostClassesIdGradebookColumns401 | PostClassesIdGradebookColumns403>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postClassesIdGradebookColumns>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainCreateGradebookColumnDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postClassesIdGradebookColumns>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainCreateGradebookColumnDTO}, TContext> => {

const mutationKey = ['postClassesIdGradebookColumns'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postClassesIdGradebookColumns>>, {id: string;data: GithubCom4H1RZooraInternalDomainCreateGradebookColumnDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  postClassesIdGradebookColumns(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostClassesIdGradebookColumnsMutationResult = NonNullable<Awaited<ReturnType<typeof postClassesIdGradebookColumns>>>
    export type PostClassesIdGradebookColumnsMutationBody = GithubCom4H1RZooraInternalDomainCreateGradebookColumnDTO
    export type PostClassesIdGradebookColumnsMutationError = ErrorType<PostClassesIdGradebookColumns400 | PostClassesIdGradebookColumns401 | PostClassesIdGradebookColumns403>

    /**
 * @summary Create gradebook column
 */
export const usePostClassesIdGradebookColumns = <TError = ErrorType<PostClassesIdGradebookColumns400 | PostClassesIdGradebookColumns401 | PostClassesIdGradebookColumns403>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postClassesIdGradebookColumns>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainCreateGradebookColumnDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postClassesIdGradebookColumns>>,
        TError,
        {id: string;data: GithubCom4H1RZooraInternalDomainCreateGradebookColumnDTO},
        TContext
      > => {
      return useMutation(getPostClassesIdGradebookColumnsMutationOptions(options), queryClient);
    }
    /**
 * @summary Update gradebook column
 */
export type putClassesIdGradebookColumnsColumnIdResponse200 = {
  data: PutClassesIdGradebookColumnsColumnId200
  status: 200
}

export type putClassesIdGradebookColumnsColumnIdResponse400 = {
  data: PutClassesIdGradebookColumnsColumnId400
  status: 400
}

export type putClassesIdGradebookColumnsColumnIdResponse401 = {
  data: PutClassesIdGradebookColumnsColumnId401
  status: 401
}

export type putClassesIdGradebookColumnsColumnIdResponse403 = {
  data: PutClassesIdGradebookColumnsColumnId403
  status: 403
}

export type putClassesIdGradebookColumnsColumnIdResponse404 = {
  data: PutClassesIdGradebookColumnsColumnId404
  status: 404
}

export type putClassesIdGradebookColumnsColumnIdResponseSuccess = (putClassesIdGradebookColumnsColumnIdResponse200) & {
  headers: Headers;
};
export type putClassesIdGradebookColumnsColumnIdResponseError = (putClassesIdGradebookColumnsColumnIdResponse400 | putClassesIdGradebookColumnsColumnIdResponse401 | putClassesIdGradebookColumnsColumnIdResponse403 | putClassesIdGradebookColumnsColumnIdResponse404) & {
  headers: Headers;
};

export type putClassesIdGradebookColumnsColumnIdResponse = (putClassesIdGradebookColumnsColumnIdResponseSuccess | putClassesIdGradebookColumnsColumnIdResponseError)

export const getPutClassesIdGradebookColumnsColumnIdUrl = (id: string,
    columnId: string,) => {




  return `/classes/${id}/gradebook/columns/${columnId}`
}

export const putClassesIdGradebookColumnsColumnId = async (id: string,
    columnId: string,
    githubCom4H1RZooraInternalDomainUpdateGradebookColumnDTO: GithubCom4H1RZooraInternalDomainUpdateGradebookColumnDTO, options?: RequestInit): Promise<putClassesIdGradebookColumnsColumnIdResponse> => {

  return customInstance<putClassesIdGradebookColumnsColumnIdResponse>(getPutClassesIdGradebookColumnsColumnIdUrl(id,columnId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      githubCom4H1RZooraInternalDomainUpdateGradebookColumnDTO,)
  }
);}




export const getPutClassesIdGradebookColumnsColumnIdMutationOptions = <TError = ErrorType<PutClassesIdGradebookColumnsColumnId400 | PutClassesIdGradebookColumnsColumnId401 | PutClassesIdGradebookColumnsColumnId403 | PutClassesIdGradebookColumnsColumnId404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putClassesIdGradebookColumnsColumnId>>, TError,{id: string;columnId: string;data: GithubCom4H1RZooraInternalDomainUpdateGradebookColumnDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putClassesIdGradebookColumnsColumnId>>, TError,{id: string;columnId: string;data: GithubCom4H1RZooraInternalDomainUpdateGradebookColumnDTO}, TContext> => {

const mutationKey = ['putClassesIdGradebookColumnsColumnId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putClassesIdGradebookColumnsColumnId>>, {id: string;columnId: string;data: GithubCom4H1RZooraInternalDomainUpdateGradebookColumnDTO}> = (props) => {
          const {id,columnId,data} = props ?? {};

          return  putClassesIdGradebookColumnsColumnId(id,columnId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutClassesIdGradebookColumnsColumnIdMutationResult = NonNullable<Awaited<ReturnType<typeof putClassesIdGradebookColumnsColumnId>>>
    export type PutClassesIdGradebookColumnsColumnIdMutationBody = GithubCom4H1RZooraInternalDomainUpdateGradebookColumnDTO
    export type PutClassesIdGradebookColumnsColumnIdMutationError = ErrorType<PutClassesIdGradebookColumnsColumnId400 | PutClassesIdGradebookColumnsColumnId401 | PutClassesIdGradebookColumnsColumnId403 | PutClassesIdGradebookColumnsColumnId404>

    /**
 * @summary Update gradebook column
 */
export const usePutClassesIdGradebookColumnsColumnId = <TError = ErrorType<PutClassesIdGradebookColumnsColumnId400 | PutClassesIdGradebookColumnsColumnId401 | PutClassesIdGradebookColumnsColumnId403 | PutClassesIdGradebookColumnsColumnId404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putClassesIdGradebookColumnsColumnId>>, TError,{id: string;columnId: string;data: GithubCom4H1RZooraInternalDomainUpdateGradebookColumnDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putClassesIdGradebookColumnsColumnId>>,
        TError,
        {id: string;columnId: string;data: GithubCom4H1RZooraInternalDomainUpdateGradebookColumnDTO},
        TContext
      > => {
      return useMutation(getPutClassesIdGradebookColumnsColumnIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete gradebook column
 */
export type deleteClassesIdGradebookColumnsColumnIdResponse200 = {
  data: GithubCom4H1RZooraInternalDomainResponse
  status: 200
}

export type deleteClassesIdGradebookColumnsColumnIdResponse401 = {
  data: DeleteClassesIdGradebookColumnsColumnId401
  status: 401
}

export type deleteClassesIdGradebookColumnsColumnIdResponse403 = {
  data: DeleteClassesIdGradebookColumnsColumnId403
  status: 403
}

export type deleteClassesIdGradebookColumnsColumnIdResponse404 = {
  data: DeleteClassesIdGradebookColumnsColumnId404
  status: 404
}

export type deleteClassesIdGradebookColumnsColumnIdResponseSuccess = (deleteClassesIdGradebookColumnsColumnIdResponse200) & {
  headers: Headers;
};
export type deleteClassesIdGradebookColumnsColumnIdResponseError = (deleteClassesIdGradebookColumnsColumnIdResponse401 | deleteClassesIdGradebookColumnsColumnIdResponse403 | deleteClassesIdGradebookColumnsColumnIdResponse404) & {
  headers: Headers;
};

export type deleteClassesIdGradebookColumnsColumnIdResponse = (deleteClassesIdGradebookColumnsColumnIdResponseSuccess | deleteClassesIdGradebookColumnsColumnIdResponseError)

export const getDeleteClassesIdGradebookColumnsColumnIdUrl = (id: string,
    columnId: string,) => {




  return `/classes/${id}/gradebook/columns/${columnId}`
}

export const deleteClassesIdGradebookColumnsColumnId = async (id: string,
    columnId: string, options?: RequestInit): Promise<deleteClassesIdGradebookColumnsColumnIdResponse> => {

  return customInstance<deleteClassesIdGradebookColumnsColumnIdResponse>(getDeleteClassesIdGradebookColumnsColumnIdUrl(id,columnId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteClassesIdGradebookColumnsColumnIdMutationOptions = <TError = ErrorType<DeleteClassesIdGradebookColumnsColumnId401 | DeleteClassesIdGradebookColumnsColumnId403 | DeleteClassesIdGradebookColumnsColumnId404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteClassesIdGradebookColumnsColumnId>>, TError,{id: string;columnId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteClassesIdGradebookColumnsColumnId>>, TError,{id: string;columnId: string}, TContext> => {

const mutationKey = ['deleteClassesIdGradebookColumnsColumnId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteClassesIdGradebookColumnsColumnId>>, {id: string;columnId: string}> = (props) => {
          const {id,columnId} = props ?? {};

          return  deleteClassesIdGradebookColumnsColumnId(id,columnId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteClassesIdGradebookColumnsColumnIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteClassesIdGradebookColumnsColumnId>>>

    export type DeleteClassesIdGradebookColumnsColumnIdMutationError = ErrorType<DeleteClassesIdGradebookColumnsColumnId401 | DeleteClassesIdGradebookColumnsColumnId403 | DeleteClassesIdGradebookColumnsColumnId404>

    /**
 * @summary Delete gradebook column
 */
export const useDeleteClassesIdGradebookColumnsColumnId = <TError = ErrorType<DeleteClassesIdGradebookColumnsColumnId401 | DeleteClassesIdGradebookColumnsColumnId403 | DeleteClassesIdGradebookColumnsColumnId404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteClassesIdGradebookColumnsColumnId>>, TError,{id: string;columnId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteClassesIdGradebookColumnsColumnId>>,
        TError,
        {id: string;columnId: string},
        TContext
      > => {
      return useMutation(getDeleteClassesIdGradebookColumnsColumnIdMutationOptions(options), queryClient);
    }
    /**
 * @summary Upsert gradebook cell
 */
export type postClassesIdGradebookColumnsColumnIdCellsResponse200 = {
  data: PostClassesIdGradebookColumnsColumnIdCells200
  status: 200
}

export type postClassesIdGradebookColumnsColumnIdCellsResponse400 = {
  data: PostClassesIdGradebookColumnsColumnIdCells400
  status: 400
}

export type postClassesIdGradebookColumnsColumnIdCellsResponse401 = {
  data: PostClassesIdGradebookColumnsColumnIdCells401
  status: 401
}

export type postClassesIdGradebookColumnsColumnIdCellsResponse403 = {
  data: PostClassesIdGradebookColumnsColumnIdCells403
  status: 403
}

export type postClassesIdGradebookColumnsColumnIdCellsResponse404 = {
  data: PostClassesIdGradebookColumnsColumnIdCells404
  status: 404
}

export type postClassesIdGradebookColumnsColumnIdCellsResponseSuccess = (postClassesIdGradebookColumnsColumnIdCellsResponse200) & {
  headers: Headers;
};
export type postClassesIdGradebookColumnsColumnIdCellsResponseError = (postClassesIdGradebookColumnsColumnIdCellsResponse400 | postClassesIdGradebookColumnsColumnIdCellsResponse401 | postClassesIdGradebookColumnsColumnIdCellsResponse403 | postClassesIdGradebookColumnsColumnIdCellsResponse404) & {
  headers: Headers;
};

export type postClassesIdGradebookColumnsColumnIdCellsResponse = (postClassesIdGradebookColumnsColumnIdCellsResponseSuccess | postClassesIdGradebookColumnsColumnIdCellsResponseError)

export const getPostClassesIdGradebookColumnsColumnIdCellsUrl = (id: string,
    columnId: string,) => {




  return `/classes/${id}/gradebook/columns/${columnId}/cells`
}

export const postClassesIdGradebookColumnsColumnIdCells = async (id: string,
    columnId: string,
    githubCom4H1RZooraInternalDomainUpsertGradebookCellDTO: GithubCom4H1RZooraInternalDomainUpsertGradebookCellDTO, options?: RequestInit): Promise<postClassesIdGradebookColumnsColumnIdCellsResponse> => {

  return customInstance<postClassesIdGradebookColumnsColumnIdCellsResponse>(getPostClassesIdGradebookColumnsColumnIdCellsUrl(id,columnId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      githubCom4H1RZooraInternalDomainUpsertGradebookCellDTO,)
  }
);}




export const getPostClassesIdGradebookColumnsColumnIdCellsMutationOptions = <TError = ErrorType<PostClassesIdGradebookColumnsColumnIdCells400 | PostClassesIdGradebookColumnsColumnIdCells401 | PostClassesIdGradebookColumnsColumnIdCells403 | PostClassesIdGradebookColumnsColumnIdCells404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postClassesIdGradebookColumnsColumnIdCells>>, TError,{id: string;columnId: string;data: GithubCom4H1RZooraInternalDomainUpsertGradebookCellDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postClassesIdGradebookColumnsColumnIdCells>>, TError,{id: string;columnId: string;data: GithubCom4H1RZooraInternalDomainUpsertGradebookCellDTO}, TContext> => {

const mutationKey = ['postClassesIdGradebookColumnsColumnIdCells'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postClassesIdGradebookColumnsColumnIdCells>>, {id: string;columnId: string;data: GithubCom4H1RZooraInternalDomainUpsertGradebookCellDTO}> = (props) => {
          const {id,columnId,data} = props ?? {};

          return  postClassesIdGradebookColumnsColumnIdCells(id,columnId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostClassesIdGradebookColumnsColumnIdCellsMutationResult = NonNullable<Awaited<ReturnType<typeof postClassesIdGradebookColumnsColumnIdCells>>>
    export type PostClassesIdGradebookColumnsColumnIdCellsMutationBody = GithubCom4H1RZooraInternalDomainUpsertGradebookCellDTO
    export type PostClassesIdGradebookColumnsColumnIdCellsMutationError = ErrorType<PostClassesIdGradebookColumnsColumnIdCells400 | PostClassesIdGradebookColumnsColumnIdCells401 | PostClassesIdGradebookColumnsColumnIdCells403 | PostClassesIdGradebookColumnsColumnIdCells404>

    /**
 * @summary Upsert gradebook cell
 */
export const usePostClassesIdGradebookColumnsColumnIdCells = <TError = ErrorType<PostClassesIdGradebookColumnsColumnIdCells400 | PostClassesIdGradebookColumnsColumnIdCells401 | PostClassesIdGradebookColumnsColumnIdCells403 | PostClassesIdGradebookColumnsColumnIdCells404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postClassesIdGradebookColumnsColumnIdCells>>, TError,{id: string;columnId: string;data: GithubCom4H1RZooraInternalDomainUpsertGradebookCellDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postClassesIdGradebookColumnsColumnIdCells>>,
        TError,
        {id: string;columnId: string;data: GithubCom4H1RZooraInternalDomainUpsertGradebookCellDTO},
        TContext
      > => {
      return useMutation(getPostClassesIdGradebookColumnsColumnIdCellsMutationOptions(options), queryClient);
    }
    /**
 * @summary Get my grades
 */
export type getGradebookMeResponse200 = {
  data: GetGradebookMe200
  status: 200
}

export type getGradebookMeResponse401 = {
  data: GetGradebookMe401
  status: 401
}

export type getGradebookMeResponseSuccess = (getGradebookMeResponse200) & {
  headers: Headers;
};
export type getGradebookMeResponseError = (getGradebookMeResponse401) & {
  headers: Headers;
};

export type getGradebookMeResponse = (getGradebookMeResponseSuccess | getGradebookMeResponseError)

export const getGetGradebookMeUrl = () => {




  return `/gradebook/me`
}

export const getGradebookMe = async ( options?: RequestInit): Promise<getGradebookMeResponse> => {

  return customInstance<getGradebookMeResponse>(getGetGradebookMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetGradebookMeQueryKey = () => {
    return [
    `/gradebook/me`
    ] as const;
    }


export const getGetGradebookMeQueryOptions = <TData = Awaited<ReturnType<typeof getGradebookMe>>, TError = ErrorType<GetGradebookMe401>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradebookMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGradebookMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGradebookMe>>> = ({ signal }) => getGradebookMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGradebookMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGradebookMeQueryResult = NonNullable<Awaited<ReturnType<typeof getGradebookMe>>>
export type GetGradebookMeQueryError = ErrorType<GetGradebookMe401>


export function useGetGradebookMe<TData = Awaited<ReturnType<typeof getGradebookMe>>, TError = ErrorType<GetGradebookMe401>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradebookMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGradebookMe>>,
          TError,
          Awaited<ReturnType<typeof getGradebookMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGradebookMe<TData = Awaited<ReturnType<typeof getGradebookMe>>, TError = ErrorType<GetGradebookMe401>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradebookMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGradebookMe>>,
          TError,
          Awaited<ReturnType<typeof getGradebookMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGradebookMe<TData = Awaited<ReturnType<typeof getGradebookMe>>, TError = ErrorType<GetGradebookMe401>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradebookMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get my grades
 */

export function useGetGradebookMe<TData = Awaited<ReturnType<typeof getGradebookMe>>, TError = ErrorType<GetGradebookMe401>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradebookMe>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGradebookMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






