/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteLiveRoomsIdParticipantsIdentity401,
  DeleteLiveRoomsIdParticipantsIdentity403,
  DeleteLiveRoomsIdParticipantsIdentity404,
  DeleteLiveRoomsIdParticipantsIdentity409,
  GetLiveRooms200,
  GetLiveRooms401,
  GetLiveRooms403,
  GetLiveRoomsId200,
  GetLiveRoomsId401,
  GetLiveRoomsId403,
  GetLiveRoomsId404,
  GetLiveRoomsIdParticipants200,
  GetLiveRoomsIdParticipants401,
  GetLiveRoomsIdParticipants403,
  GetLiveRoomsIdParticipants404,
  GetLiveRoomsIdParticipantsParams,
  GetLiveRoomsIdRecordings200,
  GetLiveRoomsIdRecordings401,
  GetLiveRoomsIdRecordings403,
  GetLiveRoomsIdRecordings404,
  GetLiveRoomsIdRecordingsParams,
  GetLiveRoomsIdWhiteboard200,
  GetLiveRoomsIdWhiteboard401,
  GetLiveRoomsIdWhiteboard403,
  GetLiveRoomsIdWhiteboard404,
  GetLiveRoomsParams,
  GithubCom4H1RZooraInternalDomainCreateLiveRoomDTO,
  GithubCom4H1RZooraInternalDomainMuteParticipantDTO,
  GithubCom4H1RZooraInternalDomainResponse,
  GithubCom4H1RZooraInternalDomainSaveWhiteboardDTO,
  GithubCom4H1RZooraInternalDomainSetHandDTO,
  GithubCom4H1RZooraInternalDomainSetParticipantRoleDTO,
  GithubCom4H1RZooraInternalDomainUpdateLiveRoomConfigDTO,
  PostLiveRooms201,
  PostLiveRooms400,
  PostLiveRooms401,
  PostLiveRooms403,
  PostLiveRooms409,
  PostLiveRoomsIdEnd200,
  PostLiveRoomsIdEnd400,
  PostLiveRoomsIdEnd401,
  PostLiveRoomsIdEnd403,
  PostLiveRoomsIdEnd404,
  PostLiveRoomsIdHand200,
  PostLiveRoomsIdHand400,
  PostLiveRoomsIdHand401,
  PostLiveRoomsIdHand403,
  PostLiveRoomsIdHand404,
  PostLiveRoomsIdHeartbeat401,
  PostLiveRoomsIdHeartbeat403,
  PostLiveRoomsIdHeartbeat404,
  PostLiveRoomsIdJoin200,
  PostLiveRoomsIdJoin401,
  PostLiveRoomsIdJoin403,
  PostLiveRoomsIdJoin404,
  PostLiveRoomsIdLeave401,
  PostLiveRoomsIdLeave404,
  PostLiveRoomsIdParticipantsIdentityMute400,
  PostLiveRoomsIdParticipantsIdentityMute401,
  PostLiveRoomsIdParticipantsIdentityMute403,
  PostLiveRoomsIdParticipantsIdentityMute404,
  PostLiveRoomsIdRecordings201,
  PostLiveRoomsIdRecordings400,
  PostLiveRoomsIdRecordings401,
  PostLiveRoomsIdRecordings403,
  PostLiveRoomsIdRecordings404,
  PostLiveRoomsIdRecordingsRecordingIdStop200,
  PostLiveRoomsIdRecordingsRecordingIdStop400,
  PostLiveRoomsIdRecordingsRecordingIdStop401,
  PostLiveRoomsIdRecordingsRecordingIdStop403,
  PostLiveRoomsIdRecordingsRecordingIdStop404,
  PostLiveRoomsIdStart200,
  PostLiveRoomsIdStart400,
  PostLiveRoomsIdStart401,
  PostLiveRoomsIdStart403,
  PostLiveRoomsIdStart404,
  PutLiveRoomsIdConfig200,
  PutLiveRoomsIdConfig400,
  PutLiveRoomsIdConfig401,
  PutLiveRoomsIdConfig403,
  PutLiveRoomsIdConfig404,
  PutLiveRoomsIdParticipantsIdentityHand200,
  PutLiveRoomsIdParticipantsIdentityHand400,
  PutLiveRoomsIdParticipantsIdentityHand401,
  PutLiveRoomsIdParticipantsIdentityHand403,
  PutLiveRoomsIdParticipantsIdentityHand404,
  PutLiveRoomsIdParticipantsIdentityRole200,
  PutLiveRoomsIdParticipantsIdentityRole400,
  PutLiveRoomsIdParticipantsIdentityRole401,
  PutLiveRoomsIdParticipantsIdentityRole403,
  PutLiveRoomsIdParticipantsIdentityRole404,
  PutLiveRoomsIdWhiteboard200,
  PutLiveRoomsIdWhiteboard400,
  PutLiveRoomsIdWhiteboard401,
  PutLiveRoomsIdWhiteboard403,
  PutLiveRoomsIdWhiteboard404
} from '../model';

import { customInstance } from '.././mutator/custom-instance';
import type { ErrorType } from '.././mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getLiveRoomsResponse200 = {
  data: GetLiveRooms200
  status: 200
}

export type getLiveRoomsResponse401 = {
  data: GetLiveRooms401
  status: 401
}

export type getLiveRoomsResponse403 = {
  data: GetLiveRooms403
  status: 403
}

export type getLiveRoomsResponseSuccess = (getLiveRoomsResponse200) & {
  headers: Headers;
};
export type getLiveRoomsResponseError = (getLiveRoomsResponse401 | getLiveRoomsResponse403) & {
  headers: Headers;
};

export type getLiveRoomsResponse = (getLiveRoomsResponseSuccess | getLiveRoomsResponseError)

export const getGetLiveRoomsUrl = (params?: GetLiveRoomsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/live-rooms?${stringifiedParams}` : `/live-rooms`
}

/**
 * Returns rooms filtered by caller role: super-admins / livesessions:view_any see all, teachers see their classes' rooms, students see rooms in classes they are enrolled in. Orderable fields: created_at, updated_at, status, scheduled_start_time, actual_start_time, actual_end_time. Filters: status, class_id, class_session_id.
 * @summary List live rooms (scoped by RBAC)
 */
export const getLiveRooms = async (params?: GetLiveRoomsParams, options?: RequestInit): Promise<getLiveRoomsResponse> => {

  return customInstance<getLiveRoomsResponse>(getGetLiveRoomsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLiveRoomsQueryKey = (params?: GetLiveRoomsParams,) => {
    return [
    `/live-rooms`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLiveRoomsQueryOptions = <TData = Awaited<ReturnType<typeof getLiveRooms>>, TError = ErrorType<GetLiveRooms401 | GetLiveRooms403>>(params?: GetLiveRoomsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRooms>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLiveRoomsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLiveRooms>>> = ({ signal }) => getLiveRooms(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLiveRooms>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLiveRoomsQueryResult = NonNullable<Awaited<ReturnType<typeof getLiveRooms>>>
export type GetLiveRoomsQueryError = ErrorType<GetLiveRooms401 | GetLiveRooms403>


export function useGetLiveRooms<TData = Awaited<ReturnType<typeof getLiveRooms>>, TError = ErrorType<GetLiveRooms401 | GetLiveRooms403>>(
 params: undefined |  GetLiveRoomsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRooms>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiveRooms>>,
          TError,
          Awaited<ReturnType<typeof getLiveRooms>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLiveRooms<TData = Awaited<ReturnType<typeof getLiveRooms>>, TError = ErrorType<GetLiveRooms401 | GetLiveRooms403>>(
 params?: GetLiveRoomsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRooms>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiveRooms>>,
          TError,
          Awaited<ReturnType<typeof getLiveRooms>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLiveRooms<TData = Awaited<ReturnType<typeof getLiveRooms>>, TError = ErrorType<GetLiveRooms401 | GetLiveRooms403>>(
 params?: GetLiveRoomsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRooms>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List live rooms (scoped by RBAC)
 */

export function useGetLiveRooms<TData = Awaited<ReturnType<typeof getLiveRooms>>, TError = ErrorType<GetLiveRooms401 | GetLiveRooms403>>(
 params?: GetLiveRoomsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRooms>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLiveRoomsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postLiveRoomsResponse201 = {
  data: PostLiveRooms201
  status: 201
}

export type postLiveRoomsResponse400 = {
  data: PostLiveRooms400
  status: 400
}

export type postLiveRoomsResponse401 = {
  data: PostLiveRooms401
  status: 401
}

export type postLiveRoomsResponse403 = {
  data: PostLiveRooms403
  status: 403
}

export type postLiveRoomsResponse409 = {
  data: PostLiveRooms409
  status: 409
}

export type postLiveRoomsResponseSuccess = (postLiveRoomsResponse201) & {
  headers: Headers;
};
export type postLiveRoomsResponseError = (postLiveRoomsResponse400 | postLiveRoomsResponse401 | postLiveRoomsResponse403 | postLiveRoomsResponse409) & {
  headers: Headers;
};

export type postLiveRoomsResponse = (postLiveRoomsResponseSuccess | postLiveRoomsResponseError)

export const getPostLiveRoomsUrl = () => {




  return `/live-rooms`
}

/**
 * @summary Create live room
 */
export const postLiveRooms = async (githubCom4H1RZooraInternalDomainCreateLiveRoomDTO: GithubCom4H1RZooraInternalDomainCreateLiveRoomDTO, options?: RequestInit): Promise<postLiveRoomsResponse> => {

  return customInstance<postLiveRoomsResponse>(getPostLiveRoomsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainCreateLiveRoomDTO)
  }
);}




export const getPostLiveRoomsMutationOptions = <TError = ErrorType<PostLiveRooms400 | PostLiveRooms401 | PostLiveRooms403 | PostLiveRooms409>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRooms>>, TError,{data: GithubCom4H1RZooraInternalDomainCreateLiveRoomDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postLiveRooms>>, TError,{data: GithubCom4H1RZooraInternalDomainCreateLiveRoomDTO}, TContext> => {

const mutationKey = ['postLiveRooms'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLiveRooms>>, {data: GithubCom4H1RZooraInternalDomainCreateLiveRoomDTO}> = (props) => {
          const {data} = props ?? {};

          return  postLiveRooms(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLiveRoomsMutationResult = NonNullable<Awaited<ReturnType<typeof postLiveRooms>>>
    export type PostLiveRoomsMutationBody = GithubCom4H1RZooraInternalDomainCreateLiveRoomDTO
    export type PostLiveRoomsMutationError = ErrorType<PostLiveRooms400 | PostLiveRooms401 | PostLiveRooms403 | PostLiveRooms409>

    /**
 * @summary Create live room
 */
export const usePostLiveRooms = <TError = ErrorType<PostLiveRooms400 | PostLiveRooms401 | PostLiveRooms403 | PostLiveRooms409>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRooms>>, TError,{data: GithubCom4H1RZooraInternalDomainCreateLiveRoomDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLiveRooms>>,
        TError,
        {data: GithubCom4H1RZooraInternalDomainCreateLiveRoomDTO},
        TContext
      > => {
      return useMutation(getPostLiveRoomsMutationOptions(options), queryClient);
    }
    export type getLiveRoomsIdResponse200 = {
  data: GetLiveRoomsId200
  status: 200
}

export type getLiveRoomsIdResponse401 = {
  data: GetLiveRoomsId401
  status: 401
}

export type getLiveRoomsIdResponse403 = {
  data: GetLiveRoomsId403
  status: 403
}

export type getLiveRoomsIdResponse404 = {
  data: GetLiveRoomsId404
  status: 404
}

export type getLiveRoomsIdResponseSuccess = (getLiveRoomsIdResponse200) & {
  headers: Headers;
};
export type getLiveRoomsIdResponseError = (getLiveRoomsIdResponse401 | getLiveRoomsIdResponse403 | getLiveRoomsIdResponse404) & {
  headers: Headers;
};

export type getLiveRoomsIdResponse = (getLiveRoomsIdResponseSuccess | getLiveRoomsIdResponseError)

export const getGetLiveRoomsIdUrl = (id: string,) => {




  return `/live-rooms/${id}`
}

/**
 * @summary Get live room
 */
export const getLiveRoomsId = async (id: string, options?: RequestInit): Promise<getLiveRoomsIdResponse> => {

  return customInstance<getLiveRoomsIdResponse>(getGetLiveRoomsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLiveRoomsIdQueryKey = (id: string,) => {
    return [
    `/live-rooms/${id}`
    ] as const;
    }


export const getGetLiveRoomsIdQueryOptions = <TData = Awaited<ReturnType<typeof getLiveRoomsId>>, TError = ErrorType<GetLiveRoomsId401 | GetLiveRoomsId403 | GetLiveRoomsId404>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLiveRoomsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLiveRoomsId>>> = ({ signal }) => getLiveRoomsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLiveRoomsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getLiveRoomsId>>>
export type GetLiveRoomsIdQueryError = ErrorType<GetLiveRoomsId401 | GetLiveRoomsId403 | GetLiveRoomsId404>


export function useGetLiveRoomsId<TData = Awaited<ReturnType<typeof getLiveRoomsId>>, TError = ErrorType<GetLiveRoomsId401 | GetLiveRoomsId403 | GetLiveRoomsId404>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiveRoomsId>>,
          TError,
          Awaited<ReturnType<typeof getLiveRoomsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLiveRoomsId<TData = Awaited<ReturnType<typeof getLiveRoomsId>>, TError = ErrorType<GetLiveRoomsId401 | GetLiveRoomsId403 | GetLiveRoomsId404>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiveRoomsId>>,
          TError,
          Awaited<ReturnType<typeof getLiveRoomsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLiveRoomsId<TData = Awaited<ReturnType<typeof getLiveRoomsId>>, TError = ErrorType<GetLiveRoomsId401 | GetLiveRoomsId403 | GetLiveRoomsId404>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get live room
 */

export function useGetLiveRoomsId<TData = Awaited<ReturnType<typeof getLiveRoomsId>>, TError = ErrorType<GetLiveRoomsId401 | GetLiveRoomsId403 | GetLiveRoomsId404>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLiveRoomsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type putLiveRoomsIdConfigResponse200 = {
  data: PutLiveRoomsIdConfig200
  status: 200
}

export type putLiveRoomsIdConfigResponse400 = {
  data: PutLiveRoomsIdConfig400
  status: 400
}

export type putLiveRoomsIdConfigResponse401 = {
  data: PutLiveRoomsIdConfig401
  status: 401
}

export type putLiveRoomsIdConfigResponse403 = {
  data: PutLiveRoomsIdConfig403
  status: 403
}

export type putLiveRoomsIdConfigResponse404 = {
  data: PutLiveRoomsIdConfig404
  status: 404
}

export type putLiveRoomsIdConfigResponseSuccess = (putLiveRoomsIdConfigResponse200) & {
  headers: Headers;
};
export type putLiveRoomsIdConfigResponseError = (putLiveRoomsIdConfigResponse400 | putLiveRoomsIdConfigResponse401 | putLiveRoomsIdConfigResponse403 | putLiveRoomsIdConfigResponse404) & {
  headers: Headers;
};

export type putLiveRoomsIdConfigResponse = (putLiveRoomsIdConfigResponseSuccess | putLiveRoomsIdConfigResponseError)

export const getPutLiveRoomsIdConfigUrl = (id: string,) => {




  return `/live-rooms/${id}/config`
}

/**
 * @summary Update live room config
 */
export const putLiveRoomsIdConfig = async (id: string,
    githubCom4H1RZooraInternalDomainUpdateLiveRoomConfigDTO: GithubCom4H1RZooraInternalDomainUpdateLiveRoomConfigDTO, options?: RequestInit): Promise<putLiveRoomsIdConfigResponse> => {

  return customInstance<putLiveRoomsIdConfigResponse>(getPutLiveRoomsIdConfigUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainUpdateLiveRoomConfigDTO)
  }
);}




export const getPutLiveRoomsIdConfigMutationOptions = <TError = ErrorType<PutLiveRoomsIdConfig400 | PutLiveRoomsIdConfig401 | PutLiveRoomsIdConfig403 | PutLiveRoomsIdConfig404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putLiveRoomsIdConfig>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainUpdateLiveRoomConfigDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putLiveRoomsIdConfig>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainUpdateLiveRoomConfigDTO}, TContext> => {

const mutationKey = ['putLiveRoomsIdConfig'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putLiveRoomsIdConfig>>, {id: string;data: GithubCom4H1RZooraInternalDomainUpdateLiveRoomConfigDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  putLiveRoomsIdConfig(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutLiveRoomsIdConfigMutationResult = NonNullable<Awaited<ReturnType<typeof putLiveRoomsIdConfig>>>
    export type PutLiveRoomsIdConfigMutationBody = GithubCom4H1RZooraInternalDomainUpdateLiveRoomConfigDTO
    export type PutLiveRoomsIdConfigMutationError = ErrorType<PutLiveRoomsIdConfig400 | PutLiveRoomsIdConfig401 | PutLiveRoomsIdConfig403 | PutLiveRoomsIdConfig404>

    /**
 * @summary Update live room config
 */
export const usePutLiveRoomsIdConfig = <TError = ErrorType<PutLiveRoomsIdConfig400 | PutLiveRoomsIdConfig401 | PutLiveRoomsIdConfig403 | PutLiveRoomsIdConfig404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putLiveRoomsIdConfig>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainUpdateLiveRoomConfigDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putLiveRoomsIdConfig>>,
        TError,
        {id: string;data: GithubCom4H1RZooraInternalDomainUpdateLiveRoomConfigDTO},
        TContext
      > => {
      return useMutation(getPutLiveRoomsIdConfigMutationOptions(options), queryClient);
    }
    export type postLiveRoomsIdEndResponse200 = {
  data: PostLiveRoomsIdEnd200
  status: 200
}

export type postLiveRoomsIdEndResponse400 = {
  data: PostLiveRoomsIdEnd400
  status: 400
}

export type postLiveRoomsIdEndResponse401 = {
  data: PostLiveRoomsIdEnd401
  status: 401
}

export type postLiveRoomsIdEndResponse403 = {
  data: PostLiveRoomsIdEnd403
  status: 403
}

export type postLiveRoomsIdEndResponse404 = {
  data: PostLiveRoomsIdEnd404
  status: 404
}

export type postLiveRoomsIdEndResponseSuccess = (postLiveRoomsIdEndResponse200) & {
  headers: Headers;
};
export type postLiveRoomsIdEndResponseError = (postLiveRoomsIdEndResponse400 | postLiveRoomsIdEndResponse401 | postLiveRoomsIdEndResponse403 | postLiveRoomsIdEndResponse404) & {
  headers: Headers;
};

export type postLiveRoomsIdEndResponse = (postLiveRoomsIdEndResponseSuccess | postLiveRoomsIdEndResponseError)

export const getPostLiveRoomsIdEndUrl = (id: string,) => {




  return `/live-rooms/${id}/end`
}

/**
 * @summary End live room
 */
export const postLiveRoomsIdEnd = async (id: string, options?: RequestInit): Promise<postLiveRoomsIdEndResponse> => {

  return customInstance<postLiveRoomsIdEndResponse>(getPostLiveRoomsIdEndUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostLiveRoomsIdEndMutationOptions = <TError = ErrorType<PostLiveRoomsIdEnd400 | PostLiveRoomsIdEnd401 | PostLiveRoomsIdEnd403 | PostLiveRoomsIdEnd404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdEnd>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdEnd>>, TError,{id: string}, TContext> => {

const mutationKey = ['postLiveRoomsIdEnd'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLiveRoomsIdEnd>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postLiveRoomsIdEnd(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLiveRoomsIdEndMutationResult = NonNullable<Awaited<ReturnType<typeof postLiveRoomsIdEnd>>>

    export type PostLiveRoomsIdEndMutationError = ErrorType<PostLiveRoomsIdEnd400 | PostLiveRoomsIdEnd401 | PostLiveRoomsIdEnd403 | PostLiveRoomsIdEnd404>

    /**
 * @summary End live room
 */
export const usePostLiveRoomsIdEnd = <TError = ErrorType<PostLiveRoomsIdEnd400 | PostLiveRoomsIdEnd401 | PostLiveRoomsIdEnd403 | PostLiveRoomsIdEnd404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdEnd>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLiveRoomsIdEnd>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPostLiveRoomsIdEndMutationOptions(options), queryClient);
    }
    export type postLiveRoomsIdHandResponse200 = {
  data: PostLiveRoomsIdHand200
  status: 200
}

export type postLiveRoomsIdHandResponse400 = {
  data: PostLiveRoomsIdHand400
  status: 400
}

export type postLiveRoomsIdHandResponse401 = {
  data: PostLiveRoomsIdHand401
  status: 401
}

export type postLiveRoomsIdHandResponse403 = {
  data: PostLiveRoomsIdHand403
  status: 403
}

export type postLiveRoomsIdHandResponse404 = {
  data: PostLiveRoomsIdHand404
  status: 404
}

export type postLiveRoomsIdHandResponseSuccess = (postLiveRoomsIdHandResponse200) & {
  headers: Headers;
};
export type postLiveRoomsIdHandResponseError = (postLiveRoomsIdHandResponse400 | postLiveRoomsIdHandResponse401 | postLiveRoomsIdHandResponse403 | postLiveRoomsIdHandResponse404) & {
  headers: Headers;
};

export type postLiveRoomsIdHandResponse = (postLiveRoomsIdHandResponseSuccess | postLiveRoomsIdHandResponseError)

export const getPostLiveRoomsIdHandUrl = (id: string,) => {




  return `/live-rooms/${id}/hand`
}

/**
 * @summary Set hand raised
 */
export const postLiveRoomsIdHand = async (id: string,
    githubCom4H1RZooraInternalDomainSetHandDTO: GithubCom4H1RZooraInternalDomainSetHandDTO, options?: RequestInit): Promise<postLiveRoomsIdHandResponse> => {

  return customInstance<postLiveRoomsIdHandResponse>(getPostLiveRoomsIdHandUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainSetHandDTO)
  }
);}




export const getPostLiveRoomsIdHandMutationOptions = <TError = ErrorType<PostLiveRoomsIdHand400 | PostLiveRoomsIdHand401 | PostLiveRoomsIdHand403 | PostLiveRoomsIdHand404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdHand>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainSetHandDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdHand>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainSetHandDTO}, TContext> => {

const mutationKey = ['postLiveRoomsIdHand'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLiveRoomsIdHand>>, {id: string;data: GithubCom4H1RZooraInternalDomainSetHandDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  postLiveRoomsIdHand(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLiveRoomsIdHandMutationResult = NonNullable<Awaited<ReturnType<typeof postLiveRoomsIdHand>>>
    export type PostLiveRoomsIdHandMutationBody = GithubCom4H1RZooraInternalDomainSetHandDTO
    export type PostLiveRoomsIdHandMutationError = ErrorType<PostLiveRoomsIdHand400 | PostLiveRoomsIdHand401 | PostLiveRoomsIdHand403 | PostLiveRoomsIdHand404>

    /**
 * @summary Set hand raised
 */
export const usePostLiveRoomsIdHand = <TError = ErrorType<PostLiveRoomsIdHand400 | PostLiveRoomsIdHand401 | PostLiveRoomsIdHand403 | PostLiveRoomsIdHand404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdHand>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainSetHandDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLiveRoomsIdHand>>,
        TError,
        {id: string;data: GithubCom4H1RZooraInternalDomainSetHandDTO},
        TContext
      > => {
      return useMutation(getPostLiveRoomsIdHandMutationOptions(options), queryClient);
    }
    export type postLiveRoomsIdHeartbeatResponse200 = {
  data: GithubCom4H1RZooraInternalDomainResponse
  status: 200
}

export type postLiveRoomsIdHeartbeatResponse401 = {
  data: PostLiveRoomsIdHeartbeat401
  status: 401
}

export type postLiveRoomsIdHeartbeatResponse403 = {
  data: PostLiveRoomsIdHeartbeat403
  status: 403
}

export type postLiveRoomsIdHeartbeatResponse404 = {
  data: PostLiveRoomsIdHeartbeat404
  status: 404
}

export type postLiveRoomsIdHeartbeatResponseSuccess = (postLiveRoomsIdHeartbeatResponse200) & {
  headers: Headers;
};
export type postLiveRoomsIdHeartbeatResponseError = (postLiveRoomsIdHeartbeatResponse401 | postLiveRoomsIdHeartbeatResponse403 | postLiveRoomsIdHeartbeatResponse404) & {
  headers: Headers;
};

export type postLiveRoomsIdHeartbeatResponse = (postLiveRoomsIdHeartbeatResponseSuccess | postLiveRoomsIdHeartbeatResponseError)

export const getPostLiveRoomsIdHeartbeatUrl = (id: string,) => {




  return `/live-rooms/${id}/heartbeat`
}

/**
 * @summary Heartbeat for live room
 */
export const postLiveRoomsIdHeartbeat = async (id: string, options?: RequestInit): Promise<postLiveRoomsIdHeartbeatResponse> => {

  return customInstance<postLiveRoomsIdHeartbeatResponse>(getPostLiveRoomsIdHeartbeatUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostLiveRoomsIdHeartbeatMutationOptions = <TError = ErrorType<PostLiveRoomsIdHeartbeat401 | PostLiveRoomsIdHeartbeat403 | PostLiveRoomsIdHeartbeat404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdHeartbeat>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdHeartbeat>>, TError,{id: string}, TContext> => {

const mutationKey = ['postLiveRoomsIdHeartbeat'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLiveRoomsIdHeartbeat>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postLiveRoomsIdHeartbeat(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLiveRoomsIdHeartbeatMutationResult = NonNullable<Awaited<ReturnType<typeof postLiveRoomsIdHeartbeat>>>

    export type PostLiveRoomsIdHeartbeatMutationError = ErrorType<PostLiveRoomsIdHeartbeat401 | PostLiveRoomsIdHeartbeat403 | PostLiveRoomsIdHeartbeat404>

    /**
 * @summary Heartbeat for live room
 */
export const usePostLiveRoomsIdHeartbeat = <TError = ErrorType<PostLiveRoomsIdHeartbeat401 | PostLiveRoomsIdHeartbeat403 | PostLiveRoomsIdHeartbeat404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdHeartbeat>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLiveRoomsIdHeartbeat>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPostLiveRoomsIdHeartbeatMutationOptions(options), queryClient);
    }
    export type postLiveRoomsIdJoinResponse200 = {
  data: PostLiveRoomsIdJoin200
  status: 200
}

export type postLiveRoomsIdJoinResponse401 = {
  data: PostLiveRoomsIdJoin401
  status: 401
}

export type postLiveRoomsIdJoinResponse403 = {
  data: PostLiveRoomsIdJoin403
  status: 403
}

export type postLiveRoomsIdJoinResponse404 = {
  data: PostLiveRoomsIdJoin404
  status: 404
}

export type postLiveRoomsIdJoinResponseSuccess = (postLiveRoomsIdJoinResponse200) & {
  headers: Headers;
};
export type postLiveRoomsIdJoinResponseError = (postLiveRoomsIdJoinResponse401 | postLiveRoomsIdJoinResponse403 | postLiveRoomsIdJoinResponse404) & {
  headers: Headers;
};

export type postLiveRoomsIdJoinResponse = (postLiveRoomsIdJoinResponseSuccess | postLiveRoomsIdJoinResponseError)

export const getPostLiveRoomsIdJoinUrl = (id: string,) => {




  return `/live-rooms/${id}/join`
}

/**
 * @summary Join live room
 */
export const postLiveRoomsIdJoin = async (id: string, options?: RequestInit): Promise<postLiveRoomsIdJoinResponse> => {

  return customInstance<postLiveRoomsIdJoinResponse>(getPostLiveRoomsIdJoinUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostLiveRoomsIdJoinMutationOptions = <TError = ErrorType<PostLiveRoomsIdJoin401 | PostLiveRoomsIdJoin403 | PostLiveRoomsIdJoin404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdJoin>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdJoin>>, TError,{id: string}, TContext> => {

const mutationKey = ['postLiveRoomsIdJoin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLiveRoomsIdJoin>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postLiveRoomsIdJoin(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLiveRoomsIdJoinMutationResult = NonNullable<Awaited<ReturnType<typeof postLiveRoomsIdJoin>>>

    export type PostLiveRoomsIdJoinMutationError = ErrorType<PostLiveRoomsIdJoin401 | PostLiveRoomsIdJoin403 | PostLiveRoomsIdJoin404>

    /**
 * @summary Join live room
 */
export const usePostLiveRoomsIdJoin = <TError = ErrorType<PostLiveRoomsIdJoin401 | PostLiveRoomsIdJoin403 | PostLiveRoomsIdJoin404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdJoin>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLiveRoomsIdJoin>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPostLiveRoomsIdJoinMutationOptions(options), queryClient);
    }
    export type postLiveRoomsIdLeaveResponse200 = {
  data: GithubCom4H1RZooraInternalDomainResponse
  status: 200
}

export type postLiveRoomsIdLeaveResponse401 = {
  data: PostLiveRoomsIdLeave401
  status: 401
}

export type postLiveRoomsIdLeaveResponse404 = {
  data: PostLiveRoomsIdLeave404
  status: 404
}

export type postLiveRoomsIdLeaveResponseSuccess = (postLiveRoomsIdLeaveResponse200) & {
  headers: Headers;
};
export type postLiveRoomsIdLeaveResponseError = (postLiveRoomsIdLeaveResponse401 | postLiveRoomsIdLeaveResponse404) & {
  headers: Headers;
};

export type postLiveRoomsIdLeaveResponse = (postLiveRoomsIdLeaveResponseSuccess | postLiveRoomsIdLeaveResponseError)

export const getPostLiveRoomsIdLeaveUrl = (id: string,) => {




  return `/live-rooms/${id}/leave`
}

/**
 * @summary Leave live room
 */
export const postLiveRoomsIdLeave = async (id: string, options?: RequestInit): Promise<postLiveRoomsIdLeaveResponse> => {

  return customInstance<postLiveRoomsIdLeaveResponse>(getPostLiveRoomsIdLeaveUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostLiveRoomsIdLeaveMutationOptions = <TError = ErrorType<PostLiveRoomsIdLeave401 | PostLiveRoomsIdLeave404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdLeave>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdLeave>>, TError,{id: string}, TContext> => {

const mutationKey = ['postLiveRoomsIdLeave'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLiveRoomsIdLeave>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postLiveRoomsIdLeave(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLiveRoomsIdLeaveMutationResult = NonNullable<Awaited<ReturnType<typeof postLiveRoomsIdLeave>>>

    export type PostLiveRoomsIdLeaveMutationError = ErrorType<PostLiveRoomsIdLeave401 | PostLiveRoomsIdLeave404>

    /**
 * @summary Leave live room
 */
export const usePostLiveRoomsIdLeave = <TError = ErrorType<PostLiveRoomsIdLeave401 | PostLiveRoomsIdLeave404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdLeave>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLiveRoomsIdLeave>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPostLiveRoomsIdLeaveMutationOptions(options), queryClient);
    }
    export type getLiveRoomsIdParticipantsResponse200 = {
  data: GetLiveRoomsIdParticipants200
  status: 200
}

export type getLiveRoomsIdParticipantsResponse401 = {
  data: GetLiveRoomsIdParticipants401
  status: 401
}

export type getLiveRoomsIdParticipantsResponse403 = {
  data: GetLiveRoomsIdParticipants403
  status: 403
}

export type getLiveRoomsIdParticipantsResponse404 = {
  data: GetLiveRoomsIdParticipants404
  status: 404
}

export type getLiveRoomsIdParticipantsResponseSuccess = (getLiveRoomsIdParticipantsResponse200) & {
  headers: Headers;
};
export type getLiveRoomsIdParticipantsResponseError = (getLiveRoomsIdParticipantsResponse401 | getLiveRoomsIdParticipantsResponse403 | getLiveRoomsIdParticipantsResponse404) & {
  headers: Headers;
};

export type getLiveRoomsIdParticipantsResponse = (getLiveRoomsIdParticipantsResponseSuccess | getLiveRoomsIdParticipantsResponseError)

export const getGetLiveRoomsIdParticipantsUrl = (id: string,
    params?: GetLiveRoomsIdParticipantsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/live-rooms/${id}/participants?${stringifiedParams}` : `/live-rooms/${id}/participants`
}

/**
 * Search matches substrings of: identity. Orderable fields: joined_at, left_at, created_at, total_duration_seconds. Filters: active_only, user_id.
 * @summary List live room participants
 */
export const getLiveRoomsIdParticipants = async (id: string,
    params?: GetLiveRoomsIdParticipantsParams, options?: RequestInit): Promise<getLiveRoomsIdParticipantsResponse> => {

  return customInstance<getLiveRoomsIdParticipantsResponse>(getGetLiveRoomsIdParticipantsUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLiveRoomsIdParticipantsQueryKey = (id: string,
    params?: GetLiveRoomsIdParticipantsParams,) => {
    return [
    `/live-rooms/${id}/participants`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLiveRoomsIdParticipantsQueryOptions = <TData = Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>, TError = ErrorType<GetLiveRoomsIdParticipants401 | GetLiveRoomsIdParticipants403 | GetLiveRoomsIdParticipants404>>(id: string,
    params?: GetLiveRoomsIdParticipantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLiveRoomsIdParticipantsQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>> = ({ signal }) => getLiveRoomsIdParticipants(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLiveRoomsIdParticipantsQueryResult = NonNullable<Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>>
export type GetLiveRoomsIdParticipantsQueryError = ErrorType<GetLiveRoomsIdParticipants401 | GetLiveRoomsIdParticipants403 | GetLiveRoomsIdParticipants404>


export function useGetLiveRoomsIdParticipants<TData = Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>, TError = ErrorType<GetLiveRoomsIdParticipants401 | GetLiveRoomsIdParticipants403 | GetLiveRoomsIdParticipants404>>(
 id: string,
    params: undefined |  GetLiveRoomsIdParticipantsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>,
          TError,
          Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLiveRoomsIdParticipants<TData = Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>, TError = ErrorType<GetLiveRoomsIdParticipants401 | GetLiveRoomsIdParticipants403 | GetLiveRoomsIdParticipants404>>(
 id: string,
    params?: GetLiveRoomsIdParticipantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>,
          TError,
          Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLiveRoomsIdParticipants<TData = Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>, TError = ErrorType<GetLiveRoomsIdParticipants401 | GetLiveRoomsIdParticipants403 | GetLiveRoomsIdParticipants404>>(
 id: string,
    params?: GetLiveRoomsIdParticipantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List live room participants
 */

export function useGetLiveRoomsIdParticipants<TData = Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>, TError = ErrorType<GetLiveRoomsIdParticipants401 | GetLiveRoomsIdParticipants403 | GetLiveRoomsIdParticipants404>>(
 id: string,
    params?: GetLiveRoomsIdParticipantsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdParticipants>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLiveRoomsIdParticipantsQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteLiveRoomsIdParticipantsIdentityResponse200 = {
  data: GithubCom4H1RZooraInternalDomainResponse
  status: 200
}

export type deleteLiveRoomsIdParticipantsIdentityResponse401 = {
  data: DeleteLiveRoomsIdParticipantsIdentity401
  status: 401
}

export type deleteLiveRoomsIdParticipantsIdentityResponse403 = {
  data: DeleteLiveRoomsIdParticipantsIdentity403
  status: 403
}

export type deleteLiveRoomsIdParticipantsIdentityResponse404 = {
  data: DeleteLiveRoomsIdParticipantsIdentity404
  status: 404
}

export type deleteLiveRoomsIdParticipantsIdentityResponse409 = {
  data: DeleteLiveRoomsIdParticipantsIdentity409
  status: 409
}

export type deleteLiveRoomsIdParticipantsIdentityResponseSuccess = (deleteLiveRoomsIdParticipantsIdentityResponse200) & {
  headers: Headers;
};
export type deleteLiveRoomsIdParticipantsIdentityResponseError = (deleteLiveRoomsIdParticipantsIdentityResponse401 | deleteLiveRoomsIdParticipantsIdentityResponse403 | deleteLiveRoomsIdParticipantsIdentityResponse404 | deleteLiveRoomsIdParticipantsIdentityResponse409) & {
  headers: Headers;
};

export type deleteLiveRoomsIdParticipantsIdentityResponse = (deleteLiveRoomsIdParticipantsIdentityResponseSuccess | deleteLiveRoomsIdParticipantsIdentityResponseError)

export const getDeleteLiveRoomsIdParticipantsIdentityUrl = (id: string,
    identity: string,) => {




  return `/live-rooms/${id}/participants/${identity}`
}

/**
 * Host-only. Ejects a participant from the room. A host cannot remove another host or themselves.
 * @summary Remove participant
 */
export const deleteLiveRoomsIdParticipantsIdentity = async (id: string,
    identity: string, options?: RequestInit): Promise<deleteLiveRoomsIdParticipantsIdentityResponse> => {

  return customInstance<deleteLiveRoomsIdParticipantsIdentityResponse>(getDeleteLiveRoomsIdParticipantsIdentityUrl(id,identity),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteLiveRoomsIdParticipantsIdentityMutationOptions = <TError = ErrorType<DeleteLiveRoomsIdParticipantsIdentity401 | DeleteLiveRoomsIdParticipantsIdentity403 | DeleteLiveRoomsIdParticipantsIdentity404 | DeleteLiveRoomsIdParticipantsIdentity409>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLiveRoomsIdParticipantsIdentity>>, TError,{id: string;identity: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteLiveRoomsIdParticipantsIdentity>>, TError,{id: string;identity: string}, TContext> => {

const mutationKey = ['deleteLiveRoomsIdParticipantsIdentity'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteLiveRoomsIdParticipantsIdentity>>, {id: string;identity: string}> = (props) => {
          const {id,identity} = props ?? {};

          return  deleteLiveRoomsIdParticipantsIdentity(id,identity,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteLiveRoomsIdParticipantsIdentityMutationResult = NonNullable<Awaited<ReturnType<typeof deleteLiveRoomsIdParticipantsIdentity>>>

    export type DeleteLiveRoomsIdParticipantsIdentityMutationError = ErrorType<DeleteLiveRoomsIdParticipantsIdentity401 | DeleteLiveRoomsIdParticipantsIdentity403 | DeleteLiveRoomsIdParticipantsIdentity404 | DeleteLiveRoomsIdParticipantsIdentity409>

    /**
 * @summary Remove participant
 */
export const useDeleteLiveRoomsIdParticipantsIdentity = <TError = ErrorType<DeleteLiveRoomsIdParticipantsIdentity401 | DeleteLiveRoomsIdParticipantsIdentity403 | DeleteLiveRoomsIdParticipantsIdentity404 | DeleteLiveRoomsIdParticipantsIdentity409>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteLiveRoomsIdParticipantsIdentity>>, TError,{id: string;identity: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteLiveRoomsIdParticipantsIdentity>>,
        TError,
        {id: string;identity: string},
        TContext
      > => {
      return useMutation(getDeleteLiveRoomsIdParticipantsIdentityMutationOptions(options), queryClient);
    }
    export type putLiveRoomsIdParticipantsIdentityHandResponse200 = {
  data: PutLiveRoomsIdParticipantsIdentityHand200
  status: 200
}

export type putLiveRoomsIdParticipantsIdentityHandResponse400 = {
  data: PutLiveRoomsIdParticipantsIdentityHand400
  status: 400
}

export type putLiveRoomsIdParticipantsIdentityHandResponse401 = {
  data: PutLiveRoomsIdParticipantsIdentityHand401
  status: 401
}

export type putLiveRoomsIdParticipantsIdentityHandResponse403 = {
  data: PutLiveRoomsIdParticipantsIdentityHand403
  status: 403
}

export type putLiveRoomsIdParticipantsIdentityHandResponse404 = {
  data: PutLiveRoomsIdParticipantsIdentityHand404
  status: 404
}

export type putLiveRoomsIdParticipantsIdentityHandResponseSuccess = (putLiveRoomsIdParticipantsIdentityHandResponse200) & {
  headers: Headers;
};
export type putLiveRoomsIdParticipantsIdentityHandResponseError = (putLiveRoomsIdParticipantsIdentityHandResponse400 | putLiveRoomsIdParticipantsIdentityHandResponse401 | putLiveRoomsIdParticipantsIdentityHandResponse403 | putLiveRoomsIdParticipantsIdentityHandResponse404) & {
  headers: Headers;
};

export type putLiveRoomsIdParticipantsIdentityHandResponse = (putLiveRoomsIdParticipantsIdentityHandResponseSuccess | putLiveRoomsIdParticipantsIdentityHandResponseError)

export const getPutLiveRoomsIdParticipantsIdentityHandUrl = (id: string,
    identity: string,) => {




  return `/live-rooms/${id}/participants/${identity}/hand`
}

/**
 * @summary Set participant hand
 */
export const putLiveRoomsIdParticipantsIdentityHand = async (id: string,
    identity: string,
    githubCom4H1RZooraInternalDomainSetHandDTO: GithubCom4H1RZooraInternalDomainSetHandDTO, options?: RequestInit): Promise<putLiveRoomsIdParticipantsIdentityHandResponse> => {

  return customInstance<putLiveRoomsIdParticipantsIdentityHandResponse>(getPutLiveRoomsIdParticipantsIdentityHandUrl(id,identity),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainSetHandDTO)
  }
);}




export const getPutLiveRoomsIdParticipantsIdentityHandMutationOptions = <TError = ErrorType<PutLiveRoomsIdParticipantsIdentityHand400 | PutLiveRoomsIdParticipantsIdentityHand401 | PutLiveRoomsIdParticipantsIdentityHand403 | PutLiveRoomsIdParticipantsIdentityHand404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putLiveRoomsIdParticipantsIdentityHand>>, TError,{id: string;identity: string;data: GithubCom4H1RZooraInternalDomainSetHandDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putLiveRoomsIdParticipantsIdentityHand>>, TError,{id: string;identity: string;data: GithubCom4H1RZooraInternalDomainSetHandDTO}, TContext> => {

const mutationKey = ['putLiveRoomsIdParticipantsIdentityHand'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putLiveRoomsIdParticipantsIdentityHand>>, {id: string;identity: string;data: GithubCom4H1RZooraInternalDomainSetHandDTO}> = (props) => {
          const {id,identity,data} = props ?? {};

          return  putLiveRoomsIdParticipantsIdentityHand(id,identity,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutLiveRoomsIdParticipantsIdentityHandMutationResult = NonNullable<Awaited<ReturnType<typeof putLiveRoomsIdParticipantsIdentityHand>>>
    export type PutLiveRoomsIdParticipantsIdentityHandMutationBody = GithubCom4H1RZooraInternalDomainSetHandDTO
    export type PutLiveRoomsIdParticipantsIdentityHandMutationError = ErrorType<PutLiveRoomsIdParticipantsIdentityHand400 | PutLiveRoomsIdParticipantsIdentityHand401 | PutLiveRoomsIdParticipantsIdentityHand403 | PutLiveRoomsIdParticipantsIdentityHand404>

    /**
 * @summary Set participant hand
 */
export const usePutLiveRoomsIdParticipantsIdentityHand = <TError = ErrorType<PutLiveRoomsIdParticipantsIdentityHand400 | PutLiveRoomsIdParticipantsIdentityHand401 | PutLiveRoomsIdParticipantsIdentityHand403 | PutLiveRoomsIdParticipantsIdentityHand404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putLiveRoomsIdParticipantsIdentityHand>>, TError,{id: string;identity: string;data: GithubCom4H1RZooraInternalDomainSetHandDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putLiveRoomsIdParticipantsIdentityHand>>,
        TError,
        {id: string;identity: string;data: GithubCom4H1RZooraInternalDomainSetHandDTO},
        TContext
      > => {
      return useMutation(getPutLiveRoomsIdParticipantsIdentityHandMutationOptions(options), queryClient);
    }
    export type postLiveRoomsIdParticipantsIdentityMuteResponse200 = {
  data: GithubCom4H1RZooraInternalDomainResponse
  status: 200
}

export type postLiveRoomsIdParticipantsIdentityMuteResponse400 = {
  data: PostLiveRoomsIdParticipantsIdentityMute400
  status: 400
}

export type postLiveRoomsIdParticipantsIdentityMuteResponse401 = {
  data: PostLiveRoomsIdParticipantsIdentityMute401
  status: 401
}

export type postLiveRoomsIdParticipantsIdentityMuteResponse403 = {
  data: PostLiveRoomsIdParticipantsIdentityMute403
  status: 403
}

export type postLiveRoomsIdParticipantsIdentityMuteResponse404 = {
  data: PostLiveRoomsIdParticipantsIdentityMute404
  status: 404
}

export type postLiveRoomsIdParticipantsIdentityMuteResponseSuccess = (postLiveRoomsIdParticipantsIdentityMuteResponse200) & {
  headers: Headers;
};
export type postLiveRoomsIdParticipantsIdentityMuteResponseError = (postLiveRoomsIdParticipantsIdentityMuteResponse400 | postLiveRoomsIdParticipantsIdentityMuteResponse401 | postLiveRoomsIdParticipantsIdentityMuteResponse403 | postLiveRoomsIdParticipantsIdentityMuteResponse404) & {
  headers: Headers;
};

export type postLiveRoomsIdParticipantsIdentityMuteResponse = (postLiveRoomsIdParticipantsIdentityMuteResponseSuccess | postLiveRoomsIdParticipantsIdentityMuteResponseError)

export const getPostLiveRoomsIdParticipantsIdentityMuteUrl = (id: string,
    identity: string,) => {




  return `/live-rooms/${id}/participants/${identity}/mute`
}

/**
 * @summary Mute participant
 */
export const postLiveRoomsIdParticipantsIdentityMute = async (id: string,
    identity: string,
    githubCom4H1RZooraInternalDomainMuteParticipantDTO: GithubCom4H1RZooraInternalDomainMuteParticipantDTO, options?: RequestInit): Promise<postLiveRoomsIdParticipantsIdentityMuteResponse> => {

  return customInstance<postLiveRoomsIdParticipantsIdentityMuteResponse>(getPostLiveRoomsIdParticipantsIdentityMuteUrl(id,identity),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainMuteParticipantDTO)
  }
);}




export const getPostLiveRoomsIdParticipantsIdentityMuteMutationOptions = <TError = ErrorType<PostLiveRoomsIdParticipantsIdentityMute400 | PostLiveRoomsIdParticipantsIdentityMute401 | PostLiveRoomsIdParticipantsIdentityMute403 | PostLiveRoomsIdParticipantsIdentityMute404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdParticipantsIdentityMute>>, TError,{id: string;identity: string;data: GithubCom4H1RZooraInternalDomainMuteParticipantDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdParticipantsIdentityMute>>, TError,{id: string;identity: string;data: GithubCom4H1RZooraInternalDomainMuteParticipantDTO}, TContext> => {

const mutationKey = ['postLiveRoomsIdParticipantsIdentityMute'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLiveRoomsIdParticipantsIdentityMute>>, {id: string;identity: string;data: GithubCom4H1RZooraInternalDomainMuteParticipantDTO}> = (props) => {
          const {id,identity,data} = props ?? {};

          return  postLiveRoomsIdParticipantsIdentityMute(id,identity,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLiveRoomsIdParticipantsIdentityMuteMutationResult = NonNullable<Awaited<ReturnType<typeof postLiveRoomsIdParticipantsIdentityMute>>>
    export type PostLiveRoomsIdParticipantsIdentityMuteMutationBody = GithubCom4H1RZooraInternalDomainMuteParticipantDTO
    export type PostLiveRoomsIdParticipantsIdentityMuteMutationError = ErrorType<PostLiveRoomsIdParticipantsIdentityMute400 | PostLiveRoomsIdParticipantsIdentityMute401 | PostLiveRoomsIdParticipantsIdentityMute403 | PostLiveRoomsIdParticipantsIdentityMute404>

    /**
 * @summary Mute participant
 */
export const usePostLiveRoomsIdParticipantsIdentityMute = <TError = ErrorType<PostLiveRoomsIdParticipantsIdentityMute400 | PostLiveRoomsIdParticipantsIdentityMute401 | PostLiveRoomsIdParticipantsIdentityMute403 | PostLiveRoomsIdParticipantsIdentityMute404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdParticipantsIdentityMute>>, TError,{id: string;identity: string;data: GithubCom4H1RZooraInternalDomainMuteParticipantDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLiveRoomsIdParticipantsIdentityMute>>,
        TError,
        {id: string;identity: string;data: GithubCom4H1RZooraInternalDomainMuteParticipantDTO},
        TContext
      > => {
      return useMutation(getPostLiveRoomsIdParticipantsIdentityMuteMutationOptions(options), queryClient);
    }
    export type putLiveRoomsIdParticipantsIdentityRoleResponse200 = {
  data: PutLiveRoomsIdParticipantsIdentityRole200
  status: 200
}

export type putLiveRoomsIdParticipantsIdentityRoleResponse400 = {
  data: PutLiveRoomsIdParticipantsIdentityRole400
  status: 400
}

export type putLiveRoomsIdParticipantsIdentityRoleResponse401 = {
  data: PutLiveRoomsIdParticipantsIdentityRole401
  status: 401
}

export type putLiveRoomsIdParticipantsIdentityRoleResponse403 = {
  data: PutLiveRoomsIdParticipantsIdentityRole403
  status: 403
}

export type putLiveRoomsIdParticipantsIdentityRoleResponse404 = {
  data: PutLiveRoomsIdParticipantsIdentityRole404
  status: 404
}

export type putLiveRoomsIdParticipantsIdentityRoleResponseSuccess = (putLiveRoomsIdParticipantsIdentityRoleResponse200) & {
  headers: Headers;
};
export type putLiveRoomsIdParticipantsIdentityRoleResponseError = (putLiveRoomsIdParticipantsIdentityRoleResponse400 | putLiveRoomsIdParticipantsIdentityRoleResponse401 | putLiveRoomsIdParticipantsIdentityRoleResponse403 | putLiveRoomsIdParticipantsIdentityRoleResponse404) & {
  headers: Headers;
};

export type putLiveRoomsIdParticipantsIdentityRoleResponse = (putLiveRoomsIdParticipantsIdentityRoleResponseSuccess | putLiveRoomsIdParticipantsIdentityRoleResponseError)

export const getPutLiveRoomsIdParticipantsIdentityRoleUrl = (id: string,
    identity: string,) => {




  return `/live-rooms/${id}/participants/${identity}/role`
}

/**
 * @summary Set participant role
 */
export const putLiveRoomsIdParticipantsIdentityRole = async (id: string,
    identity: string,
    githubCom4H1RZooraInternalDomainSetParticipantRoleDTO: GithubCom4H1RZooraInternalDomainSetParticipantRoleDTO, options?: RequestInit): Promise<putLiveRoomsIdParticipantsIdentityRoleResponse> => {

  return customInstance<putLiveRoomsIdParticipantsIdentityRoleResponse>(getPutLiveRoomsIdParticipantsIdentityRoleUrl(id,identity),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainSetParticipantRoleDTO)
  }
);}




export const getPutLiveRoomsIdParticipantsIdentityRoleMutationOptions = <TError = ErrorType<PutLiveRoomsIdParticipantsIdentityRole400 | PutLiveRoomsIdParticipantsIdentityRole401 | PutLiveRoomsIdParticipantsIdentityRole403 | PutLiveRoomsIdParticipantsIdentityRole404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putLiveRoomsIdParticipantsIdentityRole>>, TError,{id: string;identity: string;data: GithubCom4H1RZooraInternalDomainSetParticipantRoleDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putLiveRoomsIdParticipantsIdentityRole>>, TError,{id: string;identity: string;data: GithubCom4H1RZooraInternalDomainSetParticipantRoleDTO}, TContext> => {

const mutationKey = ['putLiveRoomsIdParticipantsIdentityRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putLiveRoomsIdParticipantsIdentityRole>>, {id: string;identity: string;data: GithubCom4H1RZooraInternalDomainSetParticipantRoleDTO}> = (props) => {
          const {id,identity,data} = props ?? {};

          return  putLiveRoomsIdParticipantsIdentityRole(id,identity,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutLiveRoomsIdParticipantsIdentityRoleMutationResult = NonNullable<Awaited<ReturnType<typeof putLiveRoomsIdParticipantsIdentityRole>>>
    export type PutLiveRoomsIdParticipantsIdentityRoleMutationBody = GithubCom4H1RZooraInternalDomainSetParticipantRoleDTO
    export type PutLiveRoomsIdParticipantsIdentityRoleMutationError = ErrorType<PutLiveRoomsIdParticipantsIdentityRole400 | PutLiveRoomsIdParticipantsIdentityRole401 | PutLiveRoomsIdParticipantsIdentityRole403 | PutLiveRoomsIdParticipantsIdentityRole404>

    /**
 * @summary Set participant role
 */
export const usePutLiveRoomsIdParticipantsIdentityRole = <TError = ErrorType<PutLiveRoomsIdParticipantsIdentityRole400 | PutLiveRoomsIdParticipantsIdentityRole401 | PutLiveRoomsIdParticipantsIdentityRole403 | PutLiveRoomsIdParticipantsIdentityRole404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putLiveRoomsIdParticipantsIdentityRole>>, TError,{id: string;identity: string;data: GithubCom4H1RZooraInternalDomainSetParticipantRoleDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putLiveRoomsIdParticipantsIdentityRole>>,
        TError,
        {id: string;identity: string;data: GithubCom4H1RZooraInternalDomainSetParticipantRoleDTO},
        TContext
      > => {
      return useMutation(getPutLiveRoomsIdParticipantsIdentityRoleMutationOptions(options), queryClient);
    }
    export type getLiveRoomsIdRecordingsResponse200 = {
  data: GetLiveRoomsIdRecordings200
  status: 200
}

export type getLiveRoomsIdRecordingsResponse401 = {
  data: GetLiveRoomsIdRecordings401
  status: 401
}

export type getLiveRoomsIdRecordingsResponse403 = {
  data: GetLiveRoomsIdRecordings403
  status: 403
}

export type getLiveRoomsIdRecordingsResponse404 = {
  data: GetLiveRoomsIdRecordings404
  status: 404
}

export type getLiveRoomsIdRecordingsResponseSuccess = (getLiveRoomsIdRecordingsResponse200) & {
  headers: Headers;
};
export type getLiveRoomsIdRecordingsResponseError = (getLiveRoomsIdRecordingsResponse401 | getLiveRoomsIdRecordingsResponse403 | getLiveRoomsIdRecordingsResponse404) & {
  headers: Headers;
};

export type getLiveRoomsIdRecordingsResponse = (getLiveRoomsIdRecordingsResponseSuccess | getLiveRoomsIdRecordingsResponseError)

export const getGetLiveRoomsIdRecordingsUrl = (id: string,
    params?: GetLiveRoomsIdRecordingsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/live-rooms/${id}/recordings?${stringifiedParams}` : `/live-rooms/${id}/recordings`
}

/**
 * Orderable fields: started_at, ended_at, created_at, duration, size. Filters: status.
 * @summary List recordings
 */
export const getLiveRoomsIdRecordings = async (id: string,
    params?: GetLiveRoomsIdRecordingsParams, options?: RequestInit): Promise<getLiveRoomsIdRecordingsResponse> => {

  return customInstance<getLiveRoomsIdRecordingsResponse>(getGetLiveRoomsIdRecordingsUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLiveRoomsIdRecordingsQueryKey = (id: string,
    params?: GetLiveRoomsIdRecordingsParams,) => {
    return [
    `/live-rooms/${id}/recordings`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetLiveRoomsIdRecordingsQueryOptions = <TData = Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>, TError = ErrorType<GetLiveRoomsIdRecordings401 | GetLiveRoomsIdRecordings403 | GetLiveRoomsIdRecordings404>>(id: string,
    params?: GetLiveRoomsIdRecordingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLiveRoomsIdRecordingsQueryKey(id,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>> = ({ signal }) => getLiveRoomsIdRecordings(id,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLiveRoomsIdRecordingsQueryResult = NonNullable<Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>>
export type GetLiveRoomsIdRecordingsQueryError = ErrorType<GetLiveRoomsIdRecordings401 | GetLiveRoomsIdRecordings403 | GetLiveRoomsIdRecordings404>


export function useGetLiveRoomsIdRecordings<TData = Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>, TError = ErrorType<GetLiveRoomsIdRecordings401 | GetLiveRoomsIdRecordings403 | GetLiveRoomsIdRecordings404>>(
 id: string,
    params: undefined |  GetLiveRoomsIdRecordingsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>,
          TError,
          Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLiveRoomsIdRecordings<TData = Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>, TError = ErrorType<GetLiveRoomsIdRecordings401 | GetLiveRoomsIdRecordings403 | GetLiveRoomsIdRecordings404>>(
 id: string,
    params?: GetLiveRoomsIdRecordingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>,
          TError,
          Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLiveRoomsIdRecordings<TData = Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>, TError = ErrorType<GetLiveRoomsIdRecordings401 | GetLiveRoomsIdRecordings403 | GetLiveRoomsIdRecordings404>>(
 id: string,
    params?: GetLiveRoomsIdRecordingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List recordings
 */

export function useGetLiveRoomsIdRecordings<TData = Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>, TError = ErrorType<GetLiveRoomsIdRecordings401 | GetLiveRoomsIdRecordings403 | GetLiveRoomsIdRecordings404>>(
 id: string,
    params?: GetLiveRoomsIdRecordingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdRecordings>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLiveRoomsIdRecordingsQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postLiveRoomsIdRecordingsResponse201 = {
  data: PostLiveRoomsIdRecordings201
  status: 201
}

export type postLiveRoomsIdRecordingsResponse400 = {
  data: PostLiveRoomsIdRecordings400
  status: 400
}

export type postLiveRoomsIdRecordingsResponse401 = {
  data: PostLiveRoomsIdRecordings401
  status: 401
}

export type postLiveRoomsIdRecordingsResponse403 = {
  data: PostLiveRoomsIdRecordings403
  status: 403
}

export type postLiveRoomsIdRecordingsResponse404 = {
  data: PostLiveRoomsIdRecordings404
  status: 404
}

export type postLiveRoomsIdRecordingsResponseSuccess = (postLiveRoomsIdRecordingsResponse201) & {
  headers: Headers;
};
export type postLiveRoomsIdRecordingsResponseError = (postLiveRoomsIdRecordingsResponse400 | postLiveRoomsIdRecordingsResponse401 | postLiveRoomsIdRecordingsResponse403 | postLiveRoomsIdRecordingsResponse404) & {
  headers: Headers;
};

export type postLiveRoomsIdRecordingsResponse = (postLiveRoomsIdRecordingsResponseSuccess | postLiveRoomsIdRecordingsResponseError)

export const getPostLiveRoomsIdRecordingsUrl = (id: string,) => {




  return `/live-rooms/${id}/recordings`
}

/**
 * @summary Start recording
 */
export const postLiveRoomsIdRecordings = async (id: string, options?: RequestInit): Promise<postLiveRoomsIdRecordingsResponse> => {

  return customInstance<postLiveRoomsIdRecordingsResponse>(getPostLiveRoomsIdRecordingsUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostLiveRoomsIdRecordingsMutationOptions = <TError = ErrorType<PostLiveRoomsIdRecordings400 | PostLiveRoomsIdRecordings401 | PostLiveRoomsIdRecordings403 | PostLiveRoomsIdRecordings404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdRecordings>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdRecordings>>, TError,{id: string}, TContext> => {

const mutationKey = ['postLiveRoomsIdRecordings'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLiveRoomsIdRecordings>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postLiveRoomsIdRecordings(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLiveRoomsIdRecordingsMutationResult = NonNullable<Awaited<ReturnType<typeof postLiveRoomsIdRecordings>>>

    export type PostLiveRoomsIdRecordingsMutationError = ErrorType<PostLiveRoomsIdRecordings400 | PostLiveRoomsIdRecordings401 | PostLiveRoomsIdRecordings403 | PostLiveRoomsIdRecordings404>

    /**
 * @summary Start recording
 */
export const usePostLiveRoomsIdRecordings = <TError = ErrorType<PostLiveRoomsIdRecordings400 | PostLiveRoomsIdRecordings401 | PostLiveRoomsIdRecordings403 | PostLiveRoomsIdRecordings404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdRecordings>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLiveRoomsIdRecordings>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPostLiveRoomsIdRecordingsMutationOptions(options), queryClient);
    }
    export type postLiveRoomsIdRecordingsRecordingIdStopResponse200 = {
  data: PostLiveRoomsIdRecordingsRecordingIdStop200
  status: 200
}

export type postLiveRoomsIdRecordingsRecordingIdStopResponse400 = {
  data: PostLiveRoomsIdRecordingsRecordingIdStop400
  status: 400
}

export type postLiveRoomsIdRecordingsRecordingIdStopResponse401 = {
  data: PostLiveRoomsIdRecordingsRecordingIdStop401
  status: 401
}

export type postLiveRoomsIdRecordingsRecordingIdStopResponse403 = {
  data: PostLiveRoomsIdRecordingsRecordingIdStop403
  status: 403
}

export type postLiveRoomsIdRecordingsRecordingIdStopResponse404 = {
  data: PostLiveRoomsIdRecordingsRecordingIdStop404
  status: 404
}

export type postLiveRoomsIdRecordingsRecordingIdStopResponseSuccess = (postLiveRoomsIdRecordingsRecordingIdStopResponse200) & {
  headers: Headers;
};
export type postLiveRoomsIdRecordingsRecordingIdStopResponseError = (postLiveRoomsIdRecordingsRecordingIdStopResponse400 | postLiveRoomsIdRecordingsRecordingIdStopResponse401 | postLiveRoomsIdRecordingsRecordingIdStopResponse403 | postLiveRoomsIdRecordingsRecordingIdStopResponse404) & {
  headers: Headers;
};

export type postLiveRoomsIdRecordingsRecordingIdStopResponse = (postLiveRoomsIdRecordingsRecordingIdStopResponseSuccess | postLiveRoomsIdRecordingsRecordingIdStopResponseError)

export const getPostLiveRoomsIdRecordingsRecordingIdStopUrl = (id: string,
    recordingId: string,) => {




  return `/live-rooms/${id}/recordings/${recordingId}/stop`
}

/**
 * @summary Stop recording
 */
export const postLiveRoomsIdRecordingsRecordingIdStop = async (id: string,
    recordingId: string, options?: RequestInit): Promise<postLiveRoomsIdRecordingsRecordingIdStopResponse> => {

  return customInstance<postLiveRoomsIdRecordingsRecordingIdStopResponse>(getPostLiveRoomsIdRecordingsRecordingIdStopUrl(id,recordingId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostLiveRoomsIdRecordingsRecordingIdStopMutationOptions = <TError = ErrorType<PostLiveRoomsIdRecordingsRecordingIdStop400 | PostLiveRoomsIdRecordingsRecordingIdStop401 | PostLiveRoomsIdRecordingsRecordingIdStop403 | PostLiveRoomsIdRecordingsRecordingIdStop404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdRecordingsRecordingIdStop>>, TError,{id: string;recordingId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdRecordingsRecordingIdStop>>, TError,{id: string;recordingId: string}, TContext> => {

const mutationKey = ['postLiveRoomsIdRecordingsRecordingIdStop'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLiveRoomsIdRecordingsRecordingIdStop>>, {id: string;recordingId: string}> = (props) => {
          const {id,recordingId} = props ?? {};

          return  postLiveRoomsIdRecordingsRecordingIdStop(id,recordingId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLiveRoomsIdRecordingsRecordingIdStopMutationResult = NonNullable<Awaited<ReturnType<typeof postLiveRoomsIdRecordingsRecordingIdStop>>>

    export type PostLiveRoomsIdRecordingsRecordingIdStopMutationError = ErrorType<PostLiveRoomsIdRecordingsRecordingIdStop400 | PostLiveRoomsIdRecordingsRecordingIdStop401 | PostLiveRoomsIdRecordingsRecordingIdStop403 | PostLiveRoomsIdRecordingsRecordingIdStop404>

    /**
 * @summary Stop recording
 */
export const usePostLiveRoomsIdRecordingsRecordingIdStop = <TError = ErrorType<PostLiveRoomsIdRecordingsRecordingIdStop400 | PostLiveRoomsIdRecordingsRecordingIdStop401 | PostLiveRoomsIdRecordingsRecordingIdStop403 | PostLiveRoomsIdRecordingsRecordingIdStop404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdRecordingsRecordingIdStop>>, TError,{id: string;recordingId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLiveRoomsIdRecordingsRecordingIdStop>>,
        TError,
        {id: string;recordingId: string},
        TContext
      > => {
      return useMutation(getPostLiveRoomsIdRecordingsRecordingIdStopMutationOptions(options), queryClient);
    }
    export type postLiveRoomsIdStartResponse200 = {
  data: PostLiveRoomsIdStart200
  status: 200
}

export type postLiveRoomsIdStartResponse400 = {
  data: PostLiveRoomsIdStart400
  status: 400
}

export type postLiveRoomsIdStartResponse401 = {
  data: PostLiveRoomsIdStart401
  status: 401
}

export type postLiveRoomsIdStartResponse403 = {
  data: PostLiveRoomsIdStart403
  status: 403
}

export type postLiveRoomsIdStartResponse404 = {
  data: PostLiveRoomsIdStart404
  status: 404
}

export type postLiveRoomsIdStartResponseSuccess = (postLiveRoomsIdStartResponse200) & {
  headers: Headers;
};
export type postLiveRoomsIdStartResponseError = (postLiveRoomsIdStartResponse400 | postLiveRoomsIdStartResponse401 | postLiveRoomsIdStartResponse403 | postLiveRoomsIdStartResponse404) & {
  headers: Headers;
};

export type postLiveRoomsIdStartResponse = (postLiveRoomsIdStartResponseSuccess | postLiveRoomsIdStartResponseError)

export const getPostLiveRoomsIdStartUrl = (id: string,) => {




  return `/live-rooms/${id}/start`
}

/**
 * @summary Start live room
 */
export const postLiveRoomsIdStart = async (id: string, options?: RequestInit): Promise<postLiveRoomsIdStartResponse> => {

  return customInstance<postLiveRoomsIdStartResponse>(getPostLiveRoomsIdStartUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostLiveRoomsIdStartMutationOptions = <TError = ErrorType<PostLiveRoomsIdStart400 | PostLiveRoomsIdStart401 | PostLiveRoomsIdStart403 | PostLiveRoomsIdStart404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdStart>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdStart>>, TError,{id: string}, TContext> => {

const mutationKey = ['postLiveRoomsIdStart'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLiveRoomsIdStart>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  postLiveRoomsIdStart(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLiveRoomsIdStartMutationResult = NonNullable<Awaited<ReturnType<typeof postLiveRoomsIdStart>>>

    export type PostLiveRoomsIdStartMutationError = ErrorType<PostLiveRoomsIdStart400 | PostLiveRoomsIdStart401 | PostLiveRoomsIdStart403 | PostLiveRoomsIdStart404>

    /**
 * @summary Start live room
 */
export const usePostLiveRoomsIdStart = <TError = ErrorType<PostLiveRoomsIdStart400 | PostLiveRoomsIdStart401 | PostLiveRoomsIdStart403 | PostLiveRoomsIdStart404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLiveRoomsIdStart>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLiveRoomsIdStart>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getPostLiveRoomsIdStartMutationOptions(options), queryClient);
    }
    export type getLiveRoomsIdWhiteboardResponse200 = {
  data: GetLiveRoomsIdWhiteboard200
  status: 200
}

export type getLiveRoomsIdWhiteboardResponse401 = {
  data: GetLiveRoomsIdWhiteboard401
  status: 401
}

export type getLiveRoomsIdWhiteboardResponse403 = {
  data: GetLiveRoomsIdWhiteboard403
  status: 403
}

export type getLiveRoomsIdWhiteboardResponse404 = {
  data: GetLiveRoomsIdWhiteboard404
  status: 404
}

export type getLiveRoomsIdWhiteboardResponseSuccess = (getLiveRoomsIdWhiteboardResponse200) & {
  headers: Headers;
};
export type getLiveRoomsIdWhiteboardResponseError = (getLiveRoomsIdWhiteboardResponse401 | getLiveRoomsIdWhiteboardResponse403 | getLiveRoomsIdWhiteboardResponse404) & {
  headers: Headers;
};

export type getLiveRoomsIdWhiteboardResponse = (getLiveRoomsIdWhiteboardResponseSuccess | getLiveRoomsIdWhiteboardResponseError)

export const getGetLiveRoomsIdWhiteboardUrl = (id: string,) => {




  return `/live-rooms/${id}/whiteboard`
}

/**
 * Returns the persisted tldraw snapshot. Any room participant (viewer or above) may read it. Returns an empty board ({}) if no snapshot has been saved yet.
 * @summary Get whiteboard snapshot
 */
export const getLiveRoomsIdWhiteboard = async (id: string, options?: RequestInit): Promise<getLiveRoomsIdWhiteboardResponse> => {

  return customInstance<getLiveRoomsIdWhiteboardResponse>(getGetLiveRoomsIdWhiteboardUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetLiveRoomsIdWhiteboardQueryKey = (id: string,) => {
    return [
    `/live-rooms/${id}/whiteboard`
    ] as const;
    }


export const getGetLiveRoomsIdWhiteboardQueryOptions = <TData = Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>, TError = ErrorType<GetLiveRoomsIdWhiteboard401 | GetLiveRoomsIdWhiteboard403 | GetLiveRoomsIdWhiteboard404>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLiveRoomsIdWhiteboardQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>> = ({ signal }) => getLiveRoomsIdWhiteboard(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLiveRoomsIdWhiteboardQueryResult = NonNullable<Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>>
export type GetLiveRoomsIdWhiteboardQueryError = ErrorType<GetLiveRoomsIdWhiteboard401 | GetLiveRoomsIdWhiteboard403 | GetLiveRoomsIdWhiteboard404>


export function useGetLiveRoomsIdWhiteboard<TData = Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>, TError = ErrorType<GetLiveRoomsIdWhiteboard401 | GetLiveRoomsIdWhiteboard403 | GetLiveRoomsIdWhiteboard404>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>,
          TError,
          Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLiveRoomsIdWhiteboard<TData = Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>, TError = ErrorType<GetLiveRoomsIdWhiteboard401 | GetLiveRoomsIdWhiteboard403 | GetLiveRoomsIdWhiteboard404>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>,
          TError,
          Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLiveRoomsIdWhiteboard<TData = Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>, TError = ErrorType<GetLiveRoomsIdWhiteboard401 | GetLiveRoomsIdWhiteboard403 | GetLiveRoomsIdWhiteboard404>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get whiteboard snapshot
 */

export function useGetLiveRoomsIdWhiteboard<TData = Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>, TError = ErrorType<GetLiveRoomsIdWhiteboard401 | GetLiveRoomsIdWhiteboard403 | GetLiveRoomsIdWhiteboard404>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLiveRoomsIdWhiteboard>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLiveRoomsIdWhiteboardQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type putLiveRoomsIdWhiteboardResponse200 = {
  data: PutLiveRoomsIdWhiteboard200
  status: 200
}

export type putLiveRoomsIdWhiteboardResponse400 = {
  data: PutLiveRoomsIdWhiteboard400
  status: 400
}

export type putLiveRoomsIdWhiteboardResponse401 = {
  data: PutLiveRoomsIdWhiteboard401
  status: 401
}

export type putLiveRoomsIdWhiteboardResponse403 = {
  data: PutLiveRoomsIdWhiteboard403
  status: 403
}

export type putLiveRoomsIdWhiteboardResponse404 = {
  data: PutLiveRoomsIdWhiteboard404
  status: 404
}

export type putLiveRoomsIdWhiteboardResponseSuccess = (putLiveRoomsIdWhiteboardResponse200) & {
  headers: Headers;
};
export type putLiveRoomsIdWhiteboardResponseError = (putLiveRoomsIdWhiteboardResponse400 | putLiveRoomsIdWhiteboardResponse401 | putLiveRoomsIdWhiteboardResponse403 | putLiveRoomsIdWhiteboardResponse404) & {
  headers: Headers;
};

export type putLiveRoomsIdWhiteboardResponse = (putLiveRoomsIdWhiteboardResponseSuccess | putLiveRoomsIdWhiteboardResponseError)

export const getPutLiveRoomsIdWhiteboardUrl = (id: string,) => {




  return `/live-rooms/${id}/whiteboard`
}

/**
 * Upserts the tldraw snapshot. Only hosts and presenters may write.
 * @summary Save whiteboard snapshot
 */
export const putLiveRoomsIdWhiteboard = async (id: string,
    githubCom4H1RZooraInternalDomainSaveWhiteboardDTO: GithubCom4H1RZooraInternalDomainSaveWhiteboardDTO, options?: RequestInit): Promise<putLiveRoomsIdWhiteboardResponse> => {

  return customInstance<putLiveRoomsIdWhiteboardResponse>(getPutLiveRoomsIdWhiteboardUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainSaveWhiteboardDTO)
  }
);}




export const getPutLiveRoomsIdWhiteboardMutationOptions = <TError = ErrorType<PutLiveRoomsIdWhiteboard400 | PutLiveRoomsIdWhiteboard401 | PutLiveRoomsIdWhiteboard403 | PutLiveRoomsIdWhiteboard404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putLiveRoomsIdWhiteboard>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainSaveWhiteboardDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putLiveRoomsIdWhiteboard>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainSaveWhiteboardDTO}, TContext> => {

const mutationKey = ['putLiveRoomsIdWhiteboard'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putLiveRoomsIdWhiteboard>>, {id: string;data: GithubCom4H1RZooraInternalDomainSaveWhiteboardDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  putLiveRoomsIdWhiteboard(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutLiveRoomsIdWhiteboardMutationResult = NonNullable<Awaited<ReturnType<typeof putLiveRoomsIdWhiteboard>>>
    export type PutLiveRoomsIdWhiteboardMutationBody = GithubCom4H1RZooraInternalDomainSaveWhiteboardDTO
    export type PutLiveRoomsIdWhiteboardMutationError = ErrorType<PutLiveRoomsIdWhiteboard400 | PutLiveRoomsIdWhiteboard401 | PutLiveRoomsIdWhiteboard403 | PutLiveRoomsIdWhiteboard404>

    /**
 * @summary Save whiteboard snapshot
 */
export const usePutLiveRoomsIdWhiteboard = <TError = ErrorType<PutLiveRoomsIdWhiteboard400 | PutLiveRoomsIdWhiteboard401 | PutLiveRoomsIdWhiteboard403 | PutLiveRoomsIdWhiteboard404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putLiveRoomsIdWhiteboard>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainSaveWhiteboardDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putLiveRoomsIdWhiteboard>>,
        TError,
        {id: string;data: GithubCom4H1RZooraInternalDomainSaveWhiteboardDTO},
        TContext
      > => {
      return useMutation(getPutLiveRoomsIdWhiteboardMutationOptions(options), queryClient);
    }
