/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Zoora API
 * REST API for the Zoora education platform.
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteCustomFieldDefinitionsId403,
  DeleteCustomFieldDefinitionsId404,
  GetCustomFieldDefinitions200,
  GetCustomFieldDefinitions401,
  GetCustomFieldDefinitions403,
  GetUsersIdCustomFields200,
  GetUsersIdCustomFields401,
  GetUsersIdCustomFields403,
  GetUsersIdCustomFields404,
  GithubCom4H1RZooraInternalDomainCreateCustomFieldDefinitionDTO,
  GithubCom4H1RZooraInternalDomainSetUserCustomFieldsDTO,
  GithubCom4H1RZooraInternalDomainUpdateCustomFieldDefinitionDTO,
  PatchCustomFieldDefinitionsId200,
  PatchCustomFieldDefinitionsId400,
  PatchCustomFieldDefinitionsId403,
  PatchCustomFieldDefinitionsId404,
  PatchCustomFieldDefinitionsId409,
  PatchUsersIdCustomFields200,
  PatchUsersIdCustomFields400,
  PatchUsersIdCustomFields403,
  PatchUsersIdCustomFields404,
  PatchUsersIdCustomFields409,
  PostCustomFieldDefinitions201,
  PostCustomFieldDefinitions400,
  PostCustomFieldDefinitions403,
  PostCustomFieldDefinitions422
} from '../model';

import { customInstance } from '.././mutator/custom-instance';
import type { ErrorType } from '.././mutator/custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getCustomFieldDefinitionsResponse200 = {
  data: GetCustomFieldDefinitions200
  status: 200
}

export type getCustomFieldDefinitionsResponse401 = {
  data: GetCustomFieldDefinitions401
  status: 401
}

export type getCustomFieldDefinitionsResponse403 = {
  data: GetCustomFieldDefinitions403
  status: 403
}

export type getCustomFieldDefinitionsResponseSuccess = (getCustomFieldDefinitionsResponse200) & {
  headers: Headers;
};
export type getCustomFieldDefinitionsResponseError = (getCustomFieldDefinitionsResponse401 | getCustomFieldDefinitionsResponse403) & {
  headers: Headers;
};

export type getCustomFieldDefinitionsResponse = (getCustomFieldDefinitionsResponseSuccess | getCustomFieldDefinitionsResponseError)

export const getGetCustomFieldDefinitionsUrl = () => {




  return `/custom-field-definitions`
}

/**
 * @summary List custom field definitions
 */
export const getCustomFieldDefinitions = async ( options?: RequestInit): Promise<getCustomFieldDefinitionsResponse> => {

  return customInstance<getCustomFieldDefinitionsResponse>(getGetCustomFieldDefinitionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCustomFieldDefinitionsQueryKey = () => {
    return [
    `/custom-field-definitions`
    ] as const;
    }


export const getGetCustomFieldDefinitionsQueryOptions = <TData = Awaited<ReturnType<typeof getCustomFieldDefinitions>>, TError = ErrorType<GetCustomFieldDefinitions401 | GetCustomFieldDefinitions403>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomFieldDefinitions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCustomFieldDefinitionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCustomFieldDefinitions>>> = ({ signal }) => getCustomFieldDefinitions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCustomFieldDefinitions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCustomFieldDefinitionsQueryResult = NonNullable<Awaited<ReturnType<typeof getCustomFieldDefinitions>>>
export type GetCustomFieldDefinitionsQueryError = ErrorType<GetCustomFieldDefinitions401 | GetCustomFieldDefinitions403>


export function useGetCustomFieldDefinitions<TData = Awaited<ReturnType<typeof getCustomFieldDefinitions>>, TError = ErrorType<GetCustomFieldDefinitions401 | GetCustomFieldDefinitions403>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomFieldDefinitions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomFieldDefinitions>>,
          TError,
          Awaited<ReturnType<typeof getCustomFieldDefinitions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCustomFieldDefinitions<TData = Awaited<ReturnType<typeof getCustomFieldDefinitions>>, TError = ErrorType<GetCustomFieldDefinitions401 | GetCustomFieldDefinitions403>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomFieldDefinitions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomFieldDefinitions>>,
          TError,
          Awaited<ReturnType<typeof getCustomFieldDefinitions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCustomFieldDefinitions<TData = Awaited<ReturnType<typeof getCustomFieldDefinitions>>, TError = ErrorType<GetCustomFieldDefinitions401 | GetCustomFieldDefinitions403>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomFieldDefinitions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List custom field definitions
 */

export function useGetCustomFieldDefinitions<TData = Awaited<ReturnType<typeof getCustomFieldDefinitions>>, TError = ErrorType<GetCustomFieldDefinitions401 | GetCustomFieldDefinitions403>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomFieldDefinitions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCustomFieldDefinitionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postCustomFieldDefinitionsResponse201 = {
  data: PostCustomFieldDefinitions201
  status: 201
}

export type postCustomFieldDefinitionsResponse400 = {
  data: PostCustomFieldDefinitions400
  status: 400
}

export type postCustomFieldDefinitionsResponse403 = {
  data: PostCustomFieldDefinitions403
  status: 403
}

export type postCustomFieldDefinitionsResponse422 = {
  data: PostCustomFieldDefinitions422
  status: 422
}

export type postCustomFieldDefinitionsResponseSuccess = (postCustomFieldDefinitionsResponse201) & {
  headers: Headers;
};
export type postCustomFieldDefinitionsResponseError = (postCustomFieldDefinitionsResponse400 | postCustomFieldDefinitionsResponse403 | postCustomFieldDefinitionsResponse422) & {
  headers: Headers;
};

export type postCustomFieldDefinitionsResponse = (postCustomFieldDefinitionsResponseSuccess | postCustomFieldDefinitionsResponseError)

export const getPostCustomFieldDefinitionsUrl = () => {




  return `/custom-field-definitions`
}

/**
 * @summary Create custom field definition
 */
export const postCustomFieldDefinitions = async (githubCom4H1RZooraInternalDomainCreateCustomFieldDefinitionDTO: GithubCom4H1RZooraInternalDomainCreateCustomFieldDefinitionDTO, options?: RequestInit): Promise<postCustomFieldDefinitionsResponse> => {

  return customInstance<postCustomFieldDefinitionsResponse>(getPostCustomFieldDefinitionsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainCreateCustomFieldDefinitionDTO)
  }
);}





export const getPostCustomFieldDefinitionsMutationOptions = <TError = ErrorType<PostCustomFieldDefinitions400 | PostCustomFieldDefinitions403 | PostCustomFieldDefinitions422>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCustomFieldDefinitions>>, TError,{data: GithubCom4H1RZooraInternalDomainCreateCustomFieldDefinitionDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postCustomFieldDefinitions>>, TError,{data: GithubCom4H1RZooraInternalDomainCreateCustomFieldDefinitionDTO}, TContext> => {

const mutationKey = ['postCustomFieldDefinitions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCustomFieldDefinitions>>, {data: GithubCom4H1RZooraInternalDomainCreateCustomFieldDefinitionDTO}> = (props) => {
          const {data} = props ?? {};

          return  postCustomFieldDefinitions(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostCustomFieldDefinitionsMutationResult = NonNullable<Awaited<ReturnType<typeof postCustomFieldDefinitions>>>
    export type PostCustomFieldDefinitionsMutationBody = GithubCom4H1RZooraInternalDomainCreateCustomFieldDefinitionDTO
    export type PostCustomFieldDefinitionsMutationError = ErrorType<PostCustomFieldDefinitions400 | PostCustomFieldDefinitions403 | PostCustomFieldDefinitions422>

    /**
 * @summary Create custom field definition
 */
export const usePostCustomFieldDefinitions = <TError = ErrorType<PostCustomFieldDefinitions400 | PostCustomFieldDefinitions403 | PostCustomFieldDefinitions422>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCustomFieldDefinitions>>, TError,{data: GithubCom4H1RZooraInternalDomainCreateCustomFieldDefinitionDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postCustomFieldDefinitions>>,
        TError,
        {data: GithubCom4H1RZooraInternalDomainCreateCustomFieldDefinitionDTO},
        TContext
      > => {
      return useMutation(getPostCustomFieldDefinitionsMutationOptions(options), queryClient);
    }
    export type deleteCustomFieldDefinitionsIdResponse204 = {
  data: void
  status: 204
}

export type deleteCustomFieldDefinitionsIdResponse403 = {
  data: DeleteCustomFieldDefinitionsId403
  status: 403
}

export type deleteCustomFieldDefinitionsIdResponse404 = {
  data: DeleteCustomFieldDefinitionsId404
  status: 404
}

export type deleteCustomFieldDefinitionsIdResponseSuccess = (deleteCustomFieldDefinitionsIdResponse204) & {
  headers: Headers;
};
export type deleteCustomFieldDefinitionsIdResponseError = (deleteCustomFieldDefinitionsIdResponse403 | deleteCustomFieldDefinitionsIdResponse404) & {
  headers: Headers;
};

export type deleteCustomFieldDefinitionsIdResponse = (deleteCustomFieldDefinitionsIdResponseSuccess | deleteCustomFieldDefinitionsIdResponseError)

export const getDeleteCustomFieldDefinitionsIdUrl = (id: string,) => {




  return `/custom-field-definitions/${id}`
}

/**
 * @summary Archive custom field definition
 */
export const deleteCustomFieldDefinitionsId = async (id: string, options?: RequestInit): Promise<deleteCustomFieldDefinitionsIdResponse> => {

  return customInstance<deleteCustomFieldDefinitionsIdResponse>(getDeleteCustomFieldDefinitionsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteCustomFieldDefinitionsIdMutationOptions = <TError = ErrorType<DeleteCustomFieldDefinitionsId403 | DeleteCustomFieldDefinitionsId404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomFieldDefinitionsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCustomFieldDefinitionsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteCustomFieldDefinitionsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCustomFieldDefinitionsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteCustomFieldDefinitionsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCustomFieldDefinitionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCustomFieldDefinitionsId>>>

    export type DeleteCustomFieldDefinitionsIdMutationError = ErrorType<DeleteCustomFieldDefinitionsId403 | DeleteCustomFieldDefinitionsId404>

    /**
 * @summary Archive custom field definition
 */
export const useDeleteCustomFieldDefinitionsId = <TError = ErrorType<DeleteCustomFieldDefinitionsId403 | DeleteCustomFieldDefinitionsId404>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomFieldDefinitionsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCustomFieldDefinitionsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteCustomFieldDefinitionsIdMutationOptions(options), queryClient);
    }
    export type patchCustomFieldDefinitionsIdResponse200 = {
  data: PatchCustomFieldDefinitionsId200
  status: 200
}

export type patchCustomFieldDefinitionsIdResponse400 = {
  data: PatchCustomFieldDefinitionsId400
  status: 400
}

export type patchCustomFieldDefinitionsIdResponse403 = {
  data: PatchCustomFieldDefinitionsId403
  status: 403
}

export type patchCustomFieldDefinitionsIdResponse404 = {
  data: PatchCustomFieldDefinitionsId404
  status: 404
}

export type patchCustomFieldDefinitionsIdResponse409 = {
  data: PatchCustomFieldDefinitionsId409
  status: 409
}

export type patchCustomFieldDefinitionsIdResponseSuccess = (patchCustomFieldDefinitionsIdResponse200) & {
  headers: Headers;
};
export type patchCustomFieldDefinitionsIdResponseError = (patchCustomFieldDefinitionsIdResponse400 | patchCustomFieldDefinitionsIdResponse403 | patchCustomFieldDefinitionsIdResponse404 | patchCustomFieldDefinitionsIdResponse409) & {
  headers: Headers;
};

export type patchCustomFieldDefinitionsIdResponse = (patchCustomFieldDefinitionsIdResponseSuccess | patchCustomFieldDefinitionsIdResponseError)

export const getPatchCustomFieldDefinitionsIdUrl = (id: string,) => {




  return `/custom-field-definitions/${id}`
}

/**
 * @summary Update custom field definition
 */
export const patchCustomFieldDefinitionsId = async (id: string,
    githubCom4H1RZooraInternalDomainUpdateCustomFieldDefinitionDTO: GithubCom4H1RZooraInternalDomainUpdateCustomFieldDefinitionDTO, options?: RequestInit): Promise<patchCustomFieldDefinitionsIdResponse> => {

  return customInstance<patchCustomFieldDefinitionsIdResponse>(getPatchCustomFieldDefinitionsIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainUpdateCustomFieldDefinitionDTO)
  }
);}





export const getPatchCustomFieldDefinitionsIdMutationOptions = <TError = ErrorType<PatchCustomFieldDefinitionsId400 | PatchCustomFieldDefinitionsId403 | PatchCustomFieldDefinitionsId404 | PatchCustomFieldDefinitionsId409>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchCustomFieldDefinitionsId>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainUpdateCustomFieldDefinitionDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchCustomFieldDefinitionsId>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainUpdateCustomFieldDefinitionDTO}, TContext> => {

const mutationKey = ['patchCustomFieldDefinitionsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchCustomFieldDefinitionsId>>, {id: string;data: GithubCom4H1RZooraInternalDomainUpdateCustomFieldDefinitionDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  patchCustomFieldDefinitionsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchCustomFieldDefinitionsIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchCustomFieldDefinitionsId>>>
    export type PatchCustomFieldDefinitionsIdMutationBody = GithubCom4H1RZooraInternalDomainUpdateCustomFieldDefinitionDTO
    export type PatchCustomFieldDefinitionsIdMutationError = ErrorType<PatchCustomFieldDefinitionsId400 | PatchCustomFieldDefinitionsId403 | PatchCustomFieldDefinitionsId404 | PatchCustomFieldDefinitionsId409>

    /**
 * @summary Update custom field definition
 */
export const usePatchCustomFieldDefinitionsId = <TError = ErrorType<PatchCustomFieldDefinitionsId400 | PatchCustomFieldDefinitionsId403 | PatchCustomFieldDefinitionsId404 | PatchCustomFieldDefinitionsId409>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchCustomFieldDefinitionsId>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainUpdateCustomFieldDefinitionDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchCustomFieldDefinitionsId>>,
        TError,
        {id: string;data: GithubCom4H1RZooraInternalDomainUpdateCustomFieldDefinitionDTO},
        TContext
      > => {
      return useMutation(getPatchCustomFieldDefinitionsIdMutationOptions(options), queryClient);
    }
    export type getUsersIdCustomFieldsResponse200 = {
  data: GetUsersIdCustomFields200
  status: 200
}

export type getUsersIdCustomFieldsResponse401 = {
  data: GetUsersIdCustomFields401
  status: 401
}

export type getUsersIdCustomFieldsResponse403 = {
  data: GetUsersIdCustomFields403
  status: 403
}

export type getUsersIdCustomFieldsResponse404 = {
  data: GetUsersIdCustomFields404
  status: 404
}

export type getUsersIdCustomFieldsResponseSuccess = (getUsersIdCustomFieldsResponse200) & {
  headers: Headers;
};
export type getUsersIdCustomFieldsResponseError = (getUsersIdCustomFieldsResponse401 | getUsersIdCustomFieldsResponse403 | getUsersIdCustomFieldsResponse404) & {
  headers: Headers;
};

export type getUsersIdCustomFieldsResponse = (getUsersIdCustomFieldsResponseSuccess | getUsersIdCustomFieldsResponseError)

export const getGetUsersIdCustomFieldsUrl = (id: string,) => {




  return `/users/${id}/custom-fields`
}

/**
 * @summary Get a user's visible custom field values
 */
export const getUsersIdCustomFields = async (id: string, options?: RequestInit): Promise<getUsersIdCustomFieldsResponse> => {

  return customInstance<getUsersIdCustomFieldsResponse>(getGetUsersIdCustomFieldsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUsersIdCustomFieldsQueryKey = (id: string,) => {
    return [
    `/users/${id}/custom-fields`
    ] as const;
    }


export const getGetUsersIdCustomFieldsQueryOptions = <TData = Awaited<ReturnType<typeof getUsersIdCustomFields>>, TError = ErrorType<GetUsersIdCustomFields401 | GetUsersIdCustomFields403 | GetUsersIdCustomFields404>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersIdCustomFields>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersIdCustomFieldsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersIdCustomFields>>> = ({ signal }) => getUsersIdCustomFields(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersIdCustomFields>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersIdCustomFieldsQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersIdCustomFields>>>
export type GetUsersIdCustomFieldsQueryError = ErrorType<GetUsersIdCustomFields401 | GetUsersIdCustomFields403 | GetUsersIdCustomFields404>


export function useGetUsersIdCustomFields<TData = Awaited<ReturnType<typeof getUsersIdCustomFields>>, TError = ErrorType<GetUsersIdCustomFields401 | GetUsersIdCustomFields403 | GetUsersIdCustomFields404>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersIdCustomFields>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersIdCustomFields>>,
          TError,
          Awaited<ReturnType<typeof getUsersIdCustomFields>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersIdCustomFields<TData = Awaited<ReturnType<typeof getUsersIdCustomFields>>, TError = ErrorType<GetUsersIdCustomFields401 | GetUsersIdCustomFields403 | GetUsersIdCustomFields404>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersIdCustomFields>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersIdCustomFields>>,
          TError,
          Awaited<ReturnType<typeof getUsersIdCustomFields>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersIdCustomFields<TData = Awaited<ReturnType<typeof getUsersIdCustomFields>>, TError = ErrorType<GetUsersIdCustomFields401 | GetUsersIdCustomFields403 | GetUsersIdCustomFields404>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersIdCustomFields>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a user's visible custom field values
 */

export function useGetUsersIdCustomFields<TData = Awaited<ReturnType<typeof getUsersIdCustomFields>>, TError = ErrorType<GetUsersIdCustomFields401 | GetUsersIdCustomFields403 | GetUsersIdCustomFields404>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersIdCustomFields>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersIdCustomFieldsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type patchUsersIdCustomFieldsResponse200 = {
  data: PatchUsersIdCustomFields200
  status: 200
}

export type patchUsersIdCustomFieldsResponse400 = {
  data: PatchUsersIdCustomFields400
  status: 400
}

export type patchUsersIdCustomFieldsResponse403 = {
  data: PatchUsersIdCustomFields403
  status: 403
}

export type patchUsersIdCustomFieldsResponse404 = {
  data: PatchUsersIdCustomFields404
  status: 404
}

export type patchUsersIdCustomFieldsResponse409 = {
  data: PatchUsersIdCustomFields409
  status: 409
}

export type patchUsersIdCustomFieldsResponseSuccess = (patchUsersIdCustomFieldsResponse200) & {
  headers: Headers;
};
export type patchUsersIdCustomFieldsResponseError = (patchUsersIdCustomFieldsResponse400 | patchUsersIdCustomFieldsResponse403 | patchUsersIdCustomFieldsResponse404 | patchUsersIdCustomFieldsResponse409) & {
  headers: Headers;
};

export type patchUsersIdCustomFieldsResponse = (patchUsersIdCustomFieldsResponseSuccess | patchUsersIdCustomFieldsResponseError)

export const getPatchUsersIdCustomFieldsUrl = (id: string,) => {




  return `/users/${id}/custom-fields`
}

/**
 * @summary Set a user's custom field values (partial merge)
 */
export const patchUsersIdCustomFields = async (id: string,
    githubCom4H1RZooraInternalDomainSetUserCustomFieldsDTO: GithubCom4H1RZooraInternalDomainSetUserCustomFieldsDTO, options?: RequestInit): Promise<patchUsersIdCustomFieldsResponse> => {

  return customInstance<patchUsersIdCustomFieldsResponse>(getPatchUsersIdCustomFieldsUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(githubCom4H1RZooraInternalDomainSetUserCustomFieldsDTO)
  }
);}





export const getPatchUsersIdCustomFieldsMutationOptions = <TError = ErrorType<PatchUsersIdCustomFields400 | PatchUsersIdCustomFields403 | PatchUsersIdCustomFields404 | PatchUsersIdCustomFields409>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchUsersIdCustomFields>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainSetUserCustomFieldsDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof patchUsersIdCustomFields>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainSetUserCustomFieldsDTO}, TContext> => {

const mutationKey = ['patchUsersIdCustomFields'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchUsersIdCustomFields>>, {id: string;data: GithubCom4H1RZooraInternalDomainSetUserCustomFieldsDTO}> = (props) => {
          const {id,data} = props ?? {};

          return  patchUsersIdCustomFields(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchUsersIdCustomFieldsMutationResult = NonNullable<Awaited<ReturnType<typeof patchUsersIdCustomFields>>>
    export type PatchUsersIdCustomFieldsMutationBody = GithubCom4H1RZooraInternalDomainSetUserCustomFieldsDTO
    export type PatchUsersIdCustomFieldsMutationError = ErrorType<PatchUsersIdCustomFields400 | PatchUsersIdCustomFields403 | PatchUsersIdCustomFields404 | PatchUsersIdCustomFields409>

    /**
 * @summary Set a user's custom field values (partial merge)
 */
export const usePatchUsersIdCustomFields = <TError = ErrorType<PatchUsersIdCustomFields400 | PatchUsersIdCustomFields403 | PatchUsersIdCustomFields404 | PatchUsersIdCustomFields409>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchUsersIdCustomFields>>, TError,{id: string;data: GithubCom4H1RZooraInternalDomainSetUserCustomFieldsDTO}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchUsersIdCustomFields>>,
        TError,
        {id: string;data: GithubCom4H1RZooraInternalDomainSetUserCustomFieldsDTO},
        TContext
      > => {
      return useMutation(getPatchUsersIdCustomFieldsMutationOptions(options), queryClient);
    }
